/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.25.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package net.statemesh.k8s.crd.rayservice.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import net.statemesh.k8s.crd.rayservice.models.V1alpha1RayServiceSpecRayClusterConfigAutoscalerOptions;
import net.statemesh.k8s.crd.rayservice.models.V1alpha1RayServiceSpecRayClusterConfigHeadGroupSpec;
import net.statemesh.k8s.crd.rayservice.models.V1alpha1RayServiceSpecRayClusterConfigWorkerGroupSpecsInner;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import io.kubernetes.client.openapi.JSON;

/**
 * V1alpha1RayServiceSpecRayClusterConfig
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-09-11T07:02:38.554963Z[Etc/UTC]")
public class V1alpha1RayServiceSpecRayClusterConfig {
  public static final String SERIALIZED_NAME_AUTOSCALER_OPTIONS = "autoscalerOptions";
  @SerializedName(SERIALIZED_NAME_AUTOSCALER_OPTIONS)
  private V1alpha1RayServiceSpecRayClusterConfigAutoscalerOptions autoscalerOptions;

  public static final String SERIALIZED_NAME_ENABLE_IN_TREE_AUTOSCALING = "enableInTreeAutoscaling";
  @SerializedName(SERIALIZED_NAME_ENABLE_IN_TREE_AUTOSCALING)
  private Boolean enableInTreeAutoscaling;

  public static final String SERIALIZED_NAME_HEAD_GROUP_SPEC = "headGroupSpec";
  @SerializedName(SERIALIZED_NAME_HEAD_GROUP_SPEC)
  private V1alpha1RayServiceSpecRayClusterConfigHeadGroupSpec headGroupSpec;

  public static final String SERIALIZED_NAME_HEAD_SERVICE_ANNOTATIONS = "headServiceAnnotations";
  @SerializedName(SERIALIZED_NAME_HEAD_SERVICE_ANNOTATIONS)
  private Map<String, String> headServiceAnnotations = new HashMap<>();

  public static final String SERIALIZED_NAME_RAY_VERSION = "rayVersion";
  @SerializedName(SERIALIZED_NAME_RAY_VERSION)
  private String rayVersion;

  public static final String SERIALIZED_NAME_SUSPEND = "suspend";
  @SerializedName(SERIALIZED_NAME_SUSPEND)
  private Boolean suspend;

  public static final String SERIALIZED_NAME_WORKER_GROUP_SPECS = "workerGroupSpecs";
  @SerializedName(SERIALIZED_NAME_WORKER_GROUP_SPECS)
  private List<V1alpha1RayServiceSpecRayClusterConfigWorkerGroupSpecsInner> workerGroupSpecs;

  public V1alpha1RayServiceSpecRayClusterConfig() {
  }

  public V1alpha1RayServiceSpecRayClusterConfig autoscalerOptions(V1alpha1RayServiceSpecRayClusterConfigAutoscalerOptions autoscalerOptions) {
    
    this.autoscalerOptions = autoscalerOptions;
    return this;
  }

   /**
   * Get autoscalerOptions
   * @return autoscalerOptions
  **/
  @jakarta.annotation.Nullable
  public V1alpha1RayServiceSpecRayClusterConfigAutoscalerOptions getAutoscalerOptions() {
    return autoscalerOptions;
  }


  public void setAutoscalerOptions(V1alpha1RayServiceSpecRayClusterConfigAutoscalerOptions autoscalerOptions) {
    this.autoscalerOptions = autoscalerOptions;
  }


  public V1alpha1RayServiceSpecRayClusterConfig enableInTreeAutoscaling(Boolean enableInTreeAutoscaling) {
    
    this.enableInTreeAutoscaling = enableInTreeAutoscaling;
    return this;
  }

   /**
   * Get enableInTreeAutoscaling
   * @return enableInTreeAutoscaling
  **/
  @jakarta.annotation.Nullable
  public Boolean getEnableInTreeAutoscaling() {
    return enableInTreeAutoscaling;
  }


  public void setEnableInTreeAutoscaling(Boolean enableInTreeAutoscaling) {
    this.enableInTreeAutoscaling = enableInTreeAutoscaling;
  }


  public V1alpha1RayServiceSpecRayClusterConfig headGroupSpec(V1alpha1RayServiceSpecRayClusterConfigHeadGroupSpec headGroupSpec) {
    
    this.headGroupSpec = headGroupSpec;
    return this;
  }

   /**
   * Get headGroupSpec
   * @return headGroupSpec
  **/
  @jakarta.annotation.Nonnull
  public V1alpha1RayServiceSpecRayClusterConfigHeadGroupSpec getHeadGroupSpec() {
    return headGroupSpec;
  }


  public void setHeadGroupSpec(V1alpha1RayServiceSpecRayClusterConfigHeadGroupSpec headGroupSpec) {
    this.headGroupSpec = headGroupSpec;
  }


  public V1alpha1RayServiceSpecRayClusterConfig headServiceAnnotations(Map<String, String> headServiceAnnotations) {
    
    this.headServiceAnnotations = headServiceAnnotations;
    return this;
  }

  public V1alpha1RayServiceSpecRayClusterConfig putHeadServiceAnnotationsItem(String key, String headServiceAnnotationsItem) {
    if (this.headServiceAnnotations == null) {
      this.headServiceAnnotations = new HashMap<>();
    }
    this.headServiceAnnotations.put(key, headServiceAnnotationsItem);
    return this;
  }

   /**
   * Get headServiceAnnotations
   * @return headServiceAnnotations
  **/
  @jakarta.annotation.Nullable
  public Map<String, String> getHeadServiceAnnotations() {
    return headServiceAnnotations;
  }


  public void setHeadServiceAnnotations(Map<String, String> headServiceAnnotations) {
    this.headServiceAnnotations = headServiceAnnotations;
  }


  public V1alpha1RayServiceSpecRayClusterConfig rayVersion(String rayVersion) {
    
    this.rayVersion = rayVersion;
    return this;
  }

   /**
   * Get rayVersion
   * @return rayVersion
  **/
  @jakarta.annotation.Nullable
  public String getRayVersion() {
    return rayVersion;
  }


  public void setRayVersion(String rayVersion) {
    this.rayVersion = rayVersion;
  }


  public V1alpha1RayServiceSpecRayClusterConfig suspend(Boolean suspend) {
    
    this.suspend = suspend;
    return this;
  }

   /**
   * Get suspend
   * @return suspend
  **/
  @jakarta.annotation.Nullable
  public Boolean getSuspend() {
    return suspend;
  }


  public void setSuspend(Boolean suspend) {
    this.suspend = suspend;
  }


  public V1alpha1RayServiceSpecRayClusterConfig workerGroupSpecs(List<V1alpha1RayServiceSpecRayClusterConfigWorkerGroupSpecsInner> workerGroupSpecs) {
    
    this.workerGroupSpecs = workerGroupSpecs;
    return this;
  }

  public V1alpha1RayServiceSpecRayClusterConfig addWorkerGroupSpecsItem(V1alpha1RayServiceSpecRayClusterConfigWorkerGroupSpecsInner workerGroupSpecsItem) {
    if (this.workerGroupSpecs == null) {
      this.workerGroupSpecs = new ArrayList<>();
    }
    this.workerGroupSpecs.add(workerGroupSpecsItem);
    return this;
  }

   /**
   * Get workerGroupSpecs
   * @return workerGroupSpecs
  **/
  @jakarta.annotation.Nullable
  public List<V1alpha1RayServiceSpecRayClusterConfigWorkerGroupSpecsInner> getWorkerGroupSpecs() {
    return workerGroupSpecs;
  }


  public void setWorkerGroupSpecs(List<V1alpha1RayServiceSpecRayClusterConfigWorkerGroupSpecsInner> workerGroupSpecs) {
    this.workerGroupSpecs = workerGroupSpecs;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha1RayServiceSpecRayClusterConfig v1alpha1RayServiceSpecRayClusterConfig = (V1alpha1RayServiceSpecRayClusterConfig) o;
    return Objects.equals(this.autoscalerOptions, v1alpha1RayServiceSpecRayClusterConfig.autoscalerOptions) &&
        Objects.equals(this.enableInTreeAutoscaling, v1alpha1RayServiceSpecRayClusterConfig.enableInTreeAutoscaling) &&
        Objects.equals(this.headGroupSpec, v1alpha1RayServiceSpecRayClusterConfig.headGroupSpec) &&
        Objects.equals(this.headServiceAnnotations, v1alpha1RayServiceSpecRayClusterConfig.headServiceAnnotations) &&
        Objects.equals(this.rayVersion, v1alpha1RayServiceSpecRayClusterConfig.rayVersion) &&
        Objects.equals(this.suspend, v1alpha1RayServiceSpecRayClusterConfig.suspend) &&
        Objects.equals(this.workerGroupSpecs, v1alpha1RayServiceSpecRayClusterConfig.workerGroupSpecs);
  }

  @Override
  public int hashCode() {
    return Objects.hash(autoscalerOptions, enableInTreeAutoscaling, headGroupSpec, headServiceAnnotations, rayVersion, suspend, workerGroupSpecs);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha1RayServiceSpecRayClusterConfig {\n");
    sb.append("    autoscalerOptions: ").append(toIndentedString(autoscalerOptions)).append("\n");
    sb.append("    enableInTreeAutoscaling: ").append(toIndentedString(enableInTreeAutoscaling)).append("\n");
    sb.append("    headGroupSpec: ").append(toIndentedString(headGroupSpec)).append("\n");
    sb.append("    headServiceAnnotations: ").append(toIndentedString(headServiceAnnotations)).append("\n");
    sb.append("    rayVersion: ").append(toIndentedString(rayVersion)).append("\n");
    sb.append("    suspend: ").append(toIndentedString(suspend)).append("\n");
    sb.append("    workerGroupSpecs: ").append(toIndentedString(workerGroupSpecs)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("autoscalerOptions");
    openapiFields.add("enableInTreeAutoscaling");
    openapiFields.add("headGroupSpec");
    openapiFields.add("headServiceAnnotations");
    openapiFields.add("rayVersion");
    openapiFields.add("suspend");
    openapiFields.add("workerGroupSpecs");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("headGroupSpec");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to V1alpha1RayServiceSpecRayClusterConfig
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!V1alpha1RayServiceSpecRayClusterConfig.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in V1alpha1RayServiceSpecRayClusterConfig is not found in the empty JSON string", V1alpha1RayServiceSpecRayClusterConfig.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!V1alpha1RayServiceSpecRayClusterConfig.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `V1alpha1RayServiceSpecRayClusterConfig` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : V1alpha1RayServiceSpecRayClusterConfig.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      // validate the optional field `autoscalerOptions`
      if (jsonObj.get("autoscalerOptions") != null && !jsonObj.get("autoscalerOptions").isJsonNull()) {
        V1alpha1RayServiceSpecRayClusterConfigAutoscalerOptions.validateJsonObject(jsonObj.getAsJsonObject("autoscalerOptions"));
      }
      // validate the required field `headGroupSpec`
      V1alpha1RayServiceSpecRayClusterConfigHeadGroupSpec.validateJsonObject(jsonObj.getAsJsonObject("headGroupSpec"));
      if ((jsonObj.get("rayVersion") != null && !jsonObj.get("rayVersion").isJsonNull()) && !jsonObj.get("rayVersion").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `rayVersion` to be a primitive type in the JSON string but got `%s`", jsonObj.get("rayVersion").toString()));
      }
      if (jsonObj.get("workerGroupSpecs") != null && !jsonObj.get("workerGroupSpecs").isJsonNull()) {
        JsonArray jsonArrayworkerGroupSpecs = jsonObj.getAsJsonArray("workerGroupSpecs");
        if (jsonArrayworkerGroupSpecs != null) {
          // ensure the json data is an array
          if (!jsonObj.get("workerGroupSpecs").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `workerGroupSpecs` to be an array in the JSON string but got `%s`", jsonObj.get("workerGroupSpecs").toString()));
          }

          // validate the optional field `workerGroupSpecs` (array)
          for (int i = 0; i < jsonArrayworkerGroupSpecs.size(); i++) {
            V1alpha1RayServiceSpecRayClusterConfigWorkerGroupSpecsInner.validateJsonObject(jsonArrayworkerGroupSpecs.get(i).getAsJsonObject());
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!V1alpha1RayServiceSpecRayClusterConfig.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'V1alpha1RayServiceSpecRayClusterConfig' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<V1alpha1RayServiceSpecRayClusterConfig> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(V1alpha1RayServiceSpecRayClusterConfig.class));

       return (TypeAdapter<T>) new TypeAdapter<V1alpha1RayServiceSpecRayClusterConfig>() {
           @Override
           public void write(JsonWriter out, V1alpha1RayServiceSpecRayClusterConfig value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public V1alpha1RayServiceSpecRayClusterConfig read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of V1alpha1RayServiceSpecRayClusterConfig given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of V1alpha1RayServiceSpecRayClusterConfig
  * @throws IOException if the JSON string is invalid with respect to V1alpha1RayServiceSpecRayClusterConfig
  */
  public static V1alpha1RayServiceSpecRayClusterConfig fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, V1alpha1RayServiceSpecRayClusterConfig.class);
  }

 /**
  * Convert an instance of V1alpha1RayServiceSpecRayClusterConfig to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

