/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.25.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package net.statemesh.k8s.crd.rayservice.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;
import net.statemesh.k8s.crd.rayservice.models.V1alpha1RayServiceStatusActiveServiceStatusApplicationStatusesValue;
import net.statemesh.k8s.crd.rayservice.models.V1alpha1RayServiceStatusActiveServiceStatusRayClusterStatus;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import io.kubernetes.client.openapi.JSON;

/**
 * V1alpha1RayServiceStatusActiveServiceStatus
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-09-11T07:02:38.554963Z[Etc/UTC]")
public class V1alpha1RayServiceStatusActiveServiceStatus {
  public static final String SERIALIZED_NAME_APPLICATION_STATUSES = "applicationStatuses";
  @SerializedName(SERIALIZED_NAME_APPLICATION_STATUSES)
  private Map<String, V1alpha1RayServiceStatusActiveServiceStatusApplicationStatusesValue> applicationStatuses = new HashMap<>();

  public static final String SERIALIZED_NAME_RAY_CLUSTER_NAME = "rayClusterName";
  @SerializedName(SERIALIZED_NAME_RAY_CLUSTER_NAME)
  private String rayClusterName;

  public static final String SERIALIZED_NAME_RAY_CLUSTER_STATUS = "rayClusterStatus";
  @SerializedName(SERIALIZED_NAME_RAY_CLUSTER_STATUS)
  private V1alpha1RayServiceStatusActiveServiceStatusRayClusterStatus rayClusterStatus;

  public V1alpha1RayServiceStatusActiveServiceStatus() {
  }

  public V1alpha1RayServiceStatusActiveServiceStatus applicationStatuses(Map<String, V1alpha1RayServiceStatusActiveServiceStatusApplicationStatusesValue> applicationStatuses) {
    
    this.applicationStatuses = applicationStatuses;
    return this;
  }

  public V1alpha1RayServiceStatusActiveServiceStatus putApplicationStatusesItem(String key, V1alpha1RayServiceStatusActiveServiceStatusApplicationStatusesValue applicationStatusesItem) {
    if (this.applicationStatuses == null) {
      this.applicationStatuses = new HashMap<>();
    }
    this.applicationStatuses.put(key, applicationStatusesItem);
    return this;
  }

   /**
   * Get applicationStatuses
   * @return applicationStatuses
  **/
  @jakarta.annotation.Nullable
  public Map<String, V1alpha1RayServiceStatusActiveServiceStatusApplicationStatusesValue> getApplicationStatuses() {
    return applicationStatuses;
  }


  public void setApplicationStatuses(Map<String, V1alpha1RayServiceStatusActiveServiceStatusApplicationStatusesValue> applicationStatuses) {
    this.applicationStatuses = applicationStatuses;
  }


  public V1alpha1RayServiceStatusActiveServiceStatus rayClusterName(String rayClusterName) {
    
    this.rayClusterName = rayClusterName;
    return this;
  }

   /**
   * Get rayClusterName
   * @return rayClusterName
  **/
  @jakarta.annotation.Nullable
  public String getRayClusterName() {
    return rayClusterName;
  }


  public void setRayClusterName(String rayClusterName) {
    this.rayClusterName = rayClusterName;
  }


  public V1alpha1RayServiceStatusActiveServiceStatus rayClusterStatus(V1alpha1RayServiceStatusActiveServiceStatusRayClusterStatus rayClusterStatus) {
    
    this.rayClusterStatus = rayClusterStatus;
    return this;
  }

   /**
   * Get rayClusterStatus
   * @return rayClusterStatus
  **/
  @jakarta.annotation.Nullable
  public V1alpha1RayServiceStatusActiveServiceStatusRayClusterStatus getRayClusterStatus() {
    return rayClusterStatus;
  }


  public void setRayClusterStatus(V1alpha1RayServiceStatusActiveServiceStatusRayClusterStatus rayClusterStatus) {
    this.rayClusterStatus = rayClusterStatus;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha1RayServiceStatusActiveServiceStatus v1alpha1RayServiceStatusActiveServiceStatus = (V1alpha1RayServiceStatusActiveServiceStatus) o;
    return Objects.equals(this.applicationStatuses, v1alpha1RayServiceStatusActiveServiceStatus.applicationStatuses) &&
        Objects.equals(this.rayClusterName, v1alpha1RayServiceStatusActiveServiceStatus.rayClusterName) &&
        Objects.equals(this.rayClusterStatus, v1alpha1RayServiceStatusActiveServiceStatus.rayClusterStatus);
  }

  @Override
  public int hashCode() {
    return Objects.hash(applicationStatuses, rayClusterName, rayClusterStatus);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha1RayServiceStatusActiveServiceStatus {\n");
    sb.append("    applicationStatuses: ").append(toIndentedString(applicationStatuses)).append("\n");
    sb.append("    rayClusterName: ").append(toIndentedString(rayClusterName)).append("\n");
    sb.append("    rayClusterStatus: ").append(toIndentedString(rayClusterStatus)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("applicationStatuses");
    openapiFields.add("rayClusterName");
    openapiFields.add("rayClusterStatus");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to V1alpha1RayServiceStatusActiveServiceStatus
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!V1alpha1RayServiceStatusActiveServiceStatus.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in V1alpha1RayServiceStatusActiveServiceStatus is not found in the empty JSON string", V1alpha1RayServiceStatusActiveServiceStatus.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!V1alpha1RayServiceStatusActiveServiceStatus.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `V1alpha1RayServiceStatusActiveServiceStatus` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }
      if ((jsonObj.get("rayClusterName") != null && !jsonObj.get("rayClusterName").isJsonNull()) && !jsonObj.get("rayClusterName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `rayClusterName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("rayClusterName").toString()));
      }
      // validate the optional field `rayClusterStatus`
      if (jsonObj.get("rayClusterStatus") != null && !jsonObj.get("rayClusterStatus").isJsonNull()) {
        V1alpha1RayServiceStatusActiveServiceStatusRayClusterStatus.validateJsonObject(jsonObj.getAsJsonObject("rayClusterStatus"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!V1alpha1RayServiceStatusActiveServiceStatus.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'V1alpha1RayServiceStatusActiveServiceStatus' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<V1alpha1RayServiceStatusActiveServiceStatus> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(V1alpha1RayServiceStatusActiveServiceStatus.class));

       return (TypeAdapter<T>) new TypeAdapter<V1alpha1RayServiceStatusActiveServiceStatus>() {
           @Override
           public void write(JsonWriter out, V1alpha1RayServiceStatusActiveServiceStatus value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public V1alpha1RayServiceStatusActiveServiceStatus read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of V1alpha1RayServiceStatusActiveServiceStatus given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of V1alpha1RayServiceStatusActiveServiceStatus
  * @throws IOException if the JSON string is invalid with respect to V1alpha1RayServiceStatusActiveServiceStatus
  */
  public static V1alpha1RayServiceStatusActiveServiceStatus fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, V1alpha1RayServiceStatusActiveServiceStatus.class);
  }

 /**
  * Convert an instance of V1alpha1RayServiceStatusActiveServiceStatus to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

