/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.25.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package net.statemesh.k8s.crd.rayservice.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import io.kubernetes.client.openapi.JSON;

/**
 * V1RayServiceSpecRayClusterConfigHeadGroupSpecTemplateSpecResourceClaimsInner
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-09-11T07:02:38.554963Z[Etc/UTC]")
public class V1RayServiceSpecRayClusterConfigHeadGroupSpecTemplateSpecResourceClaimsInner {
  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_RESOURCE_CLAIM_NAME = "resourceClaimName";
  @SerializedName(SERIALIZED_NAME_RESOURCE_CLAIM_NAME)
  private String resourceClaimName;

  public static final String SERIALIZED_NAME_RESOURCE_CLAIM_TEMPLATE_NAME = "resourceClaimTemplateName";
  @SerializedName(SERIALIZED_NAME_RESOURCE_CLAIM_TEMPLATE_NAME)
  private String resourceClaimTemplateName;

  public V1RayServiceSpecRayClusterConfigHeadGroupSpecTemplateSpecResourceClaimsInner() {
  }

  public V1RayServiceSpecRayClusterConfigHeadGroupSpecTemplateSpecResourceClaimsInner name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @jakarta.annotation.Nonnull
  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public V1RayServiceSpecRayClusterConfigHeadGroupSpecTemplateSpecResourceClaimsInner resourceClaimName(String resourceClaimName) {
    
    this.resourceClaimName = resourceClaimName;
    return this;
  }

   /**
   * Get resourceClaimName
   * @return resourceClaimName
  **/
  @jakarta.annotation.Nullable
  public String getResourceClaimName() {
    return resourceClaimName;
  }


  public void setResourceClaimName(String resourceClaimName) {
    this.resourceClaimName = resourceClaimName;
  }


  public V1RayServiceSpecRayClusterConfigHeadGroupSpecTemplateSpecResourceClaimsInner resourceClaimTemplateName(String resourceClaimTemplateName) {
    
    this.resourceClaimTemplateName = resourceClaimTemplateName;
    return this;
  }

   /**
   * Get resourceClaimTemplateName
   * @return resourceClaimTemplateName
  **/
  @jakarta.annotation.Nullable
  public String getResourceClaimTemplateName() {
    return resourceClaimTemplateName;
  }


  public void setResourceClaimTemplateName(String resourceClaimTemplateName) {
    this.resourceClaimTemplateName = resourceClaimTemplateName;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1RayServiceSpecRayClusterConfigHeadGroupSpecTemplateSpecResourceClaimsInner v1RayServiceSpecRayClusterConfigHeadGroupSpecTemplateSpecResourceClaimsInner = (V1RayServiceSpecRayClusterConfigHeadGroupSpecTemplateSpecResourceClaimsInner) o;
    return Objects.equals(this.name, v1RayServiceSpecRayClusterConfigHeadGroupSpecTemplateSpecResourceClaimsInner.name) &&
        Objects.equals(this.resourceClaimName, v1RayServiceSpecRayClusterConfigHeadGroupSpecTemplateSpecResourceClaimsInner.resourceClaimName) &&
        Objects.equals(this.resourceClaimTemplateName, v1RayServiceSpecRayClusterConfigHeadGroupSpecTemplateSpecResourceClaimsInner.resourceClaimTemplateName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, resourceClaimName, resourceClaimTemplateName);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1RayServiceSpecRayClusterConfigHeadGroupSpecTemplateSpecResourceClaimsInner {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    resourceClaimName: ").append(toIndentedString(resourceClaimName)).append("\n");
    sb.append("    resourceClaimTemplateName: ").append(toIndentedString(resourceClaimTemplateName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("name");
    openapiFields.add("resourceClaimName");
    openapiFields.add("resourceClaimTemplateName");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("name");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to V1RayServiceSpecRayClusterConfigHeadGroupSpecTemplateSpecResourceClaimsInner
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!V1RayServiceSpecRayClusterConfigHeadGroupSpecTemplateSpecResourceClaimsInner.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in V1RayServiceSpecRayClusterConfigHeadGroupSpecTemplateSpecResourceClaimsInner is not found in the empty JSON string", V1RayServiceSpecRayClusterConfigHeadGroupSpecTemplateSpecResourceClaimsInner.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!V1RayServiceSpecRayClusterConfigHeadGroupSpecTemplateSpecResourceClaimsInner.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `V1RayServiceSpecRayClusterConfigHeadGroupSpecTemplateSpecResourceClaimsInner` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : V1RayServiceSpecRayClusterConfigHeadGroupSpecTemplateSpecResourceClaimsInner.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      if (!jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      if ((jsonObj.get("resourceClaimName") != null && !jsonObj.get("resourceClaimName").isJsonNull()) && !jsonObj.get("resourceClaimName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `resourceClaimName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("resourceClaimName").toString()));
      }
      if ((jsonObj.get("resourceClaimTemplateName") != null && !jsonObj.get("resourceClaimTemplateName").isJsonNull()) && !jsonObj.get("resourceClaimTemplateName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `resourceClaimTemplateName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("resourceClaimTemplateName").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!V1RayServiceSpecRayClusterConfigHeadGroupSpecTemplateSpecResourceClaimsInner.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'V1RayServiceSpecRayClusterConfigHeadGroupSpecTemplateSpecResourceClaimsInner' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<V1RayServiceSpecRayClusterConfigHeadGroupSpecTemplateSpecResourceClaimsInner> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(V1RayServiceSpecRayClusterConfigHeadGroupSpecTemplateSpecResourceClaimsInner.class));

       return (TypeAdapter<T>) new TypeAdapter<V1RayServiceSpecRayClusterConfigHeadGroupSpecTemplateSpecResourceClaimsInner>() {
           @Override
           public void write(JsonWriter out, V1RayServiceSpecRayClusterConfigHeadGroupSpecTemplateSpecResourceClaimsInner value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public V1RayServiceSpecRayClusterConfigHeadGroupSpecTemplateSpecResourceClaimsInner read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of V1RayServiceSpecRayClusterConfigHeadGroupSpecTemplateSpecResourceClaimsInner given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of V1RayServiceSpecRayClusterConfigHeadGroupSpecTemplateSpecResourceClaimsInner
  * @throws IOException if the JSON string is invalid with respect to V1RayServiceSpecRayClusterConfigHeadGroupSpecTemplateSpecResourceClaimsInner
  */
  public static V1RayServiceSpecRayClusterConfigHeadGroupSpecTemplateSpecResourceClaimsInner fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, V1RayServiceSpecRayClusterConfigHeadGroupSpecTemplateSpecResourceClaimsInner.class);
  }

 /**
  * Convert an instance of V1RayServiceSpecRayClusterConfigHeadGroupSpecTemplateSpecResourceClaimsInner to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

