/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.25.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package net.statemesh.k8s.crd.rayservice.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import net.statemesh.k8s.crd.rayservice.models.V1RayServiceSpecRayClusterConfigAutoscalerOptionsResourcesClaimsInner;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import io.kubernetes.client.openapi.JSON;

/**
 * V1RayServiceSpecRayClusterConfigAutoscalerOptionsResources
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-09-11T07:02:38.554963Z[Etc/UTC]")
public class V1RayServiceSpecRayClusterConfigAutoscalerOptionsResources {
  public static final String SERIALIZED_NAME_CLAIMS = "claims";
  @SerializedName(SERIALIZED_NAME_CLAIMS)
  private List<V1RayServiceSpecRayClusterConfigAutoscalerOptionsResourcesClaimsInner> claims;

  public static final String SERIALIZED_NAME_LIMITS = "limits";
  @SerializedName(SERIALIZED_NAME_LIMITS)
  private Map<String, Object> limits = new HashMap<>();

  public static final String SERIALIZED_NAME_REQUESTS = "requests";
  @SerializedName(SERIALIZED_NAME_REQUESTS)
  private Map<String, Object> requests = new HashMap<>();

  public V1RayServiceSpecRayClusterConfigAutoscalerOptionsResources() {
  }

  public V1RayServiceSpecRayClusterConfigAutoscalerOptionsResources claims(List<V1RayServiceSpecRayClusterConfigAutoscalerOptionsResourcesClaimsInner> claims) {
    
    this.claims = claims;
    return this;
  }

  public V1RayServiceSpecRayClusterConfigAutoscalerOptionsResources addClaimsItem(V1RayServiceSpecRayClusterConfigAutoscalerOptionsResourcesClaimsInner claimsItem) {
    if (this.claims == null) {
      this.claims = new ArrayList<>();
    }
    this.claims.add(claimsItem);
    return this;
  }

   /**
   * Get claims
   * @return claims
  **/
  @jakarta.annotation.Nullable
  public List<V1RayServiceSpecRayClusterConfigAutoscalerOptionsResourcesClaimsInner> getClaims() {
    return claims;
  }


  public void setClaims(List<V1RayServiceSpecRayClusterConfigAutoscalerOptionsResourcesClaimsInner> claims) {
    this.claims = claims;
  }


  public V1RayServiceSpecRayClusterConfigAutoscalerOptionsResources limits(Map<String, Object> limits) {
    
    this.limits = limits;
    return this;
  }

  public V1RayServiceSpecRayClusterConfigAutoscalerOptionsResources putLimitsItem(String key, Object limitsItem) {
    if (this.limits == null) {
      this.limits = new HashMap<>();
    }
    this.limits.put(key, limitsItem);
    return this;
  }

   /**
   * Get limits
   * @return limits
  **/
  @jakarta.annotation.Nullable
  public Map<String, Object> getLimits() {
    return limits;
  }


  public void setLimits(Map<String, Object> limits) {
    this.limits = limits;
  }


  public V1RayServiceSpecRayClusterConfigAutoscalerOptionsResources requests(Map<String, Object> requests) {
    
    this.requests = requests;
    return this;
  }

  public V1RayServiceSpecRayClusterConfigAutoscalerOptionsResources putRequestsItem(String key, Object requestsItem) {
    if (this.requests == null) {
      this.requests = new HashMap<>();
    }
    this.requests.put(key, requestsItem);
    return this;
  }

   /**
   * Get requests
   * @return requests
  **/
  @jakarta.annotation.Nullable
  public Map<String, Object> getRequests() {
    return requests;
  }


  public void setRequests(Map<String, Object> requests) {
    this.requests = requests;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1RayServiceSpecRayClusterConfigAutoscalerOptionsResources v1RayServiceSpecRayClusterConfigAutoscalerOptionsResources = (V1RayServiceSpecRayClusterConfigAutoscalerOptionsResources) o;
    return Objects.equals(this.claims, v1RayServiceSpecRayClusterConfigAutoscalerOptionsResources.claims) &&
        Objects.equals(this.limits, v1RayServiceSpecRayClusterConfigAutoscalerOptionsResources.limits) &&
        Objects.equals(this.requests, v1RayServiceSpecRayClusterConfigAutoscalerOptionsResources.requests);
  }

  @Override
  public int hashCode() {
    return Objects.hash(claims, limits, requests);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1RayServiceSpecRayClusterConfigAutoscalerOptionsResources {\n");
    sb.append("    claims: ").append(toIndentedString(claims)).append("\n");
    sb.append("    limits: ").append(toIndentedString(limits)).append("\n");
    sb.append("    requests: ").append(toIndentedString(requests)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("claims");
    openapiFields.add("limits");
    openapiFields.add("requests");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to V1RayServiceSpecRayClusterConfigAutoscalerOptionsResources
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!V1RayServiceSpecRayClusterConfigAutoscalerOptionsResources.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in V1RayServiceSpecRayClusterConfigAutoscalerOptionsResources is not found in the empty JSON string", V1RayServiceSpecRayClusterConfigAutoscalerOptionsResources.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!V1RayServiceSpecRayClusterConfigAutoscalerOptionsResources.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `V1RayServiceSpecRayClusterConfigAutoscalerOptionsResources` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }
      if (jsonObj.get("claims") != null && !jsonObj.get("claims").isJsonNull()) {
        JsonArray jsonArrayclaims = jsonObj.getAsJsonArray("claims");
        if (jsonArrayclaims != null) {
          // ensure the json data is an array
          if (!jsonObj.get("claims").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `claims` to be an array in the JSON string but got `%s`", jsonObj.get("claims").toString()));
          }

          // validate the optional field `claims` (array)
          for (int i = 0; i < jsonArrayclaims.size(); i++) {
            V1RayServiceSpecRayClusterConfigAutoscalerOptionsResourcesClaimsInner.validateJsonObject(jsonArrayclaims.get(i).getAsJsonObject());
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!V1RayServiceSpecRayClusterConfigAutoscalerOptionsResources.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'V1RayServiceSpecRayClusterConfigAutoscalerOptionsResources' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<V1RayServiceSpecRayClusterConfigAutoscalerOptionsResources> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(V1RayServiceSpecRayClusterConfigAutoscalerOptionsResources.class));

       return (TypeAdapter<T>) new TypeAdapter<V1RayServiceSpecRayClusterConfigAutoscalerOptionsResources>() {
           @Override
           public void write(JsonWriter out, V1RayServiceSpecRayClusterConfigAutoscalerOptionsResources value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public V1RayServiceSpecRayClusterConfigAutoscalerOptionsResources read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of V1RayServiceSpecRayClusterConfigAutoscalerOptionsResources given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of V1RayServiceSpecRayClusterConfigAutoscalerOptionsResources
  * @throws IOException if the JSON string is invalid with respect to V1RayServiceSpecRayClusterConfigAutoscalerOptionsResources
  */
  public static V1RayServiceSpecRayClusterConfigAutoscalerOptionsResources fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, V1RayServiceSpecRayClusterConfigAutoscalerOptionsResources.class);
  }

 /**
  * Convert an instance of V1RayServiceSpecRayClusterConfigAutoscalerOptionsResources to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

