/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.25.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package net.statemesh.k8s.crd.rayservice.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import io.kubernetes.client.openapi.JSON;

/**
 * V1RayServiceSpecRayClusterConfigHeadGroupSpecTemplateSpecVolumesInnerPersistentVolumeClaim
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-09-11T07:02:38.554963Z[Etc/UTC]")
public class V1RayServiceSpecRayClusterConfigHeadGroupSpecTemplateSpecVolumesInnerPersistentVolumeClaim {
  public static final String SERIALIZED_NAME_CLAIM_NAME = "claimName";
  @SerializedName(SERIALIZED_NAME_CLAIM_NAME)
  private String claimName;

  public static final String SERIALIZED_NAME_READ_ONLY = "readOnly";
  @SerializedName(SERIALIZED_NAME_READ_ONLY)
  private Boolean readOnly;

  public V1RayServiceSpecRayClusterConfigHeadGroupSpecTemplateSpecVolumesInnerPersistentVolumeClaim() {
  }

  public V1RayServiceSpecRayClusterConfigHeadGroupSpecTemplateSpecVolumesInnerPersistentVolumeClaim claimName(String claimName) {
    
    this.claimName = claimName;
    return this;
  }

   /**
   * Get claimName
   * @return claimName
  **/
  @jakarta.annotation.Nonnull
  public String getClaimName() {
    return claimName;
  }


  public void setClaimName(String claimName) {
    this.claimName = claimName;
  }


  public V1RayServiceSpecRayClusterConfigHeadGroupSpecTemplateSpecVolumesInnerPersistentVolumeClaim readOnly(Boolean readOnly) {
    
    this.readOnly = readOnly;
    return this;
  }

   /**
   * Get readOnly
   * @return readOnly
  **/
  @jakarta.annotation.Nullable
  public Boolean getReadOnly() {
    return readOnly;
  }


  public void setReadOnly(Boolean readOnly) {
    this.readOnly = readOnly;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1RayServiceSpecRayClusterConfigHeadGroupSpecTemplateSpecVolumesInnerPersistentVolumeClaim v1RayServiceSpecRayClusterConfigHeadGroupSpecTemplateSpecVolumesInnerPersistentVolumeClaim = (V1RayServiceSpecRayClusterConfigHeadGroupSpecTemplateSpecVolumesInnerPersistentVolumeClaim) o;
    return Objects.equals(this.claimName, v1RayServiceSpecRayClusterConfigHeadGroupSpecTemplateSpecVolumesInnerPersistentVolumeClaim.claimName) &&
        Objects.equals(this.readOnly, v1RayServiceSpecRayClusterConfigHeadGroupSpecTemplateSpecVolumesInnerPersistentVolumeClaim.readOnly);
  }

  @Override
  public int hashCode() {
    return Objects.hash(claimName, readOnly);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1RayServiceSpecRayClusterConfigHeadGroupSpecTemplateSpecVolumesInnerPersistentVolumeClaim {\n");
    sb.append("    claimName: ").append(toIndentedString(claimName)).append("\n");
    sb.append("    readOnly: ").append(toIndentedString(readOnly)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("claimName");
    openapiFields.add("readOnly");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("claimName");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to V1RayServiceSpecRayClusterConfigHeadGroupSpecTemplateSpecVolumesInnerPersistentVolumeClaim
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!V1RayServiceSpecRayClusterConfigHeadGroupSpecTemplateSpecVolumesInnerPersistentVolumeClaim.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in V1RayServiceSpecRayClusterConfigHeadGroupSpecTemplateSpecVolumesInnerPersistentVolumeClaim is not found in the empty JSON string", V1RayServiceSpecRayClusterConfigHeadGroupSpecTemplateSpecVolumesInnerPersistentVolumeClaim.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!V1RayServiceSpecRayClusterConfigHeadGroupSpecTemplateSpecVolumesInnerPersistentVolumeClaim.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `V1RayServiceSpecRayClusterConfigHeadGroupSpecTemplateSpecVolumesInnerPersistentVolumeClaim` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : V1RayServiceSpecRayClusterConfigHeadGroupSpecTemplateSpecVolumesInnerPersistentVolumeClaim.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      if (!jsonObj.get("claimName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `claimName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("claimName").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!V1RayServiceSpecRayClusterConfigHeadGroupSpecTemplateSpecVolumesInnerPersistentVolumeClaim.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'V1RayServiceSpecRayClusterConfigHeadGroupSpecTemplateSpecVolumesInnerPersistentVolumeClaim' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<V1RayServiceSpecRayClusterConfigHeadGroupSpecTemplateSpecVolumesInnerPersistentVolumeClaim> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(V1RayServiceSpecRayClusterConfigHeadGroupSpecTemplateSpecVolumesInnerPersistentVolumeClaim.class));

       return (TypeAdapter<T>) new TypeAdapter<V1RayServiceSpecRayClusterConfigHeadGroupSpecTemplateSpecVolumesInnerPersistentVolumeClaim>() {
           @Override
           public void write(JsonWriter out, V1RayServiceSpecRayClusterConfigHeadGroupSpecTemplateSpecVolumesInnerPersistentVolumeClaim value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public V1RayServiceSpecRayClusterConfigHeadGroupSpecTemplateSpecVolumesInnerPersistentVolumeClaim read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of V1RayServiceSpecRayClusterConfigHeadGroupSpecTemplateSpecVolumesInnerPersistentVolumeClaim given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of V1RayServiceSpecRayClusterConfigHeadGroupSpecTemplateSpecVolumesInnerPersistentVolumeClaim
  * @throws IOException if the JSON string is invalid with respect to V1RayServiceSpecRayClusterConfigHeadGroupSpecTemplateSpecVolumesInnerPersistentVolumeClaim
  */
  public static V1RayServiceSpecRayClusterConfigHeadGroupSpecTemplateSpecVolumesInnerPersistentVolumeClaim fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, V1RayServiceSpecRayClusterConfigHeadGroupSpecTemplateSpecVolumesInnerPersistentVolumeClaim.class);
  }

 /**
  * Convert an instance of V1RayServiceSpecRayClusterConfigHeadGroupSpecTemplateSpecVolumesInnerPersistentVolumeClaim to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

