/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.25.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package net.statemesh.k8s.crd.rayservice.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import net.statemesh.k8s.crd.rayservice.models.V1RayServiceSpecRayClusterConfigHeadGroupSpecHeadServiceMetadata;
import net.statemesh.k8s.crd.rayservice.models.V1RayServiceSpecRayClusterConfigHeadGroupSpecTemplateSpecVolumesInnerEphemeralVolumeClaimTemplateSpec;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import io.kubernetes.client.openapi.JSON;

/**
 * V1RayServiceSpecRayClusterConfigHeadGroupSpecTemplateSpecVolumesInnerEphemeralVolumeClaimTemplate
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-09-11T07:02:38.554963Z[Etc/UTC]")
public class V1RayServiceSpecRayClusterConfigHeadGroupSpecTemplateSpecVolumesInnerEphemeralVolumeClaimTemplate {
  public static final String SERIALIZED_NAME_METADATA = "metadata";
  @SerializedName(SERIALIZED_NAME_METADATA)
  private V1RayServiceSpecRayClusterConfigHeadGroupSpecHeadServiceMetadata metadata;

  public static final String SERIALIZED_NAME_SPEC = "spec";
  @SerializedName(SERIALIZED_NAME_SPEC)
  private V1RayServiceSpecRayClusterConfigHeadGroupSpecTemplateSpecVolumesInnerEphemeralVolumeClaimTemplateSpec spec;

  public V1RayServiceSpecRayClusterConfigHeadGroupSpecTemplateSpecVolumesInnerEphemeralVolumeClaimTemplate() {
  }

  public V1RayServiceSpecRayClusterConfigHeadGroupSpecTemplateSpecVolumesInnerEphemeralVolumeClaimTemplate metadata(V1RayServiceSpecRayClusterConfigHeadGroupSpecHeadServiceMetadata metadata) {
    
    this.metadata = metadata;
    return this;
  }

   /**
   * Get metadata
   * @return metadata
  **/
  @jakarta.annotation.Nullable
  public V1RayServiceSpecRayClusterConfigHeadGroupSpecHeadServiceMetadata getMetadata() {
    return metadata;
  }


  public void setMetadata(V1RayServiceSpecRayClusterConfigHeadGroupSpecHeadServiceMetadata metadata) {
    this.metadata = metadata;
  }


  public V1RayServiceSpecRayClusterConfigHeadGroupSpecTemplateSpecVolumesInnerEphemeralVolumeClaimTemplate spec(V1RayServiceSpecRayClusterConfigHeadGroupSpecTemplateSpecVolumesInnerEphemeralVolumeClaimTemplateSpec spec) {
    
    this.spec = spec;
    return this;
  }

   /**
   * Get spec
   * @return spec
  **/
  @jakarta.annotation.Nonnull
  public V1RayServiceSpecRayClusterConfigHeadGroupSpecTemplateSpecVolumesInnerEphemeralVolumeClaimTemplateSpec getSpec() {
    return spec;
  }


  public void setSpec(V1RayServiceSpecRayClusterConfigHeadGroupSpecTemplateSpecVolumesInnerEphemeralVolumeClaimTemplateSpec spec) {
    this.spec = spec;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1RayServiceSpecRayClusterConfigHeadGroupSpecTemplateSpecVolumesInnerEphemeralVolumeClaimTemplate v1RayServiceSpecRayClusterConfigHeadGroupSpecTemplateSpecVolumesInnerEphemeralVolumeClaimTemplate = (V1RayServiceSpecRayClusterConfigHeadGroupSpecTemplateSpecVolumesInnerEphemeralVolumeClaimTemplate) o;
    return Objects.equals(this.metadata, v1RayServiceSpecRayClusterConfigHeadGroupSpecTemplateSpecVolumesInnerEphemeralVolumeClaimTemplate.metadata) &&
        Objects.equals(this.spec, v1RayServiceSpecRayClusterConfigHeadGroupSpecTemplateSpecVolumesInnerEphemeralVolumeClaimTemplate.spec);
  }

  @Override
  public int hashCode() {
    return Objects.hash(metadata, spec);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1RayServiceSpecRayClusterConfigHeadGroupSpecTemplateSpecVolumesInnerEphemeralVolumeClaimTemplate {\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("    spec: ").append(toIndentedString(spec)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("metadata");
    openapiFields.add("spec");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("spec");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to V1RayServiceSpecRayClusterConfigHeadGroupSpecTemplateSpecVolumesInnerEphemeralVolumeClaimTemplate
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!V1RayServiceSpecRayClusterConfigHeadGroupSpecTemplateSpecVolumesInnerEphemeralVolumeClaimTemplate.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in V1RayServiceSpecRayClusterConfigHeadGroupSpecTemplateSpecVolumesInnerEphemeralVolumeClaimTemplate is not found in the empty JSON string", V1RayServiceSpecRayClusterConfigHeadGroupSpecTemplateSpecVolumesInnerEphemeralVolumeClaimTemplate.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!V1RayServiceSpecRayClusterConfigHeadGroupSpecTemplateSpecVolumesInnerEphemeralVolumeClaimTemplate.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `V1RayServiceSpecRayClusterConfigHeadGroupSpecTemplateSpecVolumesInnerEphemeralVolumeClaimTemplate` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : V1RayServiceSpecRayClusterConfigHeadGroupSpecTemplateSpecVolumesInnerEphemeralVolumeClaimTemplate.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      // validate the optional field `metadata`
      if (jsonObj.get("metadata") != null && !jsonObj.get("metadata").isJsonNull()) {
        V1RayServiceSpecRayClusterConfigHeadGroupSpecHeadServiceMetadata.validateJsonObject(jsonObj.getAsJsonObject("metadata"));
      }
      // validate the required field `spec`
      V1RayServiceSpecRayClusterConfigHeadGroupSpecTemplateSpecVolumesInnerEphemeralVolumeClaimTemplateSpec.validateJsonObject(jsonObj.getAsJsonObject("spec"));
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!V1RayServiceSpecRayClusterConfigHeadGroupSpecTemplateSpecVolumesInnerEphemeralVolumeClaimTemplate.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'V1RayServiceSpecRayClusterConfigHeadGroupSpecTemplateSpecVolumesInnerEphemeralVolumeClaimTemplate' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<V1RayServiceSpecRayClusterConfigHeadGroupSpecTemplateSpecVolumesInnerEphemeralVolumeClaimTemplate> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(V1RayServiceSpecRayClusterConfigHeadGroupSpecTemplateSpecVolumesInnerEphemeralVolumeClaimTemplate.class));

       return (TypeAdapter<T>) new TypeAdapter<V1RayServiceSpecRayClusterConfigHeadGroupSpecTemplateSpecVolumesInnerEphemeralVolumeClaimTemplate>() {
           @Override
           public void write(JsonWriter out, V1RayServiceSpecRayClusterConfigHeadGroupSpecTemplateSpecVolumesInnerEphemeralVolumeClaimTemplate value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public V1RayServiceSpecRayClusterConfigHeadGroupSpecTemplateSpecVolumesInnerEphemeralVolumeClaimTemplate read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of V1RayServiceSpecRayClusterConfigHeadGroupSpecTemplateSpecVolumesInnerEphemeralVolumeClaimTemplate given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of V1RayServiceSpecRayClusterConfigHeadGroupSpecTemplateSpecVolumesInnerEphemeralVolumeClaimTemplate
  * @throws IOException if the JSON string is invalid with respect to V1RayServiceSpecRayClusterConfigHeadGroupSpecTemplateSpecVolumesInnerEphemeralVolumeClaimTemplate
  */
  public static V1RayServiceSpecRayClusterConfigHeadGroupSpecTemplateSpecVolumesInnerEphemeralVolumeClaimTemplate fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, V1RayServiceSpecRayClusterConfigHeadGroupSpecTemplateSpecVolumesInnerEphemeralVolumeClaimTemplate.class);
  }

 /**
  * Convert an instance of V1RayServiceSpecRayClusterConfigHeadGroupSpecTemplateSpecVolumesInnerEphemeralVolumeClaimTemplate to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

