apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lakefs-shared-pvc
spec:
  accessModes:
    - ReadWriteOncePod
  resources:
    requests:
      storage: 4Ti
  storageClassName: local-path
