export enum Authority {
  ADMIN = 'ROLE_ADMIN',
  USER = 'ROLE_USER',
  TRAINING = 'ROLE_TRAINING',
  EVALUATE = 'ROLE_EVALUATE',
  QUANTIZATION = 'ROLE_QUANTIZATION',
  DEPLOY_APP = 'ROLE_DEPLOY_APP',
  DEPLOY_MODEL = 'ROLE_DEPLOY_MODEL',
  DATAHUB = 'ROLE_DATAHUB',
}
