package net.statemesh.config;

public final class K8Timeouts {
    private static final long BASE_TIMEOUT = 10L;

    public static final long CREATE_LABEL_TIMEOUT_SECONDS = BASE_TIMEOUT;
    public static final long CREATE_NAMESPACE_TIMEOUT_SECONDS = BASE_TIMEOUT;
    public static final long CREATE_ROLE_TIMEOUT_SECONDS = BASE_TIMEOUT;
    public static final long CREATE_SERVICE_ACCOUNT_TIMEOUT_SECONDS = BASE_TIMEOUT;
    public static final long CREATE_POLICY_TIMEOUT_SECONDS = BASE_TIMEOUT;
    public static final long CREATE_SERVICE_TIMEOUT_SECONDS = BASE_TIMEOUT;
    public static final long CREATE_SECRET_TIMEOUT_SECONDS = BASE_TIMEOUT;
    public static final long CREATE_STORAGE_CLASS_TIMEOUT_SECONDS = BASE_TIMEOUT;
    public static final long CREATE_PVC_TIMEOUT_SECONDS = BASE_TIMEOUT;
    public static final long CREATE_DEPLOYMENT_TIMEOUT_SECONDS = 300L;
    public static final long CREATE_INGRESS_TIMEOUT_SECONDS = BASE_TIMEOUT;
    public static final long CREATE_INGRESS_MIDDLEWARE_TIMEOUT_SECONDS = BASE_TIMEOUT;
    public static final long CREATE_FLOW_TIMEOUT_SECONDS = CREATE_NAMESPACE_TIMEOUT_SECONDS
        + CREATE_ROLE_TIMEOUT_SECONDS
        + CREATE_POLICY_TIMEOUT_SECONDS + CREATE_SERVICE_TIMEOUT_SECONDS
        + CREATE_SECRET_TIMEOUT_SECONDS + CREATE_STORAGE_CLASS_TIMEOUT_SECONDS
        + CREATE_PVC_TIMEOUT_SECONDS + CREATE_DEPLOYMENT_TIMEOUT_SECONDS
        + CREATE_INGRESS_TIMEOUT_SECONDS + BASE_TIMEOUT;

    public static final long DELETE_NAMESPACE_TIMEOUT_SECONDS = 60L;
    public static final long DELETE_INGRESS_TIMEOUT_SECONDS = BASE_TIMEOUT;
    public static final long DELETE_INGRESS_MIDDLEWARE_TIMEOUT_SECONDS = BASE_TIMEOUT;
    public static final long DELETE_DEPLOYMENT_TIMEOUT_SECONDS = 300L;
    public static final long DELETE_PVC_TIMEOUT_SECONDS = BASE_TIMEOUT;
    public static final long DELETE_STORAGE_CLASS_TIMEOUT_SECONDS = BASE_TIMEOUT;
    public static final long DELETE_SECRET_TIMEOUT_SECONDS = BASE_TIMEOUT;
    public static final long DELETE_FLOW_TIMEOUT_SECONDS = DELETE_INGRESS_TIMEOUT_SECONDS
        + DELETE_INGRESS_MIDDLEWARE_TIMEOUT_SECONDS + DELETE_DEPLOYMENT_TIMEOUT_SECONDS
        + DELETE_PVC_TIMEOUT_SECONDS + DELETE_STORAGE_CLASS_TIMEOUT_SECONDS
        + DELETE_SECRET_TIMEOUT_SECONDS;

    public static final long READ_METRICS_TIMEOUT_SECONDS = BASE_TIMEOUT;
    public static final long READ_STATUS_TIMEOUT_SECONDS = BASE_TIMEOUT;
    public static final long COPY_FILE_TIMEOUT_SECONDS = 300L;
    public static final long DELETE_NODE_TIMEOUT_SECONDS = 60L;
    public static final long DELETE_TASK_TIMEOUT_SECONDS = 5L;
    public static final long CONTROL_TIMEOUT_SECONDS = BASE_TIMEOUT;
    public static final long READ_LOGS_TIMEOUT_SECONDS = 5L;
}
