/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package net.statemesh.k8s.crd.postgresql.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * V1PostgresqlSpecAdditionalVolumes
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-03-10T17:14:22.403Z[Etc/UTC]")
public class V1PostgresqlSpecAdditionalVolumes {
  public static final String SERIALIZED_NAME_IS_SUB_PATH_EXPR = "isSubPathExpr";
  @SerializedName(SERIALIZED_NAME_IS_SUB_PATH_EXPR)
  private Boolean isSubPathExpr;

  public static final String SERIALIZED_NAME_MOUNT_PATH = "mountPath";
  @SerializedName(SERIALIZED_NAME_MOUNT_PATH)
  private String mountPath;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_SUB_PATH = "subPath";
  @SerializedName(SERIALIZED_NAME_SUB_PATH)
  private String subPath;

  public static final String SERIALIZED_NAME_TARGET_CONTAINERS = "targetContainers";
  @SerializedName(SERIALIZED_NAME_TARGET_CONTAINERS)
  private Object targetContainers;

  public static final String SERIALIZED_NAME_VOLUME_SOURCE = "volumeSource";
  @SerializedName(SERIALIZED_NAME_VOLUME_SOURCE)
  private Object volumeSource;


  public V1PostgresqlSpecAdditionalVolumes isSubPathExpr(Boolean isSubPathExpr) {
    
    this.isSubPathExpr = isSubPathExpr;
    return this;
  }

   /**
   * Get isSubPathExpr
   * @return isSubPathExpr
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getIsSubPathExpr() {
    return isSubPathExpr;
  }


  public void setIsSubPathExpr(Boolean isSubPathExpr) {
    this.isSubPathExpr = isSubPathExpr;
  }


  public V1PostgresqlSpecAdditionalVolumes mountPath(String mountPath) {
    
    this.mountPath = mountPath;
    return this;
  }

   /**
   * Get mountPath
   * @return mountPath
  **/
  @ApiModelProperty(required = true, value = "")

  public String getMountPath() {
    return mountPath;
  }


  public void setMountPath(String mountPath) {
    this.mountPath = mountPath;
  }


  public V1PostgresqlSpecAdditionalVolumes name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(required = true, value = "")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public V1PostgresqlSpecAdditionalVolumes subPath(String subPath) {
    
    this.subPath = subPath;
    return this;
  }

   /**
   * Get subPath
   * @return subPath
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getSubPath() {
    return subPath;
  }


  public void setSubPath(String subPath) {
    this.subPath = subPath;
  }


  public V1PostgresqlSpecAdditionalVolumes targetContainers(Object targetContainers) {
    
    this.targetContainers = targetContainers;
    return this;
  }

   /**
   * Get targetContainers
   * @return targetContainers
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Object getTargetContainers() {
    return targetContainers;
  }


  public void setTargetContainers(Object targetContainers) {
    this.targetContainers = targetContainers;
  }


  public V1PostgresqlSpecAdditionalVolumes volumeSource(Object volumeSource) {
    
    this.volumeSource = volumeSource;
    return this;
  }

   /**
   * Get volumeSource
   * @return volumeSource
  **/
  @ApiModelProperty(required = true, value = "")

  public Object getVolumeSource() {
    return volumeSource;
  }


  public void setVolumeSource(Object volumeSource) {
    this.volumeSource = volumeSource;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1PostgresqlSpecAdditionalVolumes v1PostgresqlSpecAdditionalVolumes = (V1PostgresqlSpecAdditionalVolumes) o;
    return Objects.equals(this.isSubPathExpr, v1PostgresqlSpecAdditionalVolumes.isSubPathExpr) &&
        Objects.equals(this.mountPath, v1PostgresqlSpecAdditionalVolumes.mountPath) &&
        Objects.equals(this.name, v1PostgresqlSpecAdditionalVolumes.name) &&
        Objects.equals(this.subPath, v1PostgresqlSpecAdditionalVolumes.subPath) &&
        Objects.equals(this.targetContainers, v1PostgresqlSpecAdditionalVolumes.targetContainers) &&
        Objects.equals(this.volumeSource, v1PostgresqlSpecAdditionalVolumes.volumeSource);
  }

  @Override
  public int hashCode() {
    return Objects.hash(isSubPathExpr, mountPath, name, subPath, targetContainers, volumeSource);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1PostgresqlSpecAdditionalVolumes {\n");
    sb.append("    isSubPathExpr: ").append(toIndentedString(isSubPathExpr)).append("\n");
    sb.append("    mountPath: ").append(toIndentedString(mountPath)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    subPath: ").append(toIndentedString(subPath)).append("\n");
    sb.append("    targetContainers: ").append(toIndentedString(targetContainers)).append("\n");
    sb.append("    volumeSource: ").append(toIndentedString(volumeSource)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

