/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package net.statemesh.k8s.crd.postgresql.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * V1PostgresqlSpecResourcesLimits
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-03-10T17:14:22.403Z[Etc/UTC]")
public class V1PostgresqlSpecResourcesLimits {
  public static final String SERIALIZED_NAME_CPU = "cpu";
  @SerializedName(SERIALIZED_NAME_CPU)
  private String cpu;

  public static final String SERIALIZED_NAME_HUGEPAGES1_GI = "hugepages-1Gi";
  @SerializedName(SERIALIZED_NAME_HUGEPAGES1_GI)
  private String hugepages1Gi;

  public static final String SERIALIZED_NAME_HUGEPAGES2_MI = "hugepages-2Mi";
  @SerializedName(SERIALIZED_NAME_HUGEPAGES2_MI)
  private String hugepages2Mi;

  public static final String SERIALIZED_NAME_MEMORY = "memory";
  @SerializedName(SERIALIZED_NAME_MEMORY)
  private String memory;


  public V1PostgresqlSpecResourcesLimits cpu(String cpu) {
    
    this.cpu = cpu;
    return this;
  }

   /**
   * Get cpu
   * @return cpu
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getCpu() {
    return cpu;
  }


  public void setCpu(String cpu) {
    this.cpu = cpu;
  }


  public V1PostgresqlSpecResourcesLimits hugepages1Gi(String hugepages1Gi) {
    
    this.hugepages1Gi = hugepages1Gi;
    return this;
  }

   /**
   * Get hugepages1Gi
   * @return hugepages1Gi
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getHugepages1Gi() {
    return hugepages1Gi;
  }


  public void setHugepages1Gi(String hugepages1Gi) {
    this.hugepages1Gi = hugepages1Gi;
  }


  public V1PostgresqlSpecResourcesLimits hugepages2Mi(String hugepages2Mi) {
    
    this.hugepages2Mi = hugepages2Mi;
    return this;
  }

   /**
   * Get hugepages2Mi
   * @return hugepages2Mi
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getHugepages2Mi() {
    return hugepages2Mi;
  }


  public void setHugepages2Mi(String hugepages2Mi) {
    this.hugepages2Mi = hugepages2Mi;
  }


  public V1PostgresqlSpecResourcesLimits memory(String memory) {
    
    this.memory = memory;
    return this;
  }

   /**
   * Get memory
   * @return memory
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getMemory() {
    return memory;
  }


  public void setMemory(String memory) {
    this.memory = memory;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1PostgresqlSpecResourcesLimits v1PostgresqlSpecResourcesLimits = (V1PostgresqlSpecResourcesLimits) o;
    return Objects.equals(this.cpu, v1PostgresqlSpecResourcesLimits.cpu) &&
        Objects.equals(this.hugepages1Gi, v1PostgresqlSpecResourcesLimits.hugepages1Gi) &&
        Objects.equals(this.hugepages2Mi, v1PostgresqlSpecResourcesLimits.hugepages2Mi) &&
        Objects.equals(this.memory, v1PostgresqlSpecResourcesLimits.memory);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cpu, hugepages1Gi, hugepages2Mi, memory);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1PostgresqlSpecResourcesLimits {\n");
    sb.append("    cpu: ").append(toIndentedString(cpu)).append("\n");
    sb.append("    hugepages1Gi: ").append(toIndentedString(hugepages1Gi)).append("\n");
    sb.append("    hugepages2Mi: ").append(toIndentedString(hugepages2Mi)).append("\n");
    sb.append("    memory: ").append(toIndentedString(memory)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

