/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.25.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package net.statemesh.k8s.crd.raycluster.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import net.statemesh.k8s.crd.raycluster.models.V1RayClusterSpecHeadGroupSpecTemplateSpecContainersInnerLifecyclePostStart;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import io.kubernetes.client.openapi.JSON;

/**
 * V1RayClusterSpecHeadGroupSpecTemplateSpecContainersInnerLifecycle
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-09-11T07:02:16.267867Z[Etc/UTC]")
public class V1RayClusterSpecHeadGroupSpecTemplateSpecContainersInnerLifecycle {
  public static final String SERIALIZED_NAME_POST_START = "postStart";
  @SerializedName(SERIALIZED_NAME_POST_START)
  private V1RayClusterSpecHeadGroupSpecTemplateSpecContainersInnerLifecyclePostStart postStart;

  public static final String SERIALIZED_NAME_PRE_STOP = "preStop";
  @SerializedName(SERIALIZED_NAME_PRE_STOP)
  private V1RayClusterSpecHeadGroupSpecTemplateSpecContainersInnerLifecyclePostStart preStop;

  public static final String SERIALIZED_NAME_STOP_SIGNAL = "stopSignal";
  @SerializedName(SERIALIZED_NAME_STOP_SIGNAL)
  private String stopSignal;

  public V1RayClusterSpecHeadGroupSpecTemplateSpecContainersInnerLifecycle() {
  }

  public V1RayClusterSpecHeadGroupSpecTemplateSpecContainersInnerLifecycle postStart(V1RayClusterSpecHeadGroupSpecTemplateSpecContainersInnerLifecyclePostStart postStart) {
    
    this.postStart = postStart;
    return this;
  }

   /**
   * Get postStart
   * @return postStart
  **/
  @jakarta.annotation.Nullable
  public V1RayClusterSpecHeadGroupSpecTemplateSpecContainersInnerLifecyclePostStart getPostStart() {
    return postStart;
  }


  public void setPostStart(V1RayClusterSpecHeadGroupSpecTemplateSpecContainersInnerLifecyclePostStart postStart) {
    this.postStart = postStart;
  }


  public V1RayClusterSpecHeadGroupSpecTemplateSpecContainersInnerLifecycle preStop(V1RayClusterSpecHeadGroupSpecTemplateSpecContainersInnerLifecyclePostStart preStop) {
    
    this.preStop = preStop;
    return this;
  }

   /**
   * Get preStop
   * @return preStop
  **/
  @jakarta.annotation.Nullable
  public V1RayClusterSpecHeadGroupSpecTemplateSpecContainersInnerLifecyclePostStart getPreStop() {
    return preStop;
  }


  public void setPreStop(V1RayClusterSpecHeadGroupSpecTemplateSpecContainersInnerLifecyclePostStart preStop) {
    this.preStop = preStop;
  }


  public V1RayClusterSpecHeadGroupSpecTemplateSpecContainersInnerLifecycle stopSignal(String stopSignal) {
    
    this.stopSignal = stopSignal;
    return this;
  }

   /**
   * Get stopSignal
   * @return stopSignal
  **/
  @jakarta.annotation.Nullable
  public String getStopSignal() {
    return stopSignal;
  }


  public void setStopSignal(String stopSignal) {
    this.stopSignal = stopSignal;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1RayClusterSpecHeadGroupSpecTemplateSpecContainersInnerLifecycle v1RayClusterSpecHeadGroupSpecTemplateSpecContainersInnerLifecycle = (V1RayClusterSpecHeadGroupSpecTemplateSpecContainersInnerLifecycle) o;
    return Objects.equals(this.postStart, v1RayClusterSpecHeadGroupSpecTemplateSpecContainersInnerLifecycle.postStart) &&
        Objects.equals(this.preStop, v1RayClusterSpecHeadGroupSpecTemplateSpecContainersInnerLifecycle.preStop) &&
        Objects.equals(this.stopSignal, v1RayClusterSpecHeadGroupSpecTemplateSpecContainersInnerLifecycle.stopSignal);
  }

  @Override
  public int hashCode() {
    return Objects.hash(postStart, preStop, stopSignal);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1RayClusterSpecHeadGroupSpecTemplateSpecContainersInnerLifecycle {\n");
    sb.append("    postStart: ").append(toIndentedString(postStart)).append("\n");
    sb.append("    preStop: ").append(toIndentedString(preStop)).append("\n");
    sb.append("    stopSignal: ").append(toIndentedString(stopSignal)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("postStart");
    openapiFields.add("preStop");
    openapiFields.add("stopSignal");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to V1RayClusterSpecHeadGroupSpecTemplateSpecContainersInnerLifecycle
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!V1RayClusterSpecHeadGroupSpecTemplateSpecContainersInnerLifecycle.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in V1RayClusterSpecHeadGroupSpecTemplateSpecContainersInnerLifecycle is not found in the empty JSON string", V1RayClusterSpecHeadGroupSpecTemplateSpecContainersInnerLifecycle.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!V1RayClusterSpecHeadGroupSpecTemplateSpecContainersInnerLifecycle.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `V1RayClusterSpecHeadGroupSpecTemplateSpecContainersInnerLifecycle` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }
      // validate the optional field `postStart`
      if (jsonObj.get("postStart") != null && !jsonObj.get("postStart").isJsonNull()) {
        V1RayClusterSpecHeadGroupSpecTemplateSpecContainersInnerLifecyclePostStart.validateJsonObject(jsonObj.getAsJsonObject("postStart"));
      }
      // validate the optional field `preStop`
      if (jsonObj.get("preStop") != null && !jsonObj.get("preStop").isJsonNull()) {
        V1RayClusterSpecHeadGroupSpecTemplateSpecContainersInnerLifecyclePostStart.validateJsonObject(jsonObj.getAsJsonObject("preStop"));
      }
      if ((jsonObj.get("stopSignal") != null && !jsonObj.get("stopSignal").isJsonNull()) && !jsonObj.get("stopSignal").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `stopSignal` to be a primitive type in the JSON string but got `%s`", jsonObj.get("stopSignal").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!V1RayClusterSpecHeadGroupSpecTemplateSpecContainersInnerLifecycle.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'V1RayClusterSpecHeadGroupSpecTemplateSpecContainersInnerLifecycle' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<V1RayClusterSpecHeadGroupSpecTemplateSpecContainersInnerLifecycle> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(V1RayClusterSpecHeadGroupSpecTemplateSpecContainersInnerLifecycle.class));

       return (TypeAdapter<T>) new TypeAdapter<V1RayClusterSpecHeadGroupSpecTemplateSpecContainersInnerLifecycle>() {
           @Override
           public void write(JsonWriter out, V1RayClusterSpecHeadGroupSpecTemplateSpecContainersInnerLifecycle value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public V1RayClusterSpecHeadGroupSpecTemplateSpecContainersInnerLifecycle read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of V1RayClusterSpecHeadGroupSpecTemplateSpecContainersInnerLifecycle given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of V1RayClusterSpecHeadGroupSpecTemplateSpecContainersInnerLifecycle
  * @throws IOException if the JSON string is invalid with respect to V1RayClusterSpecHeadGroupSpecTemplateSpecContainersInnerLifecycle
  */
  public static V1RayClusterSpecHeadGroupSpecTemplateSpecContainersInnerLifecycle fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, V1RayClusterSpecHeadGroupSpecTemplateSpecContainersInnerLifecycle.class);
  }

 /**
  * Convert an instance of V1RayClusterSpecHeadGroupSpecTemplateSpecContainersInnerLifecycle to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

