/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.25.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package net.statemesh.k8s.crd.tekton.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import io.kubernetes.client.openapi.JSON;

/**
 * RunResult is used to write key/value pairs to TaskRun pod termination messages. The key/value pairs may come from the entrypoint binary, or represent a TaskRunResult. If they represent a TaskRunResult, the key is the name of the result and the value is the JSON-serialized value of the result.
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-10-01T09:42:24.724862Z[Etc/UTC]")
public class V1beta1PipelineRunStatusTaskRunsValueStatusResourcesResultInner {
  public static final String SERIALIZED_NAME_KEY = "key";
  @SerializedName(SERIALIZED_NAME_KEY)
  private String key;

  public static final String SERIALIZED_NAME_RESOURCE_NAME = "resourceName";
  @SerializedName(SERIALIZED_NAME_RESOURCE_NAME)
  private String resourceName;

  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  private Integer type;

  public static final String SERIALIZED_NAME_VALUE = "value";
  @SerializedName(SERIALIZED_NAME_VALUE)
  private String value;

  public V1beta1PipelineRunStatusTaskRunsValueStatusResourcesResultInner() {
  }

  public V1beta1PipelineRunStatusTaskRunsValueStatusResourcesResultInner key(String key) {
    
    this.key = key;
    return this;
  }

   /**
   * Get key
   * @return key
  **/
  @jakarta.annotation.Nonnull
  public String getKey() {
    return key;
  }


  public void setKey(String key) {
    this.key = key;
  }


  public V1beta1PipelineRunStatusTaskRunsValueStatusResourcesResultInner resourceName(String resourceName) {
    
    this.resourceName = resourceName;
    return this;
  }

   /**
   * ResourceName may be used in tests, but it is not populated in termination messages. It is preserved here for backwards compatibility and will not be ported to v1.
   * @return resourceName
  **/
  @jakarta.annotation.Nullable
  public String getResourceName() {
    return resourceName;
  }


  public void setResourceName(String resourceName) {
    this.resourceName = resourceName;
  }


  public V1beta1PipelineRunStatusTaskRunsValueStatusResourcesResultInner type(Integer type) {
    
    this.type = type;
    return this;
  }

   /**
   * ResultType used to find out whether a RunResult is from a task result or not Note that ResultsType is another type which is used to define the data type (e.g. string, array, etc) we used for Results
   * @return type
  **/
  @jakarta.annotation.Nullable
  public Integer getType() {
    return type;
  }


  public void setType(Integer type) {
    this.type = type;
  }


  public V1beta1PipelineRunStatusTaskRunsValueStatusResourcesResultInner value(String value) {
    
    this.value = value;
    return this;
  }

   /**
   * Get value
   * @return value
  **/
  @jakarta.annotation.Nonnull
  public String getValue() {
    return value;
  }


  public void setValue(String value) {
    this.value = value;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1beta1PipelineRunStatusTaskRunsValueStatusResourcesResultInner v1beta1PipelineRunStatusTaskRunsValueStatusResourcesResultInner = (V1beta1PipelineRunStatusTaskRunsValueStatusResourcesResultInner) o;
    return Objects.equals(this.key, v1beta1PipelineRunStatusTaskRunsValueStatusResourcesResultInner.key) &&
        Objects.equals(this.resourceName, v1beta1PipelineRunStatusTaskRunsValueStatusResourcesResultInner.resourceName) &&
        Objects.equals(this.type, v1beta1PipelineRunStatusTaskRunsValueStatusResourcesResultInner.type) &&
        Objects.equals(this.value, v1beta1PipelineRunStatusTaskRunsValueStatusResourcesResultInner.value);
  }

  @Override
  public int hashCode() {
    return Objects.hash(key, resourceName, type, value);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1beta1PipelineRunStatusTaskRunsValueStatusResourcesResultInner {\n");
    sb.append("    key: ").append(toIndentedString(key)).append("\n");
    sb.append("    resourceName: ").append(toIndentedString(resourceName)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("key");
    openapiFields.add("resourceName");
    openapiFields.add("type");
    openapiFields.add("value");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("key");
    openapiRequiredFields.add("value");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to V1beta1PipelineRunStatusTaskRunsValueStatusResourcesResultInner
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!V1beta1PipelineRunStatusTaskRunsValueStatusResourcesResultInner.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in V1beta1PipelineRunStatusTaskRunsValueStatusResourcesResultInner is not found in the empty JSON string", V1beta1PipelineRunStatusTaskRunsValueStatusResourcesResultInner.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!V1beta1PipelineRunStatusTaskRunsValueStatusResourcesResultInner.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `V1beta1PipelineRunStatusTaskRunsValueStatusResourcesResultInner` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : V1beta1PipelineRunStatusTaskRunsValueStatusResourcesResultInner.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      if (!jsonObj.get("key").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `key` to be a primitive type in the JSON string but got `%s`", jsonObj.get("key").toString()));
      }
      if ((jsonObj.get("resourceName") != null && !jsonObj.get("resourceName").isJsonNull()) && !jsonObj.get("resourceName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `resourceName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("resourceName").toString()));
      }
      if (!jsonObj.get("value").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `value` to be a primitive type in the JSON string but got `%s`", jsonObj.get("value").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!V1beta1PipelineRunStatusTaskRunsValueStatusResourcesResultInner.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'V1beta1PipelineRunStatusTaskRunsValueStatusResourcesResultInner' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<V1beta1PipelineRunStatusTaskRunsValueStatusResourcesResultInner> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(V1beta1PipelineRunStatusTaskRunsValueStatusResourcesResultInner.class));

       return (TypeAdapter<T>) new TypeAdapter<V1beta1PipelineRunStatusTaskRunsValueStatusResourcesResultInner>() {
           @Override
           public void write(JsonWriter out, V1beta1PipelineRunStatusTaskRunsValueStatusResourcesResultInner value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public V1beta1PipelineRunStatusTaskRunsValueStatusResourcesResultInner read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of V1beta1PipelineRunStatusTaskRunsValueStatusResourcesResultInner given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of V1beta1PipelineRunStatusTaskRunsValueStatusResourcesResultInner
  * @throws IOException if the JSON string is invalid with respect to V1beta1PipelineRunStatusTaskRunsValueStatusResourcesResultInner
  */
  public static V1beta1PipelineRunStatusTaskRunsValueStatusResourcesResultInner fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, V1beta1PipelineRunStatusTaskRunsValueStatusResourcesResultInner.class);
  }

 /**
  * Convert an instance of V1beta1PipelineRunStatusTaskRunsValueStatusResourcesResultInner to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

