/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.25.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package net.statemesh.k8s.crd.tekton.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import net.statemesh.k8s.crd.tekton.models.V1PipelineRunStatusProvenanceFeatureFlags;
import net.statemesh.k8s.crd.tekton.models.V1PipelineRunStatusProvenanceRefSource;
import net.statemesh.k8s.crd.tekton.models.V1beta1PipelineRunStatusProvenanceConfigSource;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import io.kubernetes.client.openapi.JSON;

/**
 * Provenance contains metadata about resources used in the TaskRun/PipelineRun such as the source from where a remote build definition was fetched. This field aims to carry minimum amoumt of metadata in *Run status so that Tekton Chains can capture them in the provenance.
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-10-01T09:42:24.724862Z[Etc/UTC]")
public class V1beta1PipelineRunStatusTaskRunsValueStatusStepsInnerProvenance {
  public static final String SERIALIZED_NAME_CONFIG_SOURCE = "configSource";
  @SerializedName(SERIALIZED_NAME_CONFIG_SOURCE)
  private V1beta1PipelineRunStatusProvenanceConfigSource configSource;

  public static final String SERIALIZED_NAME_FEATURE_FLAGS = "featureFlags";
  @SerializedName(SERIALIZED_NAME_FEATURE_FLAGS)
  private V1PipelineRunStatusProvenanceFeatureFlags featureFlags;

  public static final String SERIALIZED_NAME_REF_SOURCE = "refSource";
  @SerializedName(SERIALIZED_NAME_REF_SOURCE)
  private V1PipelineRunStatusProvenanceRefSource refSource;

  public V1beta1PipelineRunStatusTaskRunsValueStatusStepsInnerProvenance() {
  }

  public V1beta1PipelineRunStatusTaskRunsValueStatusStepsInnerProvenance configSource(V1beta1PipelineRunStatusProvenanceConfigSource configSource) {
    
    this.configSource = configSource;
    return this;
  }

   /**
   * Get configSource
   * @return configSource
  **/
  @jakarta.annotation.Nullable
  public V1beta1PipelineRunStatusProvenanceConfigSource getConfigSource() {
    return configSource;
  }


  public void setConfigSource(V1beta1PipelineRunStatusProvenanceConfigSource configSource) {
    this.configSource = configSource;
  }


  public V1beta1PipelineRunStatusTaskRunsValueStatusStepsInnerProvenance featureFlags(V1PipelineRunStatusProvenanceFeatureFlags featureFlags) {
    
    this.featureFlags = featureFlags;
    return this;
  }

   /**
   * Get featureFlags
   * @return featureFlags
  **/
  @jakarta.annotation.Nullable
  public V1PipelineRunStatusProvenanceFeatureFlags getFeatureFlags() {
    return featureFlags;
  }


  public void setFeatureFlags(V1PipelineRunStatusProvenanceFeatureFlags featureFlags) {
    this.featureFlags = featureFlags;
  }


  public V1beta1PipelineRunStatusTaskRunsValueStatusStepsInnerProvenance refSource(V1PipelineRunStatusProvenanceRefSource refSource) {
    
    this.refSource = refSource;
    return this;
  }

   /**
   * Get refSource
   * @return refSource
  **/
  @jakarta.annotation.Nullable
  public V1PipelineRunStatusProvenanceRefSource getRefSource() {
    return refSource;
  }


  public void setRefSource(V1PipelineRunStatusProvenanceRefSource refSource) {
    this.refSource = refSource;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1beta1PipelineRunStatusTaskRunsValueStatusStepsInnerProvenance v1beta1PipelineRunStatusTaskRunsValueStatusStepsInnerProvenance = (V1beta1PipelineRunStatusTaskRunsValueStatusStepsInnerProvenance) o;
    return Objects.equals(this.configSource, v1beta1PipelineRunStatusTaskRunsValueStatusStepsInnerProvenance.configSource) &&
        Objects.equals(this.featureFlags, v1beta1PipelineRunStatusTaskRunsValueStatusStepsInnerProvenance.featureFlags) &&
        Objects.equals(this.refSource, v1beta1PipelineRunStatusTaskRunsValueStatusStepsInnerProvenance.refSource);
  }

  @Override
  public int hashCode() {
    return Objects.hash(configSource, featureFlags, refSource);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1beta1PipelineRunStatusTaskRunsValueStatusStepsInnerProvenance {\n");
    sb.append("    configSource: ").append(toIndentedString(configSource)).append("\n");
    sb.append("    featureFlags: ").append(toIndentedString(featureFlags)).append("\n");
    sb.append("    refSource: ").append(toIndentedString(refSource)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("configSource");
    openapiFields.add("featureFlags");
    openapiFields.add("refSource");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to V1beta1PipelineRunStatusTaskRunsValueStatusStepsInnerProvenance
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!V1beta1PipelineRunStatusTaskRunsValueStatusStepsInnerProvenance.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in V1beta1PipelineRunStatusTaskRunsValueStatusStepsInnerProvenance is not found in the empty JSON string", V1beta1PipelineRunStatusTaskRunsValueStatusStepsInnerProvenance.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!V1beta1PipelineRunStatusTaskRunsValueStatusStepsInnerProvenance.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `V1beta1PipelineRunStatusTaskRunsValueStatusStepsInnerProvenance` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }
      // validate the optional field `configSource`
      if (jsonObj.get("configSource") != null && !jsonObj.get("configSource").isJsonNull()) {
        V1beta1PipelineRunStatusProvenanceConfigSource.validateJsonObject(jsonObj.getAsJsonObject("configSource"));
      }
      // validate the optional field `featureFlags`
      if (jsonObj.get("featureFlags") != null && !jsonObj.get("featureFlags").isJsonNull()) {
        V1PipelineRunStatusProvenanceFeatureFlags.validateJsonObject(jsonObj.getAsJsonObject("featureFlags"));
      }
      // validate the optional field `refSource`
      if (jsonObj.get("refSource") != null && !jsonObj.get("refSource").isJsonNull()) {
        V1PipelineRunStatusProvenanceRefSource.validateJsonObject(jsonObj.getAsJsonObject("refSource"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!V1beta1PipelineRunStatusTaskRunsValueStatusStepsInnerProvenance.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'V1beta1PipelineRunStatusTaskRunsValueStatusStepsInnerProvenance' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<V1beta1PipelineRunStatusTaskRunsValueStatusStepsInnerProvenance> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(V1beta1PipelineRunStatusTaskRunsValueStatusStepsInnerProvenance.class));

       return (TypeAdapter<T>) new TypeAdapter<V1beta1PipelineRunStatusTaskRunsValueStatusStepsInnerProvenance>() {
           @Override
           public void write(JsonWriter out, V1beta1PipelineRunStatusTaskRunsValueStatusStepsInnerProvenance value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public V1beta1PipelineRunStatusTaskRunsValueStatusStepsInnerProvenance read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of V1beta1PipelineRunStatusTaskRunsValueStatusStepsInnerProvenance given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of V1beta1PipelineRunStatusTaskRunsValueStatusStepsInnerProvenance
  * @throws IOException if the JSON string is invalid with respect to V1beta1PipelineRunStatusTaskRunsValueStatusStepsInnerProvenance
  */
  public static V1beta1PipelineRunStatusTaskRunsValueStatusStepsInnerProvenance fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, V1beta1PipelineRunStatusTaskRunsValueStatusStepsInnerProvenance.class);
  }

 /**
  * Convert an instance of V1beta1PipelineRunStatusTaskRunsValueStatusStepsInnerProvenance to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

