/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.25.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package net.statemesh.k8s.crd.tekton.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import net.statemesh.k8s.crd.tekton.models.V1beta1TaskRunSpecResourcesInputsInner;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import io.kubernetes.client.openapi.JSON;

/**
 * Deprecated: Unused, preserved only for backwards compatibility
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-10-01T09:42:24.724862Z[Etc/UTC]")
public class V1beta1TaskRunSpecResources {
  public static final String SERIALIZED_NAME_INPUTS = "inputs";
  @SerializedName(SERIALIZED_NAME_INPUTS)
  private List<V1beta1TaskRunSpecResourcesInputsInner> inputs;

  public static final String SERIALIZED_NAME_OUTPUTS = "outputs";
  @SerializedName(SERIALIZED_NAME_OUTPUTS)
  private List<V1beta1TaskRunSpecResourcesInputsInner> outputs;

  public V1beta1TaskRunSpecResources() {
  }

  public V1beta1TaskRunSpecResources inputs(List<V1beta1TaskRunSpecResourcesInputsInner> inputs) {
    
    this.inputs = inputs;
    return this;
  }

  public V1beta1TaskRunSpecResources addInputsItem(V1beta1TaskRunSpecResourcesInputsInner inputsItem) {
    if (this.inputs == null) {
      this.inputs = new ArrayList<>();
    }
    this.inputs.add(inputsItem);
    return this;
  }

   /**
   * Inputs holds the inputs resources this task was invoked with
   * @return inputs
  **/
  @jakarta.annotation.Nullable
  public List<V1beta1TaskRunSpecResourcesInputsInner> getInputs() {
    return inputs;
  }


  public void setInputs(List<V1beta1TaskRunSpecResourcesInputsInner> inputs) {
    this.inputs = inputs;
  }


  public V1beta1TaskRunSpecResources outputs(List<V1beta1TaskRunSpecResourcesInputsInner> outputs) {
    
    this.outputs = outputs;
    return this;
  }

  public V1beta1TaskRunSpecResources addOutputsItem(V1beta1TaskRunSpecResourcesInputsInner outputsItem) {
    if (this.outputs == null) {
      this.outputs = new ArrayList<>();
    }
    this.outputs.add(outputsItem);
    return this;
  }

   /**
   * Outputs holds the inputs resources this task was invoked with
   * @return outputs
  **/
  @jakarta.annotation.Nullable
  public List<V1beta1TaskRunSpecResourcesInputsInner> getOutputs() {
    return outputs;
  }


  public void setOutputs(List<V1beta1TaskRunSpecResourcesInputsInner> outputs) {
    this.outputs = outputs;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1beta1TaskRunSpecResources v1beta1TaskRunSpecResources = (V1beta1TaskRunSpecResources) o;
    return Objects.equals(this.inputs, v1beta1TaskRunSpecResources.inputs) &&
        Objects.equals(this.outputs, v1beta1TaskRunSpecResources.outputs);
  }

  @Override
  public int hashCode() {
    return Objects.hash(inputs, outputs);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1beta1TaskRunSpecResources {\n");
    sb.append("    inputs: ").append(toIndentedString(inputs)).append("\n");
    sb.append("    outputs: ").append(toIndentedString(outputs)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("inputs");
    openapiFields.add("outputs");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to V1beta1TaskRunSpecResources
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!V1beta1TaskRunSpecResources.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in V1beta1TaskRunSpecResources is not found in the empty JSON string", V1beta1TaskRunSpecResources.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!V1beta1TaskRunSpecResources.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `V1beta1TaskRunSpecResources` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }
      if (jsonObj.get("inputs") != null && !jsonObj.get("inputs").isJsonNull()) {
        JsonArray jsonArrayinputs = jsonObj.getAsJsonArray("inputs");
        if (jsonArrayinputs != null) {
          // ensure the json data is an array
          if (!jsonObj.get("inputs").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `inputs` to be an array in the JSON string but got `%s`", jsonObj.get("inputs").toString()));
          }

          // validate the optional field `inputs` (array)
          for (int i = 0; i < jsonArrayinputs.size(); i++) {
            V1beta1TaskRunSpecResourcesInputsInner.validateJsonObject(jsonArrayinputs.get(i).getAsJsonObject());
          };
        }
      }
      if (jsonObj.get("outputs") != null && !jsonObj.get("outputs").isJsonNull()) {
        JsonArray jsonArrayoutputs = jsonObj.getAsJsonArray("outputs");
        if (jsonArrayoutputs != null) {
          // ensure the json data is an array
          if (!jsonObj.get("outputs").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `outputs` to be an array in the JSON string but got `%s`", jsonObj.get("outputs").toString()));
          }

          // validate the optional field `outputs` (array)
          for (int i = 0; i < jsonArrayoutputs.size(); i++) {
            V1beta1TaskRunSpecResourcesInputsInner.validateJsonObject(jsonArrayoutputs.get(i).getAsJsonObject());
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!V1beta1TaskRunSpecResources.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'V1beta1TaskRunSpecResources' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<V1beta1TaskRunSpecResources> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(V1beta1TaskRunSpecResources.class));

       return (TypeAdapter<T>) new TypeAdapter<V1beta1TaskRunSpecResources>() {
           @Override
           public void write(JsonWriter out, V1beta1TaskRunSpecResources value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public V1beta1TaskRunSpecResources read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of V1beta1TaskRunSpecResources given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of V1beta1TaskRunSpecResources
  * @throws IOException if the JSON string is invalid with respect to V1beta1TaskRunSpecResources
  */
  public static V1beta1TaskRunSpecResources fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, V1beta1TaskRunSpecResources.class);
  }

 /**
  * Convert an instance of V1beta1TaskRunSpecResources to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

