/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.25.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package net.statemesh.k8s.crd.tekton.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import net.statemesh.k8s.crd.tekton.models.V1PipelineRunStatusConditionsInner;
import net.statemesh.k8s.crd.tekton.models.V1TaskRunStatusResultsInner;
import net.statemesh.k8s.crd.tekton.models.V1TaskRunStatusSidecarsInner;
import net.statemesh.k8s.crd.tekton.models.V1beta1PipelineRunStatusProvenance;
import net.statemesh.k8s.crd.tekton.models.V1beta1PipelineRunStatusTaskRunsValueStatusCloudEventsInner;
import net.statemesh.k8s.crd.tekton.models.V1beta1PipelineRunStatusTaskRunsValueStatusResourcesResultInner;
import net.statemesh.k8s.crd.tekton.models.V1beta1PipelineRunStatusTaskRunsValueStatusStepsInner;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import io.kubernetes.client.openapi.JSON;

/**
 * Status is the TaskRunStatus for the corresponding TaskRun
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-10-01T09:42:24.724862Z[Etc/UTC]")
public class V1beta1PipelineRunStatusTaskRunsValueStatus {
  public static final String SERIALIZED_NAME_ANNOTATIONS = "annotations";
  @SerializedName(SERIALIZED_NAME_ANNOTATIONS)
  private Map<String, String> annotations = new HashMap<>();

  public static final String SERIALIZED_NAME_CLOUD_EVENTS = "cloudEvents";
  @SerializedName(SERIALIZED_NAME_CLOUD_EVENTS)
  private List<V1beta1PipelineRunStatusTaskRunsValueStatusCloudEventsInner> cloudEvents;

  public static final String SERIALIZED_NAME_COMPLETION_TIME = "completionTime";
  @SerializedName(SERIALIZED_NAME_COMPLETION_TIME)
  private OffsetDateTime completionTime;

  public static final String SERIALIZED_NAME_CONDITIONS = "conditions";
  @SerializedName(SERIALIZED_NAME_CONDITIONS)
  private List<V1PipelineRunStatusConditionsInner> conditions;

  public static final String SERIALIZED_NAME_OBSERVED_GENERATION = "observedGeneration";
  @SerializedName(SERIALIZED_NAME_OBSERVED_GENERATION)
  private Long observedGeneration;

  public static final String SERIALIZED_NAME_POD_NAME = "podName";
  @SerializedName(SERIALIZED_NAME_POD_NAME)
  private String podName;

  public static final String SERIALIZED_NAME_PROVENANCE = "provenance";
  @SerializedName(SERIALIZED_NAME_PROVENANCE)
  private V1beta1PipelineRunStatusProvenance provenance;

  public static final String SERIALIZED_NAME_RESOURCES_RESULT = "resourcesResult";
  @SerializedName(SERIALIZED_NAME_RESOURCES_RESULT)
  private List<V1beta1PipelineRunStatusTaskRunsValueStatusResourcesResultInner> resourcesResult;

  public static final String SERIALIZED_NAME_RETRIES_STATUS = "retriesStatus";
  @SerializedName(SERIALIZED_NAME_RETRIES_STATUS)
  private Object retriesStatus;

  public static final String SERIALIZED_NAME_SIDECARS = "sidecars";
  @SerializedName(SERIALIZED_NAME_SIDECARS)
  private List<V1TaskRunStatusSidecarsInner> sidecars;

  public static final String SERIALIZED_NAME_SPAN_CONTEXT = "spanContext";
  @SerializedName(SERIALIZED_NAME_SPAN_CONTEXT)
  private Map<String, String> spanContext = new HashMap<>();

  public static final String SERIALIZED_NAME_START_TIME = "startTime";
  @SerializedName(SERIALIZED_NAME_START_TIME)
  private OffsetDateTime startTime;

  public static final String SERIALIZED_NAME_STEPS = "steps";
  @SerializedName(SERIALIZED_NAME_STEPS)
  private List<V1beta1PipelineRunStatusTaskRunsValueStatusStepsInner> steps;

  public static final String SERIALIZED_NAME_TASK_RESULTS = "taskResults";
  @SerializedName(SERIALIZED_NAME_TASK_RESULTS)
  private List<V1TaskRunStatusResultsInner> taskResults;

  public static final String SERIALIZED_NAME_TASK_SPEC = "taskSpec";
  @SerializedName(SERIALIZED_NAME_TASK_SPEC)
  private Object taskSpec;

  public V1beta1PipelineRunStatusTaskRunsValueStatus() {
  }

  public V1beta1PipelineRunStatusTaskRunsValueStatus annotations(Map<String, String> annotations) {
    
    this.annotations = annotations;
    return this;
  }

  public V1beta1PipelineRunStatusTaskRunsValueStatus putAnnotationsItem(String key, String annotationsItem) {
    if (this.annotations == null) {
      this.annotations = new HashMap<>();
    }
    this.annotations.put(key, annotationsItem);
    return this;
  }

   /**
   * Annotations is additional Status fields for the Resource to save some additional State as well as convey more information to the user. This is roughly akin to Annotations on any k8s resource, just the reconciler conveying richer information outwards.
   * @return annotations
  **/
  @jakarta.annotation.Nullable
  public Map<String, String> getAnnotations() {
    return annotations;
  }


  public void setAnnotations(Map<String, String> annotations) {
    this.annotations = annotations;
  }


  public V1beta1PipelineRunStatusTaskRunsValueStatus cloudEvents(List<V1beta1PipelineRunStatusTaskRunsValueStatusCloudEventsInner> cloudEvents) {
    
    this.cloudEvents = cloudEvents;
    return this;
  }

  public V1beta1PipelineRunStatusTaskRunsValueStatus addCloudEventsItem(V1beta1PipelineRunStatusTaskRunsValueStatusCloudEventsInner cloudEventsItem) {
    if (this.cloudEvents == null) {
      this.cloudEvents = new ArrayList<>();
    }
    this.cloudEvents.add(cloudEventsItem);
    return this;
  }

   /**
   * CloudEvents describe the state of each cloud event requested via a CloudEventResource.  Deprecated: Removed in v0.44.0.
   * @return cloudEvents
  **/
  @jakarta.annotation.Nullable
  public List<V1beta1PipelineRunStatusTaskRunsValueStatusCloudEventsInner> getCloudEvents() {
    return cloudEvents;
  }


  public void setCloudEvents(List<V1beta1PipelineRunStatusTaskRunsValueStatusCloudEventsInner> cloudEvents) {
    this.cloudEvents = cloudEvents;
  }


  public V1beta1PipelineRunStatusTaskRunsValueStatus completionTime(OffsetDateTime completionTime) {
    
    this.completionTime = completionTime;
    return this;
  }

   /**
   * CompletionTime is the time the build completed.
   * @return completionTime
  **/
  @jakarta.annotation.Nullable
  public OffsetDateTime getCompletionTime() {
    return completionTime;
  }


  public void setCompletionTime(OffsetDateTime completionTime) {
    this.completionTime = completionTime;
  }


  public V1beta1PipelineRunStatusTaskRunsValueStatus conditions(List<V1PipelineRunStatusConditionsInner> conditions) {
    
    this.conditions = conditions;
    return this;
  }

  public V1beta1PipelineRunStatusTaskRunsValueStatus addConditionsItem(V1PipelineRunStatusConditionsInner conditionsItem) {
    if (this.conditions == null) {
      this.conditions = new ArrayList<>();
    }
    this.conditions.add(conditionsItem);
    return this;
  }

   /**
   * Conditions the latest available observations of a resource&#39;s current state.
   * @return conditions
  **/
  @jakarta.annotation.Nullable
  public List<V1PipelineRunStatusConditionsInner> getConditions() {
    return conditions;
  }


  public void setConditions(List<V1PipelineRunStatusConditionsInner> conditions) {
    this.conditions = conditions;
  }


  public V1beta1PipelineRunStatusTaskRunsValueStatus observedGeneration(Long observedGeneration) {
    
    this.observedGeneration = observedGeneration;
    return this;
  }

   /**
   * ObservedGeneration is the &#39;Generation&#39; of the Service that was last processed by the controller.
   * @return observedGeneration
  **/
  @jakarta.annotation.Nullable
  public Long getObservedGeneration() {
    return observedGeneration;
  }


  public void setObservedGeneration(Long observedGeneration) {
    this.observedGeneration = observedGeneration;
  }


  public V1beta1PipelineRunStatusTaskRunsValueStatus podName(String podName) {
    
    this.podName = podName;
    return this;
  }

   /**
   * PodName is the name of the pod responsible for executing this task&#39;s steps.
   * @return podName
  **/
  @jakarta.annotation.Nonnull
  public String getPodName() {
    return podName;
  }


  public void setPodName(String podName) {
    this.podName = podName;
  }


  public V1beta1PipelineRunStatusTaskRunsValueStatus provenance(V1beta1PipelineRunStatusProvenance provenance) {
    
    this.provenance = provenance;
    return this;
  }

   /**
   * Get provenance
   * @return provenance
  **/
  @jakarta.annotation.Nullable
  public V1beta1PipelineRunStatusProvenance getProvenance() {
    return provenance;
  }


  public void setProvenance(V1beta1PipelineRunStatusProvenance provenance) {
    this.provenance = provenance;
  }


  public V1beta1PipelineRunStatusTaskRunsValueStatus resourcesResult(List<V1beta1PipelineRunStatusTaskRunsValueStatusResourcesResultInner> resourcesResult) {
    
    this.resourcesResult = resourcesResult;
    return this;
  }

  public V1beta1PipelineRunStatusTaskRunsValueStatus addResourcesResultItem(V1beta1PipelineRunStatusTaskRunsValueStatusResourcesResultInner resourcesResultItem) {
    if (this.resourcesResult == null) {
      this.resourcesResult = new ArrayList<>();
    }
    this.resourcesResult.add(resourcesResultItem);
    return this;
  }

   /**
   * Results from Resources built during the TaskRun. This is tomb-stoned along with the removal of pipelineResources Deprecated: this field is not populated and is preserved only for backwards compatibility
   * @return resourcesResult
  **/
  @jakarta.annotation.Nullable
  public List<V1beta1PipelineRunStatusTaskRunsValueStatusResourcesResultInner> getResourcesResult() {
    return resourcesResult;
  }


  public void setResourcesResult(List<V1beta1PipelineRunStatusTaskRunsValueStatusResourcesResultInner> resourcesResult) {
    this.resourcesResult = resourcesResult;
  }


  public V1beta1PipelineRunStatusTaskRunsValueStatus retriesStatus(Object retriesStatus) {
    
    this.retriesStatus = retriesStatus;
    return this;
  }

   /**
   * RetriesStatus contains the history of TaskRunStatus in case of a retry in order to keep record of failures. All TaskRunStatus stored in RetriesStatus will have no date within the RetriesStatus as is redundant. See TaskRun.status (API version: tekton.dev/v1beta1)
   * @return retriesStatus
  **/
  @jakarta.annotation.Nullable
  public Object getRetriesStatus() {
    return retriesStatus;
  }


  public void setRetriesStatus(Object retriesStatus) {
    this.retriesStatus = retriesStatus;
  }


  public V1beta1PipelineRunStatusTaskRunsValueStatus sidecars(List<V1TaskRunStatusSidecarsInner> sidecars) {
    
    this.sidecars = sidecars;
    return this;
  }

  public V1beta1PipelineRunStatusTaskRunsValueStatus addSidecarsItem(V1TaskRunStatusSidecarsInner sidecarsItem) {
    if (this.sidecars == null) {
      this.sidecars = new ArrayList<>();
    }
    this.sidecars.add(sidecarsItem);
    return this;
  }

   /**
   * The list has one entry per sidecar in the manifest. Each entry is represents the imageid of the corresponding sidecar.
   * @return sidecars
  **/
  @jakarta.annotation.Nullable
  public List<V1TaskRunStatusSidecarsInner> getSidecars() {
    return sidecars;
  }


  public void setSidecars(List<V1TaskRunStatusSidecarsInner> sidecars) {
    this.sidecars = sidecars;
  }


  public V1beta1PipelineRunStatusTaskRunsValueStatus spanContext(Map<String, String> spanContext) {
    
    this.spanContext = spanContext;
    return this;
  }

  public V1beta1PipelineRunStatusTaskRunsValueStatus putSpanContextItem(String key, String spanContextItem) {
    if (this.spanContext == null) {
      this.spanContext = new HashMap<>();
    }
    this.spanContext.put(key, spanContextItem);
    return this;
  }

   /**
   * SpanContext contains tracing span context fields
   * @return spanContext
  **/
  @jakarta.annotation.Nullable
  public Map<String, String> getSpanContext() {
    return spanContext;
  }


  public void setSpanContext(Map<String, String> spanContext) {
    this.spanContext = spanContext;
  }


  public V1beta1PipelineRunStatusTaskRunsValueStatus startTime(OffsetDateTime startTime) {
    
    this.startTime = startTime;
    return this;
  }

   /**
   * StartTime is the time the build is actually started.
   * @return startTime
  **/
  @jakarta.annotation.Nullable
  public OffsetDateTime getStartTime() {
    return startTime;
  }


  public void setStartTime(OffsetDateTime startTime) {
    this.startTime = startTime;
  }


  public V1beta1PipelineRunStatusTaskRunsValueStatus steps(List<V1beta1PipelineRunStatusTaskRunsValueStatusStepsInner> steps) {
    
    this.steps = steps;
    return this;
  }

  public V1beta1PipelineRunStatusTaskRunsValueStatus addStepsItem(V1beta1PipelineRunStatusTaskRunsValueStatusStepsInner stepsItem) {
    if (this.steps == null) {
      this.steps = new ArrayList<>();
    }
    this.steps.add(stepsItem);
    return this;
  }

   /**
   * Steps describes the state of each build step container.
   * @return steps
  **/
  @jakarta.annotation.Nullable
  public List<V1beta1PipelineRunStatusTaskRunsValueStatusStepsInner> getSteps() {
    return steps;
  }


  public void setSteps(List<V1beta1PipelineRunStatusTaskRunsValueStatusStepsInner> steps) {
    this.steps = steps;
  }


  public V1beta1PipelineRunStatusTaskRunsValueStatus taskResults(List<V1TaskRunStatusResultsInner> taskResults) {
    
    this.taskResults = taskResults;
    return this;
  }

  public V1beta1PipelineRunStatusTaskRunsValueStatus addTaskResultsItem(V1TaskRunStatusResultsInner taskResultsItem) {
    if (this.taskResults == null) {
      this.taskResults = new ArrayList<>();
    }
    this.taskResults.add(taskResultsItem);
    return this;
  }

   /**
   * TaskRunResults are the list of results written out by the task&#39;s containers
   * @return taskResults
  **/
  @jakarta.annotation.Nullable
  public List<V1TaskRunStatusResultsInner> getTaskResults() {
    return taskResults;
  }


  public void setTaskResults(List<V1TaskRunStatusResultsInner> taskResults) {
    this.taskResults = taskResults;
  }


  public V1beta1PipelineRunStatusTaskRunsValueStatus taskSpec(Object taskSpec) {
    
    this.taskSpec = taskSpec;
    return this;
  }

   /**
   * TaskSpec contains the Spec from the dereferenced Task definition used to instantiate this TaskRun. See Task.spec (API version tekton.dev/v1beta1)
   * @return taskSpec
  **/
  @jakarta.annotation.Nullable
  public Object getTaskSpec() {
    return taskSpec;
  }


  public void setTaskSpec(Object taskSpec) {
    this.taskSpec = taskSpec;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1beta1PipelineRunStatusTaskRunsValueStatus v1beta1PipelineRunStatusTaskRunsValueStatus = (V1beta1PipelineRunStatusTaskRunsValueStatus) o;
    return Objects.equals(this.annotations, v1beta1PipelineRunStatusTaskRunsValueStatus.annotations) &&
        Objects.equals(this.cloudEvents, v1beta1PipelineRunStatusTaskRunsValueStatus.cloudEvents) &&
        Objects.equals(this.completionTime, v1beta1PipelineRunStatusTaskRunsValueStatus.completionTime) &&
        Objects.equals(this.conditions, v1beta1PipelineRunStatusTaskRunsValueStatus.conditions) &&
        Objects.equals(this.observedGeneration, v1beta1PipelineRunStatusTaskRunsValueStatus.observedGeneration) &&
        Objects.equals(this.podName, v1beta1PipelineRunStatusTaskRunsValueStatus.podName) &&
        Objects.equals(this.provenance, v1beta1PipelineRunStatusTaskRunsValueStatus.provenance) &&
        Objects.equals(this.resourcesResult, v1beta1PipelineRunStatusTaskRunsValueStatus.resourcesResult) &&
        Objects.equals(this.retriesStatus, v1beta1PipelineRunStatusTaskRunsValueStatus.retriesStatus) &&
        Objects.equals(this.sidecars, v1beta1PipelineRunStatusTaskRunsValueStatus.sidecars) &&
        Objects.equals(this.spanContext, v1beta1PipelineRunStatusTaskRunsValueStatus.spanContext) &&
        Objects.equals(this.startTime, v1beta1PipelineRunStatusTaskRunsValueStatus.startTime) &&
        Objects.equals(this.steps, v1beta1PipelineRunStatusTaskRunsValueStatus.steps) &&
        Objects.equals(this.taskResults, v1beta1PipelineRunStatusTaskRunsValueStatus.taskResults) &&
        Objects.equals(this.taskSpec, v1beta1PipelineRunStatusTaskRunsValueStatus.taskSpec);
  }

  @Override
  public int hashCode() {
    return Objects.hash(annotations, cloudEvents, completionTime, conditions, observedGeneration, podName, provenance, resourcesResult, retriesStatus, sidecars, spanContext, startTime, steps, taskResults, taskSpec);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1beta1PipelineRunStatusTaskRunsValueStatus {\n");
    sb.append("    annotations: ").append(toIndentedString(annotations)).append("\n");
    sb.append("    cloudEvents: ").append(toIndentedString(cloudEvents)).append("\n");
    sb.append("    completionTime: ").append(toIndentedString(completionTime)).append("\n");
    sb.append("    conditions: ").append(toIndentedString(conditions)).append("\n");
    sb.append("    observedGeneration: ").append(toIndentedString(observedGeneration)).append("\n");
    sb.append("    podName: ").append(toIndentedString(podName)).append("\n");
    sb.append("    provenance: ").append(toIndentedString(provenance)).append("\n");
    sb.append("    resourcesResult: ").append(toIndentedString(resourcesResult)).append("\n");
    sb.append("    retriesStatus: ").append(toIndentedString(retriesStatus)).append("\n");
    sb.append("    sidecars: ").append(toIndentedString(sidecars)).append("\n");
    sb.append("    spanContext: ").append(toIndentedString(spanContext)).append("\n");
    sb.append("    startTime: ").append(toIndentedString(startTime)).append("\n");
    sb.append("    steps: ").append(toIndentedString(steps)).append("\n");
    sb.append("    taskResults: ").append(toIndentedString(taskResults)).append("\n");
    sb.append("    taskSpec: ").append(toIndentedString(taskSpec)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("annotations");
    openapiFields.add("cloudEvents");
    openapiFields.add("completionTime");
    openapiFields.add("conditions");
    openapiFields.add("observedGeneration");
    openapiFields.add("podName");
    openapiFields.add("provenance");
    openapiFields.add("resourcesResult");
    openapiFields.add("retriesStatus");
    openapiFields.add("sidecars");
    openapiFields.add("spanContext");
    openapiFields.add("startTime");
    openapiFields.add("steps");
    openapiFields.add("taskResults");
    openapiFields.add("taskSpec");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("podName");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to V1beta1PipelineRunStatusTaskRunsValueStatus
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!V1beta1PipelineRunStatusTaskRunsValueStatus.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in V1beta1PipelineRunStatusTaskRunsValueStatus is not found in the empty JSON string", V1beta1PipelineRunStatusTaskRunsValueStatus.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!V1beta1PipelineRunStatusTaskRunsValueStatus.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `V1beta1PipelineRunStatusTaskRunsValueStatus` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : V1beta1PipelineRunStatusTaskRunsValueStatus.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      if (jsonObj.get("cloudEvents") != null && !jsonObj.get("cloudEvents").isJsonNull()) {
        JsonArray jsonArraycloudEvents = jsonObj.getAsJsonArray("cloudEvents");
        if (jsonArraycloudEvents != null) {
          // ensure the json data is an array
          if (!jsonObj.get("cloudEvents").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `cloudEvents` to be an array in the JSON string but got `%s`", jsonObj.get("cloudEvents").toString()));
          }

          // validate the optional field `cloudEvents` (array)
          for (int i = 0; i < jsonArraycloudEvents.size(); i++) {
            V1beta1PipelineRunStatusTaskRunsValueStatusCloudEventsInner.validateJsonObject(jsonArraycloudEvents.get(i).getAsJsonObject());
          };
        }
      }
      if (jsonObj.get("conditions") != null && !jsonObj.get("conditions").isJsonNull()) {
        JsonArray jsonArrayconditions = jsonObj.getAsJsonArray("conditions");
        if (jsonArrayconditions != null) {
          // ensure the json data is an array
          if (!jsonObj.get("conditions").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `conditions` to be an array in the JSON string but got `%s`", jsonObj.get("conditions").toString()));
          }

          // validate the optional field `conditions` (array)
          for (int i = 0; i < jsonArrayconditions.size(); i++) {
            V1PipelineRunStatusConditionsInner.validateJsonObject(jsonArrayconditions.get(i).getAsJsonObject());
          };
        }
      }
      if (!jsonObj.get("podName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `podName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("podName").toString()));
      }
      // validate the optional field `provenance`
      if (jsonObj.get("provenance") != null && !jsonObj.get("provenance").isJsonNull()) {
        V1beta1PipelineRunStatusProvenance.validateJsonObject(jsonObj.getAsJsonObject("provenance"));
      }
      if (jsonObj.get("resourcesResult") != null && !jsonObj.get("resourcesResult").isJsonNull()) {
        JsonArray jsonArrayresourcesResult = jsonObj.getAsJsonArray("resourcesResult");
        if (jsonArrayresourcesResult != null) {
          // ensure the json data is an array
          if (!jsonObj.get("resourcesResult").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `resourcesResult` to be an array in the JSON string but got `%s`", jsonObj.get("resourcesResult").toString()));
          }

          // validate the optional field `resourcesResult` (array)
          for (int i = 0; i < jsonArrayresourcesResult.size(); i++) {
            V1beta1PipelineRunStatusTaskRunsValueStatusResourcesResultInner.validateJsonObject(jsonArrayresourcesResult.get(i).getAsJsonObject());
          };
        }
      }
      if (jsonObj.get("sidecars") != null && !jsonObj.get("sidecars").isJsonNull()) {
        JsonArray jsonArraysidecars = jsonObj.getAsJsonArray("sidecars");
        if (jsonArraysidecars != null) {
          // ensure the json data is an array
          if (!jsonObj.get("sidecars").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `sidecars` to be an array in the JSON string but got `%s`", jsonObj.get("sidecars").toString()));
          }

          // validate the optional field `sidecars` (array)
          for (int i = 0; i < jsonArraysidecars.size(); i++) {
            V1TaskRunStatusSidecarsInner.validateJsonObject(jsonArraysidecars.get(i).getAsJsonObject());
          };
        }
      }
      if (jsonObj.get("steps") != null && !jsonObj.get("steps").isJsonNull()) {
        JsonArray jsonArraysteps = jsonObj.getAsJsonArray("steps");
        if (jsonArraysteps != null) {
          // ensure the json data is an array
          if (!jsonObj.get("steps").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `steps` to be an array in the JSON string but got `%s`", jsonObj.get("steps").toString()));
          }

          // validate the optional field `steps` (array)
          for (int i = 0; i < jsonArraysteps.size(); i++) {
            V1beta1PipelineRunStatusTaskRunsValueStatusStepsInner.validateJsonObject(jsonArraysteps.get(i).getAsJsonObject());
          };
        }
      }
      if (jsonObj.get("taskResults") != null && !jsonObj.get("taskResults").isJsonNull()) {
        JsonArray jsonArraytaskResults = jsonObj.getAsJsonArray("taskResults");
        if (jsonArraytaskResults != null) {
          // ensure the json data is an array
          if (!jsonObj.get("taskResults").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `taskResults` to be an array in the JSON string but got `%s`", jsonObj.get("taskResults").toString()));
          }

          // validate the optional field `taskResults` (array)
          for (int i = 0; i < jsonArraytaskResults.size(); i++) {
            V1TaskRunStatusResultsInner.validateJsonObject(jsonArraytaskResults.get(i).getAsJsonObject());
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!V1beta1PipelineRunStatusTaskRunsValueStatus.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'V1beta1PipelineRunStatusTaskRunsValueStatus' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<V1beta1PipelineRunStatusTaskRunsValueStatus> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(V1beta1PipelineRunStatusTaskRunsValueStatus.class));

       return (TypeAdapter<T>) new TypeAdapter<V1beta1PipelineRunStatusTaskRunsValueStatus>() {
           @Override
           public void write(JsonWriter out, V1beta1PipelineRunStatusTaskRunsValueStatus value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public V1beta1PipelineRunStatusTaskRunsValueStatus read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of V1beta1PipelineRunStatusTaskRunsValueStatus given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of V1beta1PipelineRunStatusTaskRunsValueStatus
  * @throws IOException if the JSON string is invalid with respect to V1beta1PipelineRunStatusTaskRunsValueStatus
  */
  public static V1beta1PipelineRunStatusTaskRunsValueStatus fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, V1beta1PipelineRunStatusTaskRunsValueStatus.class);
  }

 /**
  * Convert an instance of V1beta1PipelineRunStatusTaskRunsValueStatus to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

