/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.25.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package net.statemesh.k8s.crd.tekton.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import net.statemesh.k8s.crd.tekton.models.V1PipelineRunSpecWorkspacesInnerProjectedSourcesInnerDownwardAPIItemsInner;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import io.kubernetes.client.openapi.JSON;

/**
 * downwardAPI information about the downwardAPI data to project
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-10-01T09:42:24.724862Z[Etc/UTC]")
public class V1PipelineRunSpecWorkspacesInnerProjectedSourcesInnerDownwardAPI {
  public static final String SERIALIZED_NAME_ITEMS = "items";
  @SerializedName(SERIALIZED_NAME_ITEMS)
  private List<V1PipelineRunSpecWorkspacesInnerProjectedSourcesInnerDownwardAPIItemsInner> items;

  public V1PipelineRunSpecWorkspacesInnerProjectedSourcesInnerDownwardAPI() {
  }

  public V1PipelineRunSpecWorkspacesInnerProjectedSourcesInnerDownwardAPI items(List<V1PipelineRunSpecWorkspacesInnerProjectedSourcesInnerDownwardAPIItemsInner> items) {
    
    this.items = items;
    return this;
  }

  public V1PipelineRunSpecWorkspacesInnerProjectedSourcesInnerDownwardAPI addItemsItem(V1PipelineRunSpecWorkspacesInnerProjectedSourcesInnerDownwardAPIItemsInner itemsItem) {
    if (this.items == null) {
      this.items = new ArrayList<>();
    }
    this.items.add(itemsItem);
    return this;
  }

   /**
   * Items is a list of DownwardAPIVolume file
   * @return items
  **/
  @jakarta.annotation.Nullable
  public List<V1PipelineRunSpecWorkspacesInnerProjectedSourcesInnerDownwardAPIItemsInner> getItems() {
    return items;
  }


  public void setItems(List<V1PipelineRunSpecWorkspacesInnerProjectedSourcesInnerDownwardAPIItemsInner> items) {
    this.items = items;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1PipelineRunSpecWorkspacesInnerProjectedSourcesInnerDownwardAPI v1PipelineRunSpecWorkspacesInnerProjectedSourcesInnerDownwardAPI = (V1PipelineRunSpecWorkspacesInnerProjectedSourcesInnerDownwardAPI) o;
    return Objects.equals(this.items, v1PipelineRunSpecWorkspacesInnerProjectedSourcesInnerDownwardAPI.items);
  }

  @Override
  public int hashCode() {
    return Objects.hash(items);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1PipelineRunSpecWorkspacesInnerProjectedSourcesInnerDownwardAPI {\n");
    sb.append("    items: ").append(toIndentedString(items)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("items");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to V1PipelineRunSpecWorkspacesInnerProjectedSourcesInnerDownwardAPI
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!V1PipelineRunSpecWorkspacesInnerProjectedSourcesInnerDownwardAPI.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in V1PipelineRunSpecWorkspacesInnerProjectedSourcesInnerDownwardAPI is not found in the empty JSON string", V1PipelineRunSpecWorkspacesInnerProjectedSourcesInnerDownwardAPI.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!V1PipelineRunSpecWorkspacesInnerProjectedSourcesInnerDownwardAPI.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `V1PipelineRunSpecWorkspacesInnerProjectedSourcesInnerDownwardAPI` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }
      if (jsonObj.get("items") != null && !jsonObj.get("items").isJsonNull()) {
        JsonArray jsonArrayitems = jsonObj.getAsJsonArray("items");
        if (jsonArrayitems != null) {
          // ensure the json data is an array
          if (!jsonObj.get("items").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `items` to be an array in the JSON string but got `%s`", jsonObj.get("items").toString()));
          }

          // validate the optional field `items` (array)
          for (int i = 0; i < jsonArrayitems.size(); i++) {
            V1PipelineRunSpecWorkspacesInnerProjectedSourcesInnerDownwardAPIItemsInner.validateJsonObject(jsonArrayitems.get(i).getAsJsonObject());
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!V1PipelineRunSpecWorkspacesInnerProjectedSourcesInnerDownwardAPI.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'V1PipelineRunSpecWorkspacesInnerProjectedSourcesInnerDownwardAPI' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<V1PipelineRunSpecWorkspacesInnerProjectedSourcesInnerDownwardAPI> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(V1PipelineRunSpecWorkspacesInnerProjectedSourcesInnerDownwardAPI.class));

       return (TypeAdapter<T>) new TypeAdapter<V1PipelineRunSpecWorkspacesInnerProjectedSourcesInnerDownwardAPI>() {
           @Override
           public void write(JsonWriter out, V1PipelineRunSpecWorkspacesInnerProjectedSourcesInnerDownwardAPI value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public V1PipelineRunSpecWorkspacesInnerProjectedSourcesInnerDownwardAPI read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of V1PipelineRunSpecWorkspacesInnerProjectedSourcesInnerDownwardAPI given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of V1PipelineRunSpecWorkspacesInnerProjectedSourcesInnerDownwardAPI
  * @throws IOException if the JSON string is invalid with respect to V1PipelineRunSpecWorkspacesInnerProjectedSourcesInnerDownwardAPI
  */
  public static V1PipelineRunSpecWorkspacesInnerProjectedSourcesInnerDownwardAPI fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, V1PipelineRunSpecWorkspacesInnerProjectedSourcesInnerDownwardAPI.class);
  }

 /**
  * Convert an instance of V1PipelineRunSpecWorkspacesInnerProjectedSourcesInnerDownwardAPI to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

