/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.25.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package net.statemesh.k8s.crd.tekton.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import net.statemesh.k8s.crd.tekton.models.V1TaskRunStatusSidecarsInnerRunning;
import net.statemesh.k8s.crd.tekton.models.V1TaskRunStatusSidecarsInnerTerminated;
import net.statemesh.k8s.crd.tekton.models.V1TaskRunStatusSidecarsInnerWaiting;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import io.kubernetes.client.openapi.JSON;

/**
 * SidecarState reports the results of running a sidecar in a Task.
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-10-01T09:42:24.724862Z[Etc/UTC]")
public class V1TaskRunStatusSidecarsInner {
  public static final String SERIALIZED_NAME_CONTAINER = "container";
  @SerializedName(SERIALIZED_NAME_CONTAINER)
  private String container;

  public static final String SERIALIZED_NAME_IMAGE_I_D = "imageID";
  @SerializedName(SERIALIZED_NAME_IMAGE_I_D)
  private String imageID;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_RUNNING = "running";
  @SerializedName(SERIALIZED_NAME_RUNNING)
  private V1TaskRunStatusSidecarsInnerRunning running;

  public static final String SERIALIZED_NAME_TERMINATED = "terminated";
  @SerializedName(SERIALIZED_NAME_TERMINATED)
  private V1TaskRunStatusSidecarsInnerTerminated terminated;

  public static final String SERIALIZED_NAME_WAITING = "waiting";
  @SerializedName(SERIALIZED_NAME_WAITING)
  private V1TaskRunStatusSidecarsInnerWaiting waiting;

  public V1TaskRunStatusSidecarsInner() {
  }

  public V1TaskRunStatusSidecarsInner container(String container) {
    
    this.container = container;
    return this;
  }

   /**
   * Get container
   * @return container
  **/
  @jakarta.annotation.Nullable
  public String getContainer() {
    return container;
  }


  public void setContainer(String container) {
    this.container = container;
  }


  public V1TaskRunStatusSidecarsInner imageID(String imageID) {
    
    this.imageID = imageID;
    return this;
  }

   /**
   * Get imageID
   * @return imageID
  **/
  @jakarta.annotation.Nullable
  public String getImageID() {
    return imageID;
  }


  public void setImageID(String imageID) {
    this.imageID = imageID;
  }


  public V1TaskRunStatusSidecarsInner name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @jakarta.annotation.Nullable
  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public V1TaskRunStatusSidecarsInner running(V1TaskRunStatusSidecarsInnerRunning running) {
    
    this.running = running;
    return this;
  }

   /**
   * Get running
   * @return running
  **/
  @jakarta.annotation.Nullable
  public V1TaskRunStatusSidecarsInnerRunning getRunning() {
    return running;
  }


  public void setRunning(V1TaskRunStatusSidecarsInnerRunning running) {
    this.running = running;
  }


  public V1TaskRunStatusSidecarsInner terminated(V1TaskRunStatusSidecarsInnerTerminated terminated) {
    
    this.terminated = terminated;
    return this;
  }

   /**
   * Get terminated
   * @return terminated
  **/
  @jakarta.annotation.Nullable
  public V1TaskRunStatusSidecarsInnerTerminated getTerminated() {
    return terminated;
  }


  public void setTerminated(V1TaskRunStatusSidecarsInnerTerminated terminated) {
    this.terminated = terminated;
  }


  public V1TaskRunStatusSidecarsInner waiting(V1TaskRunStatusSidecarsInnerWaiting waiting) {
    
    this.waiting = waiting;
    return this;
  }

   /**
   * Get waiting
   * @return waiting
  **/
  @jakarta.annotation.Nullable
  public V1TaskRunStatusSidecarsInnerWaiting getWaiting() {
    return waiting;
  }


  public void setWaiting(V1TaskRunStatusSidecarsInnerWaiting waiting) {
    this.waiting = waiting;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1TaskRunStatusSidecarsInner v1TaskRunStatusSidecarsInner = (V1TaskRunStatusSidecarsInner) o;
    return Objects.equals(this.container, v1TaskRunStatusSidecarsInner.container) &&
        Objects.equals(this.imageID, v1TaskRunStatusSidecarsInner.imageID) &&
        Objects.equals(this.name, v1TaskRunStatusSidecarsInner.name) &&
        Objects.equals(this.running, v1TaskRunStatusSidecarsInner.running) &&
        Objects.equals(this.terminated, v1TaskRunStatusSidecarsInner.terminated) &&
        Objects.equals(this.waiting, v1TaskRunStatusSidecarsInner.waiting);
  }

  @Override
  public int hashCode() {
    return Objects.hash(container, imageID, name, running, terminated, waiting);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1TaskRunStatusSidecarsInner {\n");
    sb.append("    container: ").append(toIndentedString(container)).append("\n");
    sb.append("    imageID: ").append(toIndentedString(imageID)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    running: ").append(toIndentedString(running)).append("\n");
    sb.append("    terminated: ").append(toIndentedString(terminated)).append("\n");
    sb.append("    waiting: ").append(toIndentedString(waiting)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("container");
    openapiFields.add("imageID");
    openapiFields.add("name");
    openapiFields.add("running");
    openapiFields.add("terminated");
    openapiFields.add("waiting");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to V1TaskRunStatusSidecarsInner
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!V1TaskRunStatusSidecarsInner.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in V1TaskRunStatusSidecarsInner is not found in the empty JSON string", V1TaskRunStatusSidecarsInner.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!V1TaskRunStatusSidecarsInner.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `V1TaskRunStatusSidecarsInner` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }
      if ((jsonObj.get("container") != null && !jsonObj.get("container").isJsonNull()) && !jsonObj.get("container").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `container` to be a primitive type in the JSON string but got `%s`", jsonObj.get("container").toString()));
      }
      if ((jsonObj.get("imageID") != null && !jsonObj.get("imageID").isJsonNull()) && !jsonObj.get("imageID").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `imageID` to be a primitive type in the JSON string but got `%s`", jsonObj.get("imageID").toString()));
      }
      if ((jsonObj.get("name") != null && !jsonObj.get("name").isJsonNull()) && !jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      // validate the optional field `running`
      if (jsonObj.get("running") != null && !jsonObj.get("running").isJsonNull()) {
        V1TaskRunStatusSidecarsInnerRunning.validateJsonObject(jsonObj.getAsJsonObject("running"));
      }
      // validate the optional field `terminated`
      if (jsonObj.get("terminated") != null && !jsonObj.get("terminated").isJsonNull()) {
        V1TaskRunStatusSidecarsInnerTerminated.validateJsonObject(jsonObj.getAsJsonObject("terminated"));
      }
      // validate the optional field `waiting`
      if (jsonObj.get("waiting") != null && !jsonObj.get("waiting").isJsonNull()) {
        V1TaskRunStatusSidecarsInnerWaiting.validateJsonObject(jsonObj.getAsJsonObject("waiting"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!V1TaskRunStatusSidecarsInner.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'V1TaskRunStatusSidecarsInner' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<V1TaskRunStatusSidecarsInner> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(V1TaskRunStatusSidecarsInner.class));

       return (TypeAdapter<T>) new TypeAdapter<V1TaskRunStatusSidecarsInner>() {
           @Override
           public void write(JsonWriter out, V1TaskRunStatusSidecarsInner value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public V1TaskRunStatusSidecarsInner read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of V1TaskRunStatusSidecarsInner given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of V1TaskRunStatusSidecarsInner
  * @throws IOException if the JSON string is invalid with respect to V1TaskRunStatusSidecarsInner
  */
  public static V1TaskRunStatusSidecarsInner fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, V1TaskRunStatusSidecarsInner.class);
  }

 /**
  * Convert an instance of V1TaskRunStatusSidecarsInner to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

