/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.25.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package net.statemesh.k8s.crd.tekton.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import net.statemesh.k8s.crd.tekton.models.V1TaskRunStatusTaskSpecSidecarsInnerLifecyclePostStartExec;
import net.statemesh.k8s.crd.tekton.models.V1TaskRunStatusTaskSpecSidecarsInnerLifecyclePostStartHttpGet;
import net.statemesh.k8s.crd.tekton.models.V1TaskRunStatusTaskSpecSidecarsInnerLifecyclePostStartSleep;
import net.statemesh.k8s.crd.tekton.models.V1TaskRunStatusTaskSpecSidecarsInnerLifecyclePostStartTcpSocket;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import io.kubernetes.client.openapi.JSON;

/**
 * PostStart is called immediately after a container is created. If the handler fails, the container is terminated and restarted according to its restart policy. Other management of the container blocks until the hook completes. More info: https://kubernetes.io/docs/concepts/containers/container-lifecycle-hooks/#container-hooks
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-10-01T05:56:00.153359Z[Etc/UTC]")
public class V1TaskRunStatusTaskSpecSidecarsInnerLifecyclePostStart {
  public static final String SERIALIZED_NAME_EXEC = "exec";
  @SerializedName(SERIALIZED_NAME_EXEC)
  private V1TaskRunStatusTaskSpecSidecarsInnerLifecyclePostStartExec exec;

  public static final String SERIALIZED_NAME_HTTP_GET = "httpGet";
  @SerializedName(SERIALIZED_NAME_HTTP_GET)
  private V1TaskRunStatusTaskSpecSidecarsInnerLifecyclePostStartHttpGet httpGet;

  public static final String SERIALIZED_NAME_SLEEP = "sleep";
  @SerializedName(SERIALIZED_NAME_SLEEP)
  private V1TaskRunStatusTaskSpecSidecarsInnerLifecyclePostStartSleep sleep;

  public static final String SERIALIZED_NAME_TCP_SOCKET = "tcpSocket";
  @SerializedName(SERIALIZED_NAME_TCP_SOCKET)
  private V1TaskRunStatusTaskSpecSidecarsInnerLifecyclePostStartTcpSocket tcpSocket;

  public V1TaskRunStatusTaskSpecSidecarsInnerLifecyclePostStart() {
  }

  public V1TaskRunStatusTaskSpecSidecarsInnerLifecyclePostStart exec(V1TaskRunStatusTaskSpecSidecarsInnerLifecyclePostStartExec exec) {
    
    this.exec = exec;
    return this;
  }

   /**
   * Get exec
   * @return exec
  **/
  @jakarta.annotation.Nullable
  public V1TaskRunStatusTaskSpecSidecarsInnerLifecyclePostStartExec getExec() {
    return exec;
  }


  public void setExec(V1TaskRunStatusTaskSpecSidecarsInnerLifecyclePostStartExec exec) {
    this.exec = exec;
  }


  public V1TaskRunStatusTaskSpecSidecarsInnerLifecyclePostStart httpGet(V1TaskRunStatusTaskSpecSidecarsInnerLifecyclePostStartHttpGet httpGet) {
    
    this.httpGet = httpGet;
    return this;
  }

   /**
   * Get httpGet
   * @return httpGet
  **/
  @jakarta.annotation.Nullable
  public V1TaskRunStatusTaskSpecSidecarsInnerLifecyclePostStartHttpGet getHttpGet() {
    return httpGet;
  }


  public void setHttpGet(V1TaskRunStatusTaskSpecSidecarsInnerLifecyclePostStartHttpGet httpGet) {
    this.httpGet = httpGet;
  }


  public V1TaskRunStatusTaskSpecSidecarsInnerLifecyclePostStart sleep(V1TaskRunStatusTaskSpecSidecarsInnerLifecyclePostStartSleep sleep) {
    
    this.sleep = sleep;
    return this;
  }

   /**
   * Get sleep
   * @return sleep
  **/
  @jakarta.annotation.Nullable
  public V1TaskRunStatusTaskSpecSidecarsInnerLifecyclePostStartSleep getSleep() {
    return sleep;
  }


  public void setSleep(V1TaskRunStatusTaskSpecSidecarsInnerLifecyclePostStartSleep sleep) {
    this.sleep = sleep;
  }


  public V1TaskRunStatusTaskSpecSidecarsInnerLifecyclePostStart tcpSocket(V1TaskRunStatusTaskSpecSidecarsInnerLifecyclePostStartTcpSocket tcpSocket) {
    
    this.tcpSocket = tcpSocket;
    return this;
  }

   /**
   * Get tcpSocket
   * @return tcpSocket
  **/
  @jakarta.annotation.Nullable
  public V1TaskRunStatusTaskSpecSidecarsInnerLifecyclePostStartTcpSocket getTcpSocket() {
    return tcpSocket;
  }


  public void setTcpSocket(V1TaskRunStatusTaskSpecSidecarsInnerLifecyclePostStartTcpSocket tcpSocket) {
    this.tcpSocket = tcpSocket;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1TaskRunStatusTaskSpecSidecarsInnerLifecyclePostStart v1TaskRunStatusTaskSpecSidecarsInnerLifecyclePostStart = (V1TaskRunStatusTaskSpecSidecarsInnerLifecyclePostStart) o;
    return Objects.equals(this.exec, v1TaskRunStatusTaskSpecSidecarsInnerLifecyclePostStart.exec) &&
        Objects.equals(this.httpGet, v1TaskRunStatusTaskSpecSidecarsInnerLifecyclePostStart.httpGet) &&
        Objects.equals(this.sleep, v1TaskRunStatusTaskSpecSidecarsInnerLifecyclePostStart.sleep) &&
        Objects.equals(this.tcpSocket, v1TaskRunStatusTaskSpecSidecarsInnerLifecyclePostStart.tcpSocket);
  }

  @Override
  public int hashCode() {
    return Objects.hash(exec, httpGet, sleep, tcpSocket);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1TaskRunStatusTaskSpecSidecarsInnerLifecyclePostStart {\n");
    sb.append("    exec: ").append(toIndentedString(exec)).append("\n");
    sb.append("    httpGet: ").append(toIndentedString(httpGet)).append("\n");
    sb.append("    sleep: ").append(toIndentedString(sleep)).append("\n");
    sb.append("    tcpSocket: ").append(toIndentedString(tcpSocket)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("exec");
    openapiFields.add("httpGet");
    openapiFields.add("sleep");
    openapiFields.add("tcpSocket");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to V1TaskRunStatusTaskSpecSidecarsInnerLifecyclePostStart
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!V1TaskRunStatusTaskSpecSidecarsInnerLifecyclePostStart.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in V1TaskRunStatusTaskSpecSidecarsInnerLifecyclePostStart is not found in the empty JSON string", V1TaskRunStatusTaskSpecSidecarsInnerLifecyclePostStart.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!V1TaskRunStatusTaskSpecSidecarsInnerLifecyclePostStart.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `V1TaskRunStatusTaskSpecSidecarsInnerLifecyclePostStart` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }
      // validate the optional field `exec`
      if (jsonObj.get("exec") != null && !jsonObj.get("exec").isJsonNull()) {
        V1TaskRunStatusTaskSpecSidecarsInnerLifecyclePostStartExec.validateJsonObject(jsonObj.getAsJsonObject("exec"));
      }
      // validate the optional field `httpGet`
      if (jsonObj.get("httpGet") != null && !jsonObj.get("httpGet").isJsonNull()) {
        V1TaskRunStatusTaskSpecSidecarsInnerLifecyclePostStartHttpGet.validateJsonObject(jsonObj.getAsJsonObject("httpGet"));
      }
      // validate the optional field `sleep`
      if (jsonObj.get("sleep") != null && !jsonObj.get("sleep").isJsonNull()) {
        V1TaskRunStatusTaskSpecSidecarsInnerLifecyclePostStartSleep.validateJsonObject(jsonObj.getAsJsonObject("sleep"));
      }
      // validate the optional field `tcpSocket`
      if (jsonObj.get("tcpSocket") != null && !jsonObj.get("tcpSocket").isJsonNull()) {
        V1TaskRunStatusTaskSpecSidecarsInnerLifecyclePostStartTcpSocket.validateJsonObject(jsonObj.getAsJsonObject("tcpSocket"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!V1TaskRunStatusTaskSpecSidecarsInnerLifecyclePostStart.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'V1TaskRunStatusTaskSpecSidecarsInnerLifecyclePostStart' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<V1TaskRunStatusTaskSpecSidecarsInnerLifecyclePostStart> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(V1TaskRunStatusTaskSpecSidecarsInnerLifecyclePostStart.class));

       return (TypeAdapter<T>) new TypeAdapter<V1TaskRunStatusTaskSpecSidecarsInnerLifecyclePostStart>() {
           @Override
           public void write(JsonWriter out, V1TaskRunStatusTaskSpecSidecarsInnerLifecyclePostStart value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public V1TaskRunStatusTaskSpecSidecarsInnerLifecyclePostStart read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of V1TaskRunStatusTaskSpecSidecarsInnerLifecyclePostStart given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of V1TaskRunStatusTaskSpecSidecarsInnerLifecyclePostStart
  * @throws IOException if the JSON string is invalid with respect to V1TaskRunStatusTaskSpecSidecarsInnerLifecyclePostStart
  */
  public static V1TaskRunStatusTaskSpecSidecarsInnerLifecyclePostStart fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, V1TaskRunStatusTaskSpecSidecarsInnerLifecyclePostStart.class);
  }

 /**
  * Convert an instance of V1TaskRunStatusTaskSpecSidecarsInnerLifecyclePostStart to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

