/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.25.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package net.statemesh.k8s.crd.tekton.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import net.statemesh.k8s.crd.tekton.models.V1PipelineRunSpecParamsInner;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import io.kubernetes.client.openapi.JSON;

/**
 * Contains the reference to an existing StepAction.
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-10-01T05:56:00.153359Z[Etc/UTC]")
public class V1TaskRunStatusTaskSpecStepsInnerRef {
  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_PARAMS = "params";
  @SerializedName(SERIALIZED_NAME_PARAMS)
  private List<V1PipelineRunSpecParamsInner> params;

  public static final String SERIALIZED_NAME_RESOLVER = "resolver";
  @SerializedName(SERIALIZED_NAME_RESOLVER)
  private String resolver;

  public V1TaskRunStatusTaskSpecStepsInnerRef() {
  }

  public V1TaskRunStatusTaskSpecStepsInnerRef name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Name of the referenced step
   * @return name
  **/
  @jakarta.annotation.Nullable
  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public V1TaskRunStatusTaskSpecStepsInnerRef params(List<V1PipelineRunSpecParamsInner> params) {
    
    this.params = params;
    return this;
  }

  public V1TaskRunStatusTaskSpecStepsInnerRef addParamsItem(V1PipelineRunSpecParamsInner paramsItem) {
    if (this.params == null) {
      this.params = new ArrayList<>();
    }
    this.params.add(paramsItem);
    return this;
  }

   /**
   * Params contains the parameters used to identify the referenced Tekton resource. Example entries might include \&quot;repo\&quot; or \&quot;path\&quot; but the set of params ultimately depends on the chosen resolver.
   * @return params
  **/
  @jakarta.annotation.Nullable
  public List<V1PipelineRunSpecParamsInner> getParams() {
    return params;
  }


  public void setParams(List<V1PipelineRunSpecParamsInner> params) {
    this.params = params;
  }


  public V1TaskRunStatusTaskSpecStepsInnerRef resolver(String resolver) {
    
    this.resolver = resolver;
    return this;
  }

   /**
   * Resolver is the name of the resolver that should perform resolution of the referenced Tekton resource, such as \&quot;git\&quot;.
   * @return resolver
  **/
  @jakarta.annotation.Nullable
  public String getResolver() {
    return resolver;
  }


  public void setResolver(String resolver) {
    this.resolver = resolver;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1TaskRunStatusTaskSpecStepsInnerRef v1TaskRunStatusTaskSpecStepsInnerRef = (V1TaskRunStatusTaskSpecStepsInnerRef) o;
    return Objects.equals(this.name, v1TaskRunStatusTaskSpecStepsInnerRef.name) &&
        Objects.equals(this.params, v1TaskRunStatusTaskSpecStepsInnerRef.params) &&
        Objects.equals(this.resolver, v1TaskRunStatusTaskSpecStepsInnerRef.resolver);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, params, resolver);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1TaskRunStatusTaskSpecStepsInnerRef {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    params: ").append(toIndentedString(params)).append("\n");
    sb.append("    resolver: ").append(toIndentedString(resolver)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("name");
    openapiFields.add("params");
    openapiFields.add("resolver");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to V1TaskRunStatusTaskSpecStepsInnerRef
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!V1TaskRunStatusTaskSpecStepsInnerRef.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in V1TaskRunStatusTaskSpecStepsInnerRef is not found in the empty JSON string", V1TaskRunStatusTaskSpecStepsInnerRef.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!V1TaskRunStatusTaskSpecStepsInnerRef.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `V1TaskRunStatusTaskSpecStepsInnerRef` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }
      if ((jsonObj.get("name") != null && !jsonObj.get("name").isJsonNull()) && !jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      if (jsonObj.get("params") != null && !jsonObj.get("params").isJsonNull()) {
        JsonArray jsonArrayparams = jsonObj.getAsJsonArray("params");
        if (jsonArrayparams != null) {
          // ensure the json data is an array
          if (!jsonObj.get("params").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `params` to be an array in the JSON string but got `%s`", jsonObj.get("params").toString()));
          }

          // validate the optional field `params` (array)
          for (int i = 0; i < jsonArrayparams.size(); i++) {
            V1PipelineRunSpecParamsInner.validateJsonObject(jsonArrayparams.get(i).getAsJsonObject());
          };
        }
      }
      if ((jsonObj.get("resolver") != null && !jsonObj.get("resolver").isJsonNull()) && !jsonObj.get("resolver").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `resolver` to be a primitive type in the JSON string but got `%s`", jsonObj.get("resolver").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!V1TaskRunStatusTaskSpecStepsInnerRef.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'V1TaskRunStatusTaskSpecStepsInnerRef' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<V1TaskRunStatusTaskSpecStepsInnerRef> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(V1TaskRunStatusTaskSpecStepsInnerRef.class));

       return (TypeAdapter<T>) new TypeAdapter<V1TaskRunStatusTaskSpecStepsInnerRef>() {
           @Override
           public void write(JsonWriter out, V1TaskRunStatusTaskSpecStepsInnerRef value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public V1TaskRunStatusTaskSpecStepsInnerRef read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of V1TaskRunStatusTaskSpecStepsInnerRef given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of V1TaskRunStatusTaskSpecStepsInnerRef
  * @throws IOException if the JSON string is invalid with respect to V1TaskRunStatusTaskSpecStepsInnerRef
  */
  public static V1TaskRunStatusTaskSpecStepsInnerRef fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, V1TaskRunStatusTaskSpecStepsInnerRef.class);
  }

 /**
  * Convert an instance of V1TaskRunStatusTaskSpecStepsInnerRef to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

