/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.25.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package net.statemesh.k8s.crd.tekton.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import io.kubernetes.client.openapi.JSON;

/**
 * ArtifactValue represents a specific value or data element within an Artifact.
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-10-01T09:42:24.724862Z[Etc/UTC]")
public class V1TaskRunStatusArtifactsInputsInnerValuesInner {
  public static final String SERIALIZED_NAME_DIGEST = "digest";
  @SerializedName(SERIALIZED_NAME_DIGEST)
  private Map<String, String> digest = new HashMap<>();

  public static final String SERIALIZED_NAME_URI = "uri";
  @SerializedName(SERIALIZED_NAME_URI)
  private String uri;

  public V1TaskRunStatusArtifactsInputsInnerValuesInner() {
  }

  public V1TaskRunStatusArtifactsInputsInnerValuesInner digest(Map<String, String> digest) {
    
    this.digest = digest;
    return this;
  }

  public V1TaskRunStatusArtifactsInputsInnerValuesInner putDigestItem(String key, String digestItem) {
    if (this.digest == null) {
      this.digest = new HashMap<>();
    }
    this.digest.put(key, digestItem);
    return this;
  }

   /**
   * Get digest
   * @return digest
  **/
  @jakarta.annotation.Nullable
  public Map<String, String> getDigest() {
    return digest;
  }


  public void setDigest(Map<String, String> digest) {
    this.digest = digest;
  }


  public V1TaskRunStatusArtifactsInputsInnerValuesInner uri(String uri) {
    
    this.uri = uri;
    return this;
  }

   /**
   * Get uri
   * @return uri
  **/
  @jakarta.annotation.Nullable
  public String getUri() {
    return uri;
  }


  public void setUri(String uri) {
    this.uri = uri;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1TaskRunStatusArtifactsInputsInnerValuesInner v1TaskRunStatusArtifactsInputsInnerValuesInner = (V1TaskRunStatusArtifactsInputsInnerValuesInner) o;
    return Objects.equals(this.digest, v1TaskRunStatusArtifactsInputsInnerValuesInner.digest) &&
        Objects.equals(this.uri, v1TaskRunStatusArtifactsInputsInnerValuesInner.uri);
  }

  @Override
  public int hashCode() {
    return Objects.hash(digest, uri);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1TaskRunStatusArtifactsInputsInnerValuesInner {\n");
    sb.append("    digest: ").append(toIndentedString(digest)).append("\n");
    sb.append("    uri: ").append(toIndentedString(uri)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("digest");
    openapiFields.add("uri");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to V1TaskRunStatusArtifactsInputsInnerValuesInner
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!V1TaskRunStatusArtifactsInputsInnerValuesInner.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in V1TaskRunStatusArtifactsInputsInnerValuesInner is not found in the empty JSON string", V1TaskRunStatusArtifactsInputsInnerValuesInner.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!V1TaskRunStatusArtifactsInputsInnerValuesInner.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `V1TaskRunStatusArtifactsInputsInnerValuesInner` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }
      if ((jsonObj.get("uri") != null && !jsonObj.get("uri").isJsonNull()) && !jsonObj.get("uri").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `uri` to be a primitive type in the JSON string but got `%s`", jsonObj.get("uri").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!V1TaskRunStatusArtifactsInputsInnerValuesInner.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'V1TaskRunStatusArtifactsInputsInnerValuesInner' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<V1TaskRunStatusArtifactsInputsInnerValuesInner> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(V1TaskRunStatusArtifactsInputsInnerValuesInner.class));

       return (TypeAdapter<T>) new TypeAdapter<V1TaskRunStatusArtifactsInputsInnerValuesInner>() {
           @Override
           public void write(JsonWriter out, V1TaskRunStatusArtifactsInputsInnerValuesInner value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public V1TaskRunStatusArtifactsInputsInnerValuesInner read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of V1TaskRunStatusArtifactsInputsInnerValuesInner given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of V1TaskRunStatusArtifactsInputsInnerValuesInner
  * @throws IOException if the JSON string is invalid with respect to V1TaskRunStatusArtifactsInputsInnerValuesInner
  */
  public static V1TaskRunStatusArtifactsInputsInnerValuesInner fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, V1TaskRunStatusArtifactsInputsInnerValuesInner.class);
  }

 /**
  * Convert an instance of V1TaskRunStatusArtifactsInputsInnerValuesInner to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

