/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package net.statemesh.k8s.crd.traefik.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Domain holds a domain name with SANs.
 */
@ApiModel(description = "Domain holds a domain name with SANs.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-01-10T04:21:57.451Z[Etc/UTC]")
public class V1alpha1IngressRouteSpecTlsDomains {
  public static final String SERIALIZED_NAME_MAIN = "main";
  @SerializedName(SERIALIZED_NAME_MAIN)
  private String main;

  public static final String SERIALIZED_NAME_SANS = "sans";
  @SerializedName(SERIALIZED_NAME_SANS)
  private List<String> sans = null;


  public V1alpha1IngressRouteSpecTlsDomains main(String main) {
    
    this.main = main;
    return this;
  }

   /**
   * Main defines the main domain name.
   * @return main
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Main defines the main domain name.")

  public String getMain() {
    return main;
  }


  public void setMain(String main) {
    this.main = main;
  }


  public V1alpha1IngressRouteSpecTlsDomains sans(List<String> sans) {
    
    this.sans = sans;
    return this;
  }

  public V1alpha1IngressRouteSpecTlsDomains addSansItem(String sansItem) {
    if (this.sans == null) {
      this.sans = new ArrayList<>();
    }
    this.sans.add(sansItem);
    return this;
  }

   /**
   * SANs defines the subject alternative domain names.
   * @return sans
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "SANs defines the subject alternative domain names.")

  public List<String> getSans() {
    return sans;
  }


  public void setSans(List<String> sans) {
    this.sans = sans;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha1IngressRouteSpecTlsDomains v1alpha1IngressRouteSpecTlsDomains = (V1alpha1IngressRouteSpecTlsDomains) o;
    return Objects.equals(this.main, v1alpha1IngressRouteSpecTlsDomains.main) &&
        Objects.equals(this.sans, v1alpha1IngressRouteSpecTlsDomains.sans);
  }

  @Override
  public int hashCode() {
    return Objects.hash(main, sans);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha1IngressRouteSpecTlsDomains {\n");
    sb.append("    main: ").append(toIndentedString(main)).append("\n");
    sb.append("    sans: ").append(toIndentedString(sans)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

