/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package net.statemesh.k8s.crd.traefik.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Subject defines the client certificate subject details to add to the X-Forwarded-Tls-Client-Cert-Info header.
 */
@ApiModel(description = "Subject defines the client certificate subject details to add to the X-Forwarded-Tls-Client-Cert-Info header.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-01-10T04:21:57.451Z[Etc/UTC]")
public class V1alpha1MiddlewareSpecPassTLSClientCertInfoSubject {
  public static final String SERIALIZED_NAME_COMMON_NAME = "commonName";
  @SerializedName(SERIALIZED_NAME_COMMON_NAME)
  private Boolean commonName;

  public static final String SERIALIZED_NAME_COUNTRY = "country";
  @SerializedName(SERIALIZED_NAME_COUNTRY)
  private Boolean country;

  public static final String SERIALIZED_NAME_DOMAIN_COMPONENT = "domainComponent";
  @SerializedName(SERIALIZED_NAME_DOMAIN_COMPONENT)
  private Boolean domainComponent;

  public static final String SERIALIZED_NAME_LOCALITY = "locality";
  @SerializedName(SERIALIZED_NAME_LOCALITY)
  private Boolean locality;

  public static final String SERIALIZED_NAME_ORGANIZATION = "organization";
  @SerializedName(SERIALIZED_NAME_ORGANIZATION)
  private Boolean organization;

  public static final String SERIALIZED_NAME_ORGANIZATIONAL_UNIT = "organizationalUnit";
  @SerializedName(SERIALIZED_NAME_ORGANIZATIONAL_UNIT)
  private Boolean organizationalUnit;

  public static final String SERIALIZED_NAME_PROVINCE = "province";
  @SerializedName(SERIALIZED_NAME_PROVINCE)
  private Boolean province;

  public static final String SERIALIZED_NAME_SERIAL_NUMBER = "serialNumber";
  @SerializedName(SERIALIZED_NAME_SERIAL_NUMBER)
  private Boolean serialNumber;


  public V1alpha1MiddlewareSpecPassTLSClientCertInfoSubject commonName(Boolean commonName) {
    
    this.commonName = commonName;
    return this;
  }

   /**
   * CommonName defines whether to add the organizationalUnit information into the subject.
   * @return commonName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "CommonName defines whether to add the organizationalUnit information into the subject.")

  public Boolean getCommonName() {
    return commonName;
  }


  public void setCommonName(Boolean commonName) {
    this.commonName = commonName;
  }


  public V1alpha1MiddlewareSpecPassTLSClientCertInfoSubject country(Boolean country) {
    
    this.country = country;
    return this;
  }

   /**
   * Country defines whether to add the country information into the subject.
   * @return country
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Country defines whether to add the country information into the subject.")

  public Boolean getCountry() {
    return country;
  }


  public void setCountry(Boolean country) {
    this.country = country;
  }


  public V1alpha1MiddlewareSpecPassTLSClientCertInfoSubject domainComponent(Boolean domainComponent) {
    
    this.domainComponent = domainComponent;
    return this;
  }

   /**
   * DomainComponent defines whether to add the domainComponent information into the subject.
   * @return domainComponent
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "DomainComponent defines whether to add the domainComponent information into the subject.")

  public Boolean getDomainComponent() {
    return domainComponent;
  }


  public void setDomainComponent(Boolean domainComponent) {
    this.domainComponent = domainComponent;
  }


  public V1alpha1MiddlewareSpecPassTLSClientCertInfoSubject locality(Boolean locality) {
    
    this.locality = locality;
    return this;
  }

   /**
   * Locality defines whether to add the locality information into the subject.
   * @return locality
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Locality defines whether to add the locality information into the subject.")

  public Boolean getLocality() {
    return locality;
  }


  public void setLocality(Boolean locality) {
    this.locality = locality;
  }


  public V1alpha1MiddlewareSpecPassTLSClientCertInfoSubject organization(Boolean organization) {
    
    this.organization = organization;
    return this;
  }

   /**
   * Organization defines whether to add the organization information into the subject.
   * @return organization
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Organization defines whether to add the organization information into the subject.")

  public Boolean getOrganization() {
    return organization;
  }


  public void setOrganization(Boolean organization) {
    this.organization = organization;
  }


  public V1alpha1MiddlewareSpecPassTLSClientCertInfoSubject organizationalUnit(Boolean organizationalUnit) {
    
    this.organizationalUnit = organizationalUnit;
    return this;
  }

   /**
   * OrganizationalUnit defines whether to add the organizationalUnit information into the subject.
   * @return organizationalUnit
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "OrganizationalUnit defines whether to add the organizationalUnit information into the subject.")

  public Boolean getOrganizationalUnit() {
    return organizationalUnit;
  }


  public void setOrganizationalUnit(Boolean organizationalUnit) {
    this.organizationalUnit = organizationalUnit;
  }


  public V1alpha1MiddlewareSpecPassTLSClientCertInfoSubject province(Boolean province) {
    
    this.province = province;
    return this;
  }

   /**
   * Province defines whether to add the province information into the subject.
   * @return province
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Province defines whether to add the province information into the subject.")

  public Boolean getProvince() {
    return province;
  }


  public void setProvince(Boolean province) {
    this.province = province;
  }


  public V1alpha1MiddlewareSpecPassTLSClientCertInfoSubject serialNumber(Boolean serialNumber) {
    
    this.serialNumber = serialNumber;
    return this;
  }

   /**
   * SerialNumber defines whether to add the serialNumber information into the subject.
   * @return serialNumber
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "SerialNumber defines whether to add the serialNumber information into the subject.")

  public Boolean getSerialNumber() {
    return serialNumber;
  }


  public void setSerialNumber(Boolean serialNumber) {
    this.serialNumber = serialNumber;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha1MiddlewareSpecPassTLSClientCertInfoSubject v1alpha1MiddlewareSpecPassTLSClientCertInfoSubject = (V1alpha1MiddlewareSpecPassTLSClientCertInfoSubject) o;
    return Objects.equals(this.commonName, v1alpha1MiddlewareSpecPassTLSClientCertInfoSubject.commonName) &&
        Objects.equals(this.country, v1alpha1MiddlewareSpecPassTLSClientCertInfoSubject.country) &&
        Objects.equals(this.domainComponent, v1alpha1MiddlewareSpecPassTLSClientCertInfoSubject.domainComponent) &&
        Objects.equals(this.locality, v1alpha1MiddlewareSpecPassTLSClientCertInfoSubject.locality) &&
        Objects.equals(this.organization, v1alpha1MiddlewareSpecPassTLSClientCertInfoSubject.organization) &&
        Objects.equals(this.organizationalUnit, v1alpha1MiddlewareSpecPassTLSClientCertInfoSubject.organizationalUnit) &&
        Objects.equals(this.province, v1alpha1MiddlewareSpecPassTLSClientCertInfoSubject.province) &&
        Objects.equals(this.serialNumber, v1alpha1MiddlewareSpecPassTLSClientCertInfoSubject.serialNumber);
  }

  @Override
  public int hashCode() {
    return Objects.hash(commonName, country, domainComponent, locality, organization, organizationalUnit, province, serialNumber);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha1MiddlewareSpecPassTLSClientCertInfoSubject {\n");
    sb.append("    commonName: ").append(toIndentedString(commonName)).append("\n");
    sb.append("    country: ").append(toIndentedString(country)).append("\n");
    sb.append("    domainComponent: ").append(toIndentedString(domainComponent)).append("\n");
    sb.append("    locality: ").append(toIndentedString(locality)).append("\n");
    sb.append("    organization: ").append(toIndentedString(organization)).append("\n");
    sb.append("    organizationalUnit: ").append(toIndentedString(organizationalUnit)).append("\n");
    sb.append("    province: ").append(toIndentedString(province)).append("\n");
    sb.append("    serialNumber: ").append(toIndentedString(serialNumber)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

