/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package net.statemesh.k8s.crd.traefik.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import net.statemesh.k8s.crd.traefik.models.V1alpha1IngressRouteTCPSpecMiddlewares;
import net.statemesh.k8s.crd.traefik.models.V1alpha1IngressRouteTCPSpecServices;

/**
 * RouteTCP holds the TCP route configuration.
 */
@ApiModel(description = "RouteTCP holds the TCP route configuration.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-01-10T04:21:57.451Z[Etc/UTC]")
public class V1alpha1IngressRouteTCPSpecRoutes {
  public static final String SERIALIZED_NAME_MATCH = "match";
  @SerializedName(SERIALIZED_NAME_MATCH)
  private String match;

  public static final String SERIALIZED_NAME_MIDDLEWARES = "middlewares";
  @SerializedName(SERIALIZED_NAME_MIDDLEWARES)
  private List<V1alpha1IngressRouteTCPSpecMiddlewares> middlewares = null;

  public static final String SERIALIZED_NAME_PRIORITY = "priority";
  @SerializedName(SERIALIZED_NAME_PRIORITY)
  private Integer priority;

  public static final String SERIALIZED_NAME_SERVICES = "services";
  @SerializedName(SERIALIZED_NAME_SERVICES)
  private List<V1alpha1IngressRouteTCPSpecServices> services = null;

  public static final String SERIALIZED_NAME_SYNTAX = "syntax";
  @SerializedName(SERIALIZED_NAME_SYNTAX)
  private String syntax;


  public V1alpha1IngressRouteTCPSpecRoutes match(String match) {
    
    this.match = match;
    return this;
  }

   /**
   * Match defines the router&#39;s rule. More info: https://doc.traefik.io/traefik/v3.3/routing/routers/#rule_1
   * @return match
  **/
  @ApiModelProperty(required = true, value = "Match defines the router's rule. More info: https://doc.traefik.io/traefik/v3.3/routing/routers/#rule_1")

  public String getMatch() {
    return match;
  }


  public void setMatch(String match) {
    this.match = match;
  }


  public V1alpha1IngressRouteTCPSpecRoutes middlewares(List<V1alpha1IngressRouteTCPSpecMiddlewares> middlewares) {
    
    this.middlewares = middlewares;
    return this;
  }

  public V1alpha1IngressRouteTCPSpecRoutes addMiddlewaresItem(V1alpha1IngressRouteTCPSpecMiddlewares middlewaresItem) {
    if (this.middlewares == null) {
      this.middlewares = new ArrayList<>();
    }
    this.middlewares.add(middlewaresItem);
    return this;
  }

   /**
   * Middlewares defines the list of references to MiddlewareTCP resources.
   * @return middlewares
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Middlewares defines the list of references to MiddlewareTCP resources.")

  public List<V1alpha1IngressRouteTCPSpecMiddlewares> getMiddlewares() {
    return middlewares;
  }


  public void setMiddlewares(List<V1alpha1IngressRouteTCPSpecMiddlewares> middlewares) {
    this.middlewares = middlewares;
  }


  public V1alpha1IngressRouteTCPSpecRoutes priority(Integer priority) {
    
    this.priority = priority;
    return this;
  }

   /**
   * Priority defines the router&#39;s priority. More info: https://doc.traefik.io/traefik/v3.3/routing/routers/#priority_1
   * @return priority
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Priority defines the router's priority. More info: https://doc.traefik.io/traefik/v3.3/routing/routers/#priority_1")

  public Integer getPriority() {
    return priority;
  }


  public void setPriority(Integer priority) {
    this.priority = priority;
  }


  public V1alpha1IngressRouteTCPSpecRoutes services(List<V1alpha1IngressRouteTCPSpecServices> services) {
    
    this.services = services;
    return this;
  }

  public V1alpha1IngressRouteTCPSpecRoutes addServicesItem(V1alpha1IngressRouteTCPSpecServices servicesItem) {
    if (this.services == null) {
      this.services = new ArrayList<>();
    }
    this.services.add(servicesItem);
    return this;
  }

   /**
   * Services defines the list of TCP services.
   * @return services
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Services defines the list of TCP services.")

  public List<V1alpha1IngressRouteTCPSpecServices> getServices() {
    return services;
  }


  public void setServices(List<V1alpha1IngressRouteTCPSpecServices> services) {
    this.services = services;
  }


  public V1alpha1IngressRouteTCPSpecRoutes syntax(String syntax) {
    
    this.syntax = syntax;
    return this;
  }

   /**
   * Syntax defines the router&#39;s rule syntax. More info: https://doc.traefik.io/traefik/v3.3/routing/routers/#rulesyntax_1
   * @return syntax
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Syntax defines the router's rule syntax. More info: https://doc.traefik.io/traefik/v3.3/routing/routers/#rulesyntax_1")

  public String getSyntax() {
    return syntax;
  }


  public void setSyntax(String syntax) {
    this.syntax = syntax;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha1IngressRouteTCPSpecRoutes v1alpha1IngressRouteTCPSpecRoutes = (V1alpha1IngressRouteTCPSpecRoutes) o;
    return Objects.equals(this.match, v1alpha1IngressRouteTCPSpecRoutes.match) &&
        Objects.equals(this.middlewares, v1alpha1IngressRouteTCPSpecRoutes.middlewares) &&
        Objects.equals(this.priority, v1alpha1IngressRouteTCPSpecRoutes.priority) &&
        Objects.equals(this.services, v1alpha1IngressRouteTCPSpecRoutes.services) &&
        Objects.equals(this.syntax, v1alpha1IngressRouteTCPSpecRoutes.syntax);
  }

  @Override
  public int hashCode() {
    return Objects.hash(match, middlewares, priority, services, syntax);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha1IngressRouteTCPSpecRoutes {\n");
    sb.append("    match: ").append(toIndentedString(match)).append("\n");
    sb.append("    middlewares: ").append(toIndentedString(middlewares)).append("\n");
    sb.append("    priority: ").append(toIndentedString(priority)).append("\n");
    sb.append("    services: ").append(toIndentedString(services)).append("\n");
    sb.append("    syntax: ").append(toIndentedString(syntax)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

