/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package net.statemesh.k8s.crd.traefik.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * IPWhiteList defines the IPWhiteList middleware configuration. This middleware accepts/refuses connections based on the client IP. Deprecated: please use IPAllowList instead. More info: https://doc.traefik.io/traefik/v3.3/middlewares/tcp/ipwhitelist/
 */
@ApiModel(description = "IPWhiteList defines the IPWhiteList middleware configuration. This middleware accepts/refuses connections based on the client IP. Deprecated: please use IPAllowList instead. More info: https://doc.traefik.io/traefik/v3.3/middlewares/tcp/ipwhitelist/")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-01-10T04:21:57.451Z[Etc/UTC]")
public class V1alpha1MiddlewareTCPSpecIpWhiteList {
  public static final String SERIALIZED_NAME_SOURCE_RANGE = "sourceRange";
  @SerializedName(SERIALIZED_NAME_SOURCE_RANGE)
  private List<String> sourceRange = null;


  public V1alpha1MiddlewareTCPSpecIpWhiteList sourceRange(List<String> sourceRange) {
    
    this.sourceRange = sourceRange;
    return this;
  }

  public V1alpha1MiddlewareTCPSpecIpWhiteList addSourceRangeItem(String sourceRangeItem) {
    if (this.sourceRange == null) {
      this.sourceRange = new ArrayList<>();
    }
    this.sourceRange.add(sourceRangeItem);
    return this;
  }

   /**
   * SourceRange defines the allowed IPs (or ranges of allowed IPs by using CIDR notation).
   * @return sourceRange
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "SourceRange defines the allowed IPs (or ranges of allowed IPs by using CIDR notation).")

  public List<String> getSourceRange() {
    return sourceRange;
  }


  public void setSourceRange(List<String> sourceRange) {
    this.sourceRange = sourceRange;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha1MiddlewareTCPSpecIpWhiteList v1alpha1MiddlewareTCPSpecIpWhiteList = (V1alpha1MiddlewareTCPSpecIpWhiteList) o;
    return Objects.equals(this.sourceRange, v1alpha1MiddlewareTCPSpecIpWhiteList.sourceRange);
  }

  @Override
  public int hashCode() {
    return Objects.hash(sourceRange);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha1MiddlewareTCPSpecIpWhiteList {\n");
    sb.append("    sourceRange: ").append(toIndentedString(sourceRange)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

