/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package net.statemesh.k8s.crd.traefik.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import net.statemesh.k8s.crd.traefik.models.V1alpha1IngressRouteTCPSpecRoutes;
import net.statemesh.k8s.crd.traefik.models.V1alpha1IngressRouteTCPSpecTls;

/**
 * IngressRouteTCPSpec defines the desired state of IngressRouteTCP.
 */
@ApiModel(description = "IngressRouteTCPSpec defines the desired state of IngressRouteTCP.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-01-10T04:21:57.451Z[Etc/UTC]")
public class V1alpha1IngressRouteTCPSpec {
  public static final String SERIALIZED_NAME_ENTRY_POINTS = "entryPoints";
  @SerializedName(SERIALIZED_NAME_ENTRY_POINTS)
  private List<String> entryPoints = null;

  public static final String SERIALIZED_NAME_ROUTES = "routes";
  @SerializedName(SERIALIZED_NAME_ROUTES)
  private List<V1alpha1IngressRouteTCPSpecRoutes> routes = new ArrayList<>();

  public static final String SERIALIZED_NAME_TLS = "tls";
  @SerializedName(SERIALIZED_NAME_TLS)
  private V1alpha1IngressRouteTCPSpecTls tls;


  public V1alpha1IngressRouteTCPSpec entryPoints(List<String> entryPoints) {
    
    this.entryPoints = entryPoints;
    return this;
  }

  public V1alpha1IngressRouteTCPSpec addEntryPointsItem(String entryPointsItem) {
    if (this.entryPoints == null) {
      this.entryPoints = new ArrayList<>();
    }
    this.entryPoints.add(entryPointsItem);
    return this;
  }

   /**
   * EntryPoints defines the list of entry point names to bind to. Entry points have to be configured in the static configuration. More info: https://doc.traefik.io/traefik/v3.3/routing/entrypoints/ Default: all.
   * @return entryPoints
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "EntryPoints defines the list of entry point names to bind to. Entry points have to be configured in the static configuration. More info: https://doc.traefik.io/traefik/v3.3/routing/entrypoints/ Default: all.")

  public List<String> getEntryPoints() {
    return entryPoints;
  }


  public void setEntryPoints(List<String> entryPoints) {
    this.entryPoints = entryPoints;
  }


  public V1alpha1IngressRouteTCPSpec routes(List<V1alpha1IngressRouteTCPSpecRoutes> routes) {
    
    this.routes = routes;
    return this;
  }

  public V1alpha1IngressRouteTCPSpec addRoutesItem(V1alpha1IngressRouteTCPSpecRoutes routesItem) {
    this.routes.add(routesItem);
    return this;
  }

   /**
   * Routes defines the list of routes.
   * @return routes
  **/
  @ApiModelProperty(required = true, value = "Routes defines the list of routes.")

  public List<V1alpha1IngressRouteTCPSpecRoutes> getRoutes() {
    return routes;
  }


  public void setRoutes(List<V1alpha1IngressRouteTCPSpecRoutes> routes) {
    this.routes = routes;
  }


  public V1alpha1IngressRouteTCPSpec tls(V1alpha1IngressRouteTCPSpecTls tls) {
    
    this.tls = tls;
    return this;
  }

   /**
   * Get tls
   * @return tls
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha1IngressRouteTCPSpecTls getTls() {
    return tls;
  }


  public void setTls(V1alpha1IngressRouteTCPSpecTls tls) {
    this.tls = tls;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha1IngressRouteTCPSpec v1alpha1IngressRouteTCPSpec = (V1alpha1IngressRouteTCPSpec) o;
    return Objects.equals(this.entryPoints, v1alpha1IngressRouteTCPSpec.entryPoints) &&
        Objects.equals(this.routes, v1alpha1IngressRouteTCPSpec.routes) &&
        Objects.equals(this.tls, v1alpha1IngressRouteTCPSpec.tls);
  }

  @Override
  public int hashCode() {
    return Objects.hash(entryPoints, routes, tls);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha1IngressRouteTCPSpec {\n");
    sb.append("    entryPoints: ").append(toIndentedString(entryPoints)).append("\n");
    sb.append("    routes: ").append(toIndentedString(routes)).append("\n");
    sb.append("    tls: ").append(toIndentedString(tls)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

