/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package net.statemesh.k8s.crd.traefik.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import net.statemesh.k8s.crd.traefik.models.V1alpha1ServersTransportTCPSpecTls;

/**
 * ServersTransportTCPSpec defines the desired state of a ServersTransportTCP.
 */
@ApiModel(description = "ServersTransportTCPSpec defines the desired state of a ServersTransportTCP.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-01-10T04:21:57.451Z[Etc/UTC]")
public class V1alpha1ServersTransportTCPSpec {
  public static final String SERIALIZED_NAME_DIAL_KEEP_ALIVE = "dialKeepAlive";
  @SerializedName(SERIALIZED_NAME_DIAL_KEEP_ALIVE)
  private Object dialKeepAlive;

  public static final String SERIALIZED_NAME_DIAL_TIMEOUT = "dialTimeout";
  @SerializedName(SERIALIZED_NAME_DIAL_TIMEOUT)
  private Object dialTimeout;

  public static final String SERIALIZED_NAME_TERMINATION_DELAY = "terminationDelay";
  @SerializedName(SERIALIZED_NAME_TERMINATION_DELAY)
  private Object terminationDelay;

  public static final String SERIALIZED_NAME_TLS = "tls";
  @SerializedName(SERIALIZED_NAME_TLS)
  private V1alpha1ServersTransportTCPSpecTls tls;


  public V1alpha1ServersTransportTCPSpec dialKeepAlive(Object dialKeepAlive) {
    
    this.dialKeepAlive = dialKeepAlive;
    return this;
  }

   /**
   * DialKeepAlive is the interval between keep-alive probes for an active network connection. If zero, keep-alive probes are sent with a default value (currently 15 seconds), if supported by the protocol and operating system. Network protocols or operating systems that do not support keep-alives ignore this field. If negative, keep-alive probes are disabled.
   * @return dialKeepAlive
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "DialKeepAlive is the interval between keep-alive probes for an active network connection. If zero, keep-alive probes are sent with a default value (currently 15 seconds), if supported by the protocol and operating system. Network protocols or operating systems that do not support keep-alives ignore this field. If negative, keep-alive probes are disabled.")

  public Object getDialKeepAlive() {
    return dialKeepAlive;
  }


  public void setDialKeepAlive(Object dialKeepAlive) {
    this.dialKeepAlive = dialKeepAlive;
  }


  public V1alpha1ServersTransportTCPSpec dialTimeout(Object dialTimeout) {
    
    this.dialTimeout = dialTimeout;
    return this;
  }

   /**
   * DialTimeout is the amount of time to wait until a connection to a backend server can be established.
   * @return dialTimeout
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "DialTimeout is the amount of time to wait until a connection to a backend server can be established.")

  public Object getDialTimeout() {
    return dialTimeout;
  }


  public void setDialTimeout(Object dialTimeout) {
    this.dialTimeout = dialTimeout;
  }


  public V1alpha1ServersTransportTCPSpec terminationDelay(Object terminationDelay) {
    
    this.terminationDelay = terminationDelay;
    return this;
  }

   /**
   * TerminationDelay defines the delay to wait before fully terminating the connection, after one connected peer has closed its writing capability.
   * @return terminationDelay
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "TerminationDelay defines the delay to wait before fully terminating the connection, after one connected peer has closed its writing capability.")

  public Object getTerminationDelay() {
    return terminationDelay;
  }


  public void setTerminationDelay(Object terminationDelay) {
    this.terminationDelay = terminationDelay;
  }


  public V1alpha1ServersTransportTCPSpec tls(V1alpha1ServersTransportTCPSpecTls tls) {
    
    this.tls = tls;
    return this;
  }

   /**
   * Get tls
   * @return tls
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha1ServersTransportTCPSpecTls getTls() {
    return tls;
  }


  public void setTls(V1alpha1ServersTransportTCPSpecTls tls) {
    this.tls = tls;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha1ServersTransportTCPSpec v1alpha1ServersTransportTCPSpec = (V1alpha1ServersTransportTCPSpec) o;
    return Objects.equals(this.dialKeepAlive, v1alpha1ServersTransportTCPSpec.dialKeepAlive) &&
        Objects.equals(this.dialTimeout, v1alpha1ServersTransportTCPSpec.dialTimeout) &&
        Objects.equals(this.terminationDelay, v1alpha1ServersTransportTCPSpec.terminationDelay) &&
        Objects.equals(this.tls, v1alpha1ServersTransportTCPSpec.tls);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dialKeepAlive, dialTimeout, terminationDelay, tls);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha1ServersTransportTCPSpec {\n");
    sb.append("    dialKeepAlive: ").append(toIndentedString(dialKeepAlive)).append("\n");
    sb.append("    dialTimeout: ").append(toIndentedString(dialTimeout)).append("\n");
    sb.append("    terminationDelay: ").append(toIndentedString(terminationDelay)).append("\n");
    sb.append("    tls: ").append(toIndentedString(tls)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

