/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.25.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package net.statemesh.k8s.crd.rayjob.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;
import net.statemesh.k8s.crd.rayjob.models.V1RayJobSpecRayClusterSpecHeadGroupSpecHeadService;
import net.statemesh.k8s.crd.rayjob.models.V1RayJobSpecRayClusterSpecHeadGroupSpecTemplate;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import io.kubernetes.client.openapi.JSON;

/**
 * V1RayJobSpecRayClusterSpecHeadGroupSpec
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-09-11T07:03:01.189516Z[Etc/UTC]")
public class V1RayJobSpecRayClusterSpecHeadGroupSpec {
  public static final String SERIALIZED_NAME_ENABLE_INGRESS = "enableIngress";
  @SerializedName(SERIALIZED_NAME_ENABLE_INGRESS)
  private Boolean enableIngress;

  public static final String SERIALIZED_NAME_HEAD_SERVICE = "headService";
  @SerializedName(SERIALIZED_NAME_HEAD_SERVICE)
  private V1RayJobSpecRayClusterSpecHeadGroupSpecHeadService headService;

  public static final String SERIALIZED_NAME_RAY_START_PARAMS = "rayStartParams";
  @SerializedName(SERIALIZED_NAME_RAY_START_PARAMS)
  private Map<String, String> rayStartParams = new HashMap<>();

  public static final String SERIALIZED_NAME_SERVICE_TYPE = "serviceType";
  @SerializedName(SERIALIZED_NAME_SERVICE_TYPE)
  private String serviceType;

  public static final String SERIALIZED_NAME_TEMPLATE = "template";
  @SerializedName(SERIALIZED_NAME_TEMPLATE)
  private V1RayJobSpecRayClusterSpecHeadGroupSpecTemplate template;

  public V1RayJobSpecRayClusterSpecHeadGroupSpec() {
  }

  public V1RayJobSpecRayClusterSpecHeadGroupSpec enableIngress(Boolean enableIngress) {
    
    this.enableIngress = enableIngress;
    return this;
  }

   /**
   * Get enableIngress
   * @return enableIngress
  **/
  @jakarta.annotation.Nullable
  public Boolean getEnableIngress() {
    return enableIngress;
  }


  public void setEnableIngress(Boolean enableIngress) {
    this.enableIngress = enableIngress;
  }


  public V1RayJobSpecRayClusterSpecHeadGroupSpec headService(V1RayJobSpecRayClusterSpecHeadGroupSpecHeadService headService) {
    
    this.headService = headService;
    return this;
  }

   /**
   * Get headService
   * @return headService
  **/
  @jakarta.annotation.Nullable
  public V1RayJobSpecRayClusterSpecHeadGroupSpecHeadService getHeadService() {
    return headService;
  }


  public void setHeadService(V1RayJobSpecRayClusterSpecHeadGroupSpecHeadService headService) {
    this.headService = headService;
  }


  public V1RayJobSpecRayClusterSpecHeadGroupSpec rayStartParams(Map<String, String> rayStartParams) {
    
    this.rayStartParams = rayStartParams;
    return this;
  }

  public V1RayJobSpecRayClusterSpecHeadGroupSpec putRayStartParamsItem(String key, String rayStartParamsItem) {
    if (this.rayStartParams == null) {
      this.rayStartParams = new HashMap<>();
    }
    this.rayStartParams.put(key, rayStartParamsItem);
    return this;
  }

   /**
   * Get rayStartParams
   * @return rayStartParams
  **/
  @jakarta.annotation.Nullable
  public Map<String, String> getRayStartParams() {
    return rayStartParams;
  }


  public void setRayStartParams(Map<String, String> rayStartParams) {
    this.rayStartParams = rayStartParams;
  }


  public V1RayJobSpecRayClusterSpecHeadGroupSpec serviceType(String serviceType) {
    
    this.serviceType = serviceType;
    return this;
  }

   /**
   * Get serviceType
   * @return serviceType
  **/
  @jakarta.annotation.Nullable
  public String getServiceType() {
    return serviceType;
  }


  public void setServiceType(String serviceType) {
    this.serviceType = serviceType;
  }


  public V1RayJobSpecRayClusterSpecHeadGroupSpec template(V1RayJobSpecRayClusterSpecHeadGroupSpecTemplate template) {
    
    this.template = template;
    return this;
  }

   /**
   * Get template
   * @return template
  **/
  @jakarta.annotation.Nonnull
  public V1RayJobSpecRayClusterSpecHeadGroupSpecTemplate getTemplate() {
    return template;
  }


  public void setTemplate(V1RayJobSpecRayClusterSpecHeadGroupSpecTemplate template) {
    this.template = template;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1RayJobSpecRayClusterSpecHeadGroupSpec v1RayJobSpecRayClusterSpecHeadGroupSpec = (V1RayJobSpecRayClusterSpecHeadGroupSpec) o;
    return Objects.equals(this.enableIngress, v1RayJobSpecRayClusterSpecHeadGroupSpec.enableIngress) &&
        Objects.equals(this.headService, v1RayJobSpecRayClusterSpecHeadGroupSpec.headService) &&
        Objects.equals(this.rayStartParams, v1RayJobSpecRayClusterSpecHeadGroupSpec.rayStartParams) &&
        Objects.equals(this.serviceType, v1RayJobSpecRayClusterSpecHeadGroupSpec.serviceType) &&
        Objects.equals(this.template, v1RayJobSpecRayClusterSpecHeadGroupSpec.template);
  }

  @Override
  public int hashCode() {
    return Objects.hash(enableIngress, headService, rayStartParams, serviceType, template);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1RayJobSpecRayClusterSpecHeadGroupSpec {\n");
    sb.append("    enableIngress: ").append(toIndentedString(enableIngress)).append("\n");
    sb.append("    headService: ").append(toIndentedString(headService)).append("\n");
    sb.append("    rayStartParams: ").append(toIndentedString(rayStartParams)).append("\n");
    sb.append("    serviceType: ").append(toIndentedString(serviceType)).append("\n");
    sb.append("    template: ").append(toIndentedString(template)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("enableIngress");
    openapiFields.add("headService");
    openapiFields.add("rayStartParams");
    openapiFields.add("serviceType");
    openapiFields.add("template");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("template");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to V1RayJobSpecRayClusterSpecHeadGroupSpec
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!V1RayJobSpecRayClusterSpecHeadGroupSpec.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in V1RayJobSpecRayClusterSpecHeadGroupSpec is not found in the empty JSON string", V1RayJobSpecRayClusterSpecHeadGroupSpec.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!V1RayJobSpecRayClusterSpecHeadGroupSpec.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `V1RayJobSpecRayClusterSpecHeadGroupSpec` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : V1RayJobSpecRayClusterSpecHeadGroupSpec.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      // validate the optional field `headService`
      if (jsonObj.get("headService") != null && !jsonObj.get("headService").isJsonNull()) {
        V1RayJobSpecRayClusterSpecHeadGroupSpecHeadService.validateJsonObject(jsonObj.getAsJsonObject("headService"));
      }
      if ((jsonObj.get("serviceType") != null && !jsonObj.get("serviceType").isJsonNull()) && !jsonObj.get("serviceType").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `serviceType` to be a primitive type in the JSON string but got `%s`", jsonObj.get("serviceType").toString()));
      }
      // validate the required field `template`
      V1RayJobSpecRayClusterSpecHeadGroupSpecTemplate.validateJsonObject(jsonObj.getAsJsonObject("template"));
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!V1RayJobSpecRayClusterSpecHeadGroupSpec.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'V1RayJobSpecRayClusterSpecHeadGroupSpec' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<V1RayJobSpecRayClusterSpecHeadGroupSpec> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(V1RayJobSpecRayClusterSpecHeadGroupSpec.class));

       return (TypeAdapter<T>) new TypeAdapter<V1RayJobSpecRayClusterSpecHeadGroupSpec>() {
           @Override
           public void write(JsonWriter out, V1RayJobSpecRayClusterSpecHeadGroupSpec value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public V1RayJobSpecRayClusterSpecHeadGroupSpec read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of V1RayJobSpecRayClusterSpecHeadGroupSpec given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of V1RayJobSpecRayClusterSpecHeadGroupSpec
  * @throws IOException if the JSON string is invalid with respect to V1RayJobSpecRayClusterSpecHeadGroupSpec
  */
  public static V1RayJobSpecRayClusterSpecHeadGroupSpec fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, V1RayJobSpecRayClusterSpecHeadGroupSpec.class);
  }

 /**
  * Convert an instance of V1RayJobSpecRayClusterSpecHeadGroupSpec to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

