/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.25.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package net.statemesh.k8s.crd.rayjob.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import net.statemesh.k8s.crd.rayjob.models.V1RayJobSpecRayClusterSpecHeadGroupSpecTemplateSpecContainersInnerLifecyclePostStartExec;
import net.statemesh.k8s.crd.rayjob.models.V1RayJobSpecRayClusterSpecHeadGroupSpecTemplateSpecContainersInnerLifecyclePostStartHttpGet;
import net.statemesh.k8s.crd.rayjob.models.V1RayJobSpecRayClusterSpecHeadGroupSpecTemplateSpecContainersInnerLifecyclePostStartTcpSocket;
import net.statemesh.k8s.crd.rayjob.models.V1RayJobSpecRayClusterSpecHeadGroupSpecTemplateSpecContainersInnerLivenessProbeGrpc;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import io.kubernetes.client.openapi.JSON;

/**
 * V1RayJobSpecRayClusterSpecHeadGroupSpecTemplateSpecContainersInnerLivenessProbe
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-09-11T07:03:01.189516Z[Etc/UTC]")
public class V1RayJobSpecRayClusterSpecHeadGroupSpecTemplateSpecContainersInnerLivenessProbe {
  public static final String SERIALIZED_NAME_EXEC = "exec";
  @SerializedName(SERIALIZED_NAME_EXEC)
  private V1RayJobSpecRayClusterSpecHeadGroupSpecTemplateSpecContainersInnerLifecyclePostStartExec exec;

  public static final String SERIALIZED_NAME_FAILURE_THRESHOLD = "failureThreshold";
  @SerializedName(SERIALIZED_NAME_FAILURE_THRESHOLD)
  private Integer failureThreshold;

  public static final String SERIALIZED_NAME_GRPC = "grpc";
  @SerializedName(SERIALIZED_NAME_GRPC)
  private V1RayJobSpecRayClusterSpecHeadGroupSpecTemplateSpecContainersInnerLivenessProbeGrpc grpc;

  public static final String SERIALIZED_NAME_HTTP_GET = "httpGet";
  @SerializedName(SERIALIZED_NAME_HTTP_GET)
  private V1RayJobSpecRayClusterSpecHeadGroupSpecTemplateSpecContainersInnerLifecyclePostStartHttpGet httpGet;

  public static final String SERIALIZED_NAME_INITIAL_DELAY_SECONDS = "initialDelaySeconds";
  @SerializedName(SERIALIZED_NAME_INITIAL_DELAY_SECONDS)
  private Integer initialDelaySeconds;

  public static final String SERIALIZED_NAME_PERIOD_SECONDS = "periodSeconds";
  @SerializedName(SERIALIZED_NAME_PERIOD_SECONDS)
  private Integer periodSeconds;

  public static final String SERIALIZED_NAME_SUCCESS_THRESHOLD = "successThreshold";
  @SerializedName(SERIALIZED_NAME_SUCCESS_THRESHOLD)
  private Integer successThreshold;

  public static final String SERIALIZED_NAME_TCP_SOCKET = "tcpSocket";
  @SerializedName(SERIALIZED_NAME_TCP_SOCKET)
  private V1RayJobSpecRayClusterSpecHeadGroupSpecTemplateSpecContainersInnerLifecyclePostStartTcpSocket tcpSocket;

  public static final String SERIALIZED_NAME_TERMINATION_GRACE_PERIOD_SECONDS = "terminationGracePeriodSeconds";
  @SerializedName(SERIALIZED_NAME_TERMINATION_GRACE_PERIOD_SECONDS)
  private Long terminationGracePeriodSeconds;

  public static final String SERIALIZED_NAME_TIMEOUT_SECONDS = "timeoutSeconds";
  @SerializedName(SERIALIZED_NAME_TIMEOUT_SECONDS)
  private Integer timeoutSeconds;

  public V1RayJobSpecRayClusterSpecHeadGroupSpecTemplateSpecContainersInnerLivenessProbe() {
  }

  public V1RayJobSpecRayClusterSpecHeadGroupSpecTemplateSpecContainersInnerLivenessProbe exec(V1RayJobSpecRayClusterSpecHeadGroupSpecTemplateSpecContainersInnerLifecyclePostStartExec exec) {
    
    this.exec = exec;
    return this;
  }

   /**
   * Get exec
   * @return exec
  **/
  @jakarta.annotation.Nullable
  public V1RayJobSpecRayClusterSpecHeadGroupSpecTemplateSpecContainersInnerLifecyclePostStartExec getExec() {
    return exec;
  }


  public void setExec(V1RayJobSpecRayClusterSpecHeadGroupSpecTemplateSpecContainersInnerLifecyclePostStartExec exec) {
    this.exec = exec;
  }


  public V1RayJobSpecRayClusterSpecHeadGroupSpecTemplateSpecContainersInnerLivenessProbe failureThreshold(Integer failureThreshold) {
    
    this.failureThreshold = failureThreshold;
    return this;
  }

   /**
   * Get failureThreshold
   * @return failureThreshold
  **/
  @jakarta.annotation.Nullable
  public Integer getFailureThreshold() {
    return failureThreshold;
  }


  public void setFailureThreshold(Integer failureThreshold) {
    this.failureThreshold = failureThreshold;
  }


  public V1RayJobSpecRayClusterSpecHeadGroupSpecTemplateSpecContainersInnerLivenessProbe grpc(V1RayJobSpecRayClusterSpecHeadGroupSpecTemplateSpecContainersInnerLivenessProbeGrpc grpc) {
    
    this.grpc = grpc;
    return this;
  }

   /**
   * Get grpc
   * @return grpc
  **/
  @jakarta.annotation.Nullable
  public V1RayJobSpecRayClusterSpecHeadGroupSpecTemplateSpecContainersInnerLivenessProbeGrpc getGrpc() {
    return grpc;
  }


  public void setGrpc(V1RayJobSpecRayClusterSpecHeadGroupSpecTemplateSpecContainersInnerLivenessProbeGrpc grpc) {
    this.grpc = grpc;
  }


  public V1RayJobSpecRayClusterSpecHeadGroupSpecTemplateSpecContainersInnerLivenessProbe httpGet(V1RayJobSpecRayClusterSpecHeadGroupSpecTemplateSpecContainersInnerLifecyclePostStartHttpGet httpGet) {
    
    this.httpGet = httpGet;
    return this;
  }

   /**
   * Get httpGet
   * @return httpGet
  **/
  @jakarta.annotation.Nullable
  public V1RayJobSpecRayClusterSpecHeadGroupSpecTemplateSpecContainersInnerLifecyclePostStartHttpGet getHttpGet() {
    return httpGet;
  }


  public void setHttpGet(V1RayJobSpecRayClusterSpecHeadGroupSpecTemplateSpecContainersInnerLifecyclePostStartHttpGet httpGet) {
    this.httpGet = httpGet;
  }


  public V1RayJobSpecRayClusterSpecHeadGroupSpecTemplateSpecContainersInnerLivenessProbe initialDelaySeconds(Integer initialDelaySeconds) {
    
    this.initialDelaySeconds = initialDelaySeconds;
    return this;
  }

   /**
   * Get initialDelaySeconds
   * @return initialDelaySeconds
  **/
  @jakarta.annotation.Nullable
  public Integer getInitialDelaySeconds() {
    return initialDelaySeconds;
  }


  public void setInitialDelaySeconds(Integer initialDelaySeconds) {
    this.initialDelaySeconds = initialDelaySeconds;
  }


  public V1RayJobSpecRayClusterSpecHeadGroupSpecTemplateSpecContainersInnerLivenessProbe periodSeconds(Integer periodSeconds) {
    
    this.periodSeconds = periodSeconds;
    return this;
  }

   /**
   * Get periodSeconds
   * @return periodSeconds
  **/
  @jakarta.annotation.Nullable
  public Integer getPeriodSeconds() {
    return periodSeconds;
  }


  public void setPeriodSeconds(Integer periodSeconds) {
    this.periodSeconds = periodSeconds;
  }


  public V1RayJobSpecRayClusterSpecHeadGroupSpecTemplateSpecContainersInnerLivenessProbe successThreshold(Integer successThreshold) {
    
    this.successThreshold = successThreshold;
    return this;
  }

   /**
   * Get successThreshold
   * @return successThreshold
  **/
  @jakarta.annotation.Nullable
  public Integer getSuccessThreshold() {
    return successThreshold;
  }


  public void setSuccessThreshold(Integer successThreshold) {
    this.successThreshold = successThreshold;
  }


  public V1RayJobSpecRayClusterSpecHeadGroupSpecTemplateSpecContainersInnerLivenessProbe tcpSocket(V1RayJobSpecRayClusterSpecHeadGroupSpecTemplateSpecContainersInnerLifecyclePostStartTcpSocket tcpSocket) {
    
    this.tcpSocket = tcpSocket;
    return this;
  }

   /**
   * Get tcpSocket
   * @return tcpSocket
  **/
  @jakarta.annotation.Nullable
  public V1RayJobSpecRayClusterSpecHeadGroupSpecTemplateSpecContainersInnerLifecyclePostStartTcpSocket getTcpSocket() {
    return tcpSocket;
  }


  public void setTcpSocket(V1RayJobSpecRayClusterSpecHeadGroupSpecTemplateSpecContainersInnerLifecyclePostStartTcpSocket tcpSocket) {
    this.tcpSocket = tcpSocket;
  }


  public V1RayJobSpecRayClusterSpecHeadGroupSpecTemplateSpecContainersInnerLivenessProbe terminationGracePeriodSeconds(Long terminationGracePeriodSeconds) {
    
    this.terminationGracePeriodSeconds = terminationGracePeriodSeconds;
    return this;
  }

   /**
   * Get terminationGracePeriodSeconds
   * @return terminationGracePeriodSeconds
  **/
  @jakarta.annotation.Nullable
  public Long getTerminationGracePeriodSeconds() {
    return terminationGracePeriodSeconds;
  }


  public void setTerminationGracePeriodSeconds(Long terminationGracePeriodSeconds) {
    this.terminationGracePeriodSeconds = terminationGracePeriodSeconds;
  }


  public V1RayJobSpecRayClusterSpecHeadGroupSpecTemplateSpecContainersInnerLivenessProbe timeoutSeconds(Integer timeoutSeconds) {
    
    this.timeoutSeconds = timeoutSeconds;
    return this;
  }

   /**
   * Get timeoutSeconds
   * @return timeoutSeconds
  **/
  @jakarta.annotation.Nullable
  public Integer getTimeoutSeconds() {
    return timeoutSeconds;
  }


  public void setTimeoutSeconds(Integer timeoutSeconds) {
    this.timeoutSeconds = timeoutSeconds;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1RayJobSpecRayClusterSpecHeadGroupSpecTemplateSpecContainersInnerLivenessProbe v1RayJobSpecRayClusterSpecHeadGroupSpecTemplateSpecContainersInnerLivenessProbe = (V1RayJobSpecRayClusterSpecHeadGroupSpecTemplateSpecContainersInnerLivenessProbe) o;
    return Objects.equals(this.exec, v1RayJobSpecRayClusterSpecHeadGroupSpecTemplateSpecContainersInnerLivenessProbe.exec) &&
        Objects.equals(this.failureThreshold, v1RayJobSpecRayClusterSpecHeadGroupSpecTemplateSpecContainersInnerLivenessProbe.failureThreshold) &&
        Objects.equals(this.grpc, v1RayJobSpecRayClusterSpecHeadGroupSpecTemplateSpecContainersInnerLivenessProbe.grpc) &&
        Objects.equals(this.httpGet, v1RayJobSpecRayClusterSpecHeadGroupSpecTemplateSpecContainersInnerLivenessProbe.httpGet) &&
        Objects.equals(this.initialDelaySeconds, v1RayJobSpecRayClusterSpecHeadGroupSpecTemplateSpecContainersInnerLivenessProbe.initialDelaySeconds) &&
        Objects.equals(this.periodSeconds, v1RayJobSpecRayClusterSpecHeadGroupSpecTemplateSpecContainersInnerLivenessProbe.periodSeconds) &&
        Objects.equals(this.successThreshold, v1RayJobSpecRayClusterSpecHeadGroupSpecTemplateSpecContainersInnerLivenessProbe.successThreshold) &&
        Objects.equals(this.tcpSocket, v1RayJobSpecRayClusterSpecHeadGroupSpecTemplateSpecContainersInnerLivenessProbe.tcpSocket) &&
        Objects.equals(this.terminationGracePeriodSeconds, v1RayJobSpecRayClusterSpecHeadGroupSpecTemplateSpecContainersInnerLivenessProbe.terminationGracePeriodSeconds) &&
        Objects.equals(this.timeoutSeconds, v1RayJobSpecRayClusterSpecHeadGroupSpecTemplateSpecContainersInnerLivenessProbe.timeoutSeconds);
  }

  @Override
  public int hashCode() {
    return Objects.hash(exec, failureThreshold, grpc, httpGet, initialDelaySeconds, periodSeconds, successThreshold, tcpSocket, terminationGracePeriodSeconds, timeoutSeconds);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1RayJobSpecRayClusterSpecHeadGroupSpecTemplateSpecContainersInnerLivenessProbe {\n");
    sb.append("    exec: ").append(toIndentedString(exec)).append("\n");
    sb.append("    failureThreshold: ").append(toIndentedString(failureThreshold)).append("\n");
    sb.append("    grpc: ").append(toIndentedString(grpc)).append("\n");
    sb.append("    httpGet: ").append(toIndentedString(httpGet)).append("\n");
    sb.append("    initialDelaySeconds: ").append(toIndentedString(initialDelaySeconds)).append("\n");
    sb.append("    periodSeconds: ").append(toIndentedString(periodSeconds)).append("\n");
    sb.append("    successThreshold: ").append(toIndentedString(successThreshold)).append("\n");
    sb.append("    tcpSocket: ").append(toIndentedString(tcpSocket)).append("\n");
    sb.append("    terminationGracePeriodSeconds: ").append(toIndentedString(terminationGracePeriodSeconds)).append("\n");
    sb.append("    timeoutSeconds: ").append(toIndentedString(timeoutSeconds)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("exec");
    openapiFields.add("failureThreshold");
    openapiFields.add("grpc");
    openapiFields.add("httpGet");
    openapiFields.add("initialDelaySeconds");
    openapiFields.add("periodSeconds");
    openapiFields.add("successThreshold");
    openapiFields.add("tcpSocket");
    openapiFields.add("terminationGracePeriodSeconds");
    openapiFields.add("timeoutSeconds");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to V1RayJobSpecRayClusterSpecHeadGroupSpecTemplateSpecContainersInnerLivenessProbe
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!V1RayJobSpecRayClusterSpecHeadGroupSpecTemplateSpecContainersInnerLivenessProbe.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in V1RayJobSpecRayClusterSpecHeadGroupSpecTemplateSpecContainersInnerLivenessProbe is not found in the empty JSON string", V1RayJobSpecRayClusterSpecHeadGroupSpecTemplateSpecContainersInnerLivenessProbe.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!V1RayJobSpecRayClusterSpecHeadGroupSpecTemplateSpecContainersInnerLivenessProbe.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `V1RayJobSpecRayClusterSpecHeadGroupSpecTemplateSpecContainersInnerLivenessProbe` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }
      // validate the optional field `exec`
      if (jsonObj.get("exec") != null && !jsonObj.get("exec").isJsonNull()) {
        V1RayJobSpecRayClusterSpecHeadGroupSpecTemplateSpecContainersInnerLifecyclePostStartExec.validateJsonObject(jsonObj.getAsJsonObject("exec"));
      }
      // validate the optional field `grpc`
      if (jsonObj.get("grpc") != null && !jsonObj.get("grpc").isJsonNull()) {
        V1RayJobSpecRayClusterSpecHeadGroupSpecTemplateSpecContainersInnerLivenessProbeGrpc.validateJsonObject(jsonObj.getAsJsonObject("grpc"));
      }
      // validate the optional field `httpGet`
      if (jsonObj.get("httpGet") != null && !jsonObj.get("httpGet").isJsonNull()) {
        V1RayJobSpecRayClusterSpecHeadGroupSpecTemplateSpecContainersInnerLifecyclePostStartHttpGet.validateJsonObject(jsonObj.getAsJsonObject("httpGet"));
      }
      // validate the optional field `tcpSocket`
      if (jsonObj.get("tcpSocket") != null && !jsonObj.get("tcpSocket").isJsonNull()) {
        V1RayJobSpecRayClusterSpecHeadGroupSpecTemplateSpecContainersInnerLifecyclePostStartTcpSocket.validateJsonObject(jsonObj.getAsJsonObject("tcpSocket"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!V1RayJobSpecRayClusterSpecHeadGroupSpecTemplateSpecContainersInnerLivenessProbe.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'V1RayJobSpecRayClusterSpecHeadGroupSpecTemplateSpecContainersInnerLivenessProbe' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<V1RayJobSpecRayClusterSpecHeadGroupSpecTemplateSpecContainersInnerLivenessProbe> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(V1RayJobSpecRayClusterSpecHeadGroupSpecTemplateSpecContainersInnerLivenessProbe.class));

       return (TypeAdapter<T>) new TypeAdapter<V1RayJobSpecRayClusterSpecHeadGroupSpecTemplateSpecContainersInnerLivenessProbe>() {
           @Override
           public void write(JsonWriter out, V1RayJobSpecRayClusterSpecHeadGroupSpecTemplateSpecContainersInnerLivenessProbe value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public V1RayJobSpecRayClusterSpecHeadGroupSpecTemplateSpecContainersInnerLivenessProbe read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of V1RayJobSpecRayClusterSpecHeadGroupSpecTemplateSpecContainersInnerLivenessProbe given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of V1RayJobSpecRayClusterSpecHeadGroupSpecTemplateSpecContainersInnerLivenessProbe
  * @throws IOException if the JSON string is invalid with respect to V1RayJobSpecRayClusterSpecHeadGroupSpecTemplateSpecContainersInnerLivenessProbe
  */
  public static V1RayJobSpecRayClusterSpecHeadGroupSpecTemplateSpecContainersInnerLivenessProbe fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, V1RayJobSpecRayClusterSpecHeadGroupSpecTemplateSpecContainersInnerLivenessProbe.class);
  }

 /**
  * Convert an instance of V1RayJobSpecRayClusterSpecHeadGroupSpecTemplateSpecContainersInnerLivenessProbe to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

