/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.25.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package net.statemesh.k8s.crd.rayjob.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import net.statemesh.k8s.crd.rayjob.models.V1RayJobSpecRayClusterSpecHeadGroupSpecTemplateSpecImagePullSecretsInner;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import io.kubernetes.client.openapi.JSON;

/**
 * V1RayJobSpecRayClusterSpecHeadGroupSpecTemplateSpecVolumesInnerScaleIO
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-09-11T07:03:01.189516Z[Etc/UTC]")
public class V1RayJobSpecRayClusterSpecHeadGroupSpecTemplateSpecVolumesInnerScaleIO {
  public static final String SERIALIZED_NAME_FS_TYPE = "fsType";
  @SerializedName(SERIALIZED_NAME_FS_TYPE)
  private String fsType;

  public static final String SERIALIZED_NAME_GATEWAY = "gateway";
  @SerializedName(SERIALIZED_NAME_GATEWAY)
  private String gateway;

  public static final String SERIALIZED_NAME_PROTECTION_DOMAIN = "protectionDomain";
  @SerializedName(SERIALIZED_NAME_PROTECTION_DOMAIN)
  private String protectionDomain;

  public static final String SERIALIZED_NAME_READ_ONLY = "readOnly";
  @SerializedName(SERIALIZED_NAME_READ_ONLY)
  private Boolean readOnly;

  public static final String SERIALIZED_NAME_SECRET_REF = "secretRef";
  @SerializedName(SERIALIZED_NAME_SECRET_REF)
  private V1RayJobSpecRayClusterSpecHeadGroupSpecTemplateSpecImagePullSecretsInner secretRef;

  public static final String SERIALIZED_NAME_SSL_ENABLED = "sslEnabled";
  @SerializedName(SERIALIZED_NAME_SSL_ENABLED)
  private Boolean sslEnabled;

  public static final String SERIALIZED_NAME_STORAGE_MODE = "storageMode";
  @SerializedName(SERIALIZED_NAME_STORAGE_MODE)
  private String storageMode;

  public static final String SERIALIZED_NAME_STORAGE_POOL = "storagePool";
  @SerializedName(SERIALIZED_NAME_STORAGE_POOL)
  private String storagePool;

  public static final String SERIALIZED_NAME_SYSTEM = "system";
  @SerializedName(SERIALIZED_NAME_SYSTEM)
  private String system;

  public static final String SERIALIZED_NAME_VOLUME_NAME = "volumeName";
  @SerializedName(SERIALIZED_NAME_VOLUME_NAME)
  private String volumeName;

  public V1RayJobSpecRayClusterSpecHeadGroupSpecTemplateSpecVolumesInnerScaleIO() {
  }

  public V1RayJobSpecRayClusterSpecHeadGroupSpecTemplateSpecVolumesInnerScaleIO fsType(String fsType) {
    
    this.fsType = fsType;
    return this;
  }

   /**
   * Get fsType
   * @return fsType
  **/
  @jakarta.annotation.Nullable
  public String getFsType() {
    return fsType;
  }


  public void setFsType(String fsType) {
    this.fsType = fsType;
  }


  public V1RayJobSpecRayClusterSpecHeadGroupSpecTemplateSpecVolumesInnerScaleIO gateway(String gateway) {
    
    this.gateway = gateway;
    return this;
  }

   /**
   * Get gateway
   * @return gateway
  **/
  @jakarta.annotation.Nonnull
  public String getGateway() {
    return gateway;
  }


  public void setGateway(String gateway) {
    this.gateway = gateway;
  }


  public V1RayJobSpecRayClusterSpecHeadGroupSpecTemplateSpecVolumesInnerScaleIO protectionDomain(String protectionDomain) {
    
    this.protectionDomain = protectionDomain;
    return this;
  }

   /**
   * Get protectionDomain
   * @return protectionDomain
  **/
  @jakarta.annotation.Nullable
  public String getProtectionDomain() {
    return protectionDomain;
  }


  public void setProtectionDomain(String protectionDomain) {
    this.protectionDomain = protectionDomain;
  }


  public V1RayJobSpecRayClusterSpecHeadGroupSpecTemplateSpecVolumesInnerScaleIO readOnly(Boolean readOnly) {
    
    this.readOnly = readOnly;
    return this;
  }

   /**
   * Get readOnly
   * @return readOnly
  **/
  @jakarta.annotation.Nullable
  public Boolean getReadOnly() {
    return readOnly;
  }


  public void setReadOnly(Boolean readOnly) {
    this.readOnly = readOnly;
  }


  public V1RayJobSpecRayClusterSpecHeadGroupSpecTemplateSpecVolumesInnerScaleIO secretRef(V1RayJobSpecRayClusterSpecHeadGroupSpecTemplateSpecImagePullSecretsInner secretRef) {
    
    this.secretRef = secretRef;
    return this;
  }

   /**
   * Get secretRef
   * @return secretRef
  **/
  @jakarta.annotation.Nonnull
  public V1RayJobSpecRayClusterSpecHeadGroupSpecTemplateSpecImagePullSecretsInner getSecretRef() {
    return secretRef;
  }


  public void setSecretRef(V1RayJobSpecRayClusterSpecHeadGroupSpecTemplateSpecImagePullSecretsInner secretRef) {
    this.secretRef = secretRef;
  }


  public V1RayJobSpecRayClusterSpecHeadGroupSpecTemplateSpecVolumesInnerScaleIO sslEnabled(Boolean sslEnabled) {
    
    this.sslEnabled = sslEnabled;
    return this;
  }

   /**
   * Get sslEnabled
   * @return sslEnabled
  **/
  @jakarta.annotation.Nullable
  public Boolean getSslEnabled() {
    return sslEnabled;
  }


  public void setSslEnabled(Boolean sslEnabled) {
    this.sslEnabled = sslEnabled;
  }


  public V1RayJobSpecRayClusterSpecHeadGroupSpecTemplateSpecVolumesInnerScaleIO storageMode(String storageMode) {
    
    this.storageMode = storageMode;
    return this;
  }

   /**
   * Get storageMode
   * @return storageMode
  **/
  @jakarta.annotation.Nullable
  public String getStorageMode() {
    return storageMode;
  }


  public void setStorageMode(String storageMode) {
    this.storageMode = storageMode;
  }


  public V1RayJobSpecRayClusterSpecHeadGroupSpecTemplateSpecVolumesInnerScaleIO storagePool(String storagePool) {
    
    this.storagePool = storagePool;
    return this;
  }

   /**
   * Get storagePool
   * @return storagePool
  **/
  @jakarta.annotation.Nullable
  public String getStoragePool() {
    return storagePool;
  }


  public void setStoragePool(String storagePool) {
    this.storagePool = storagePool;
  }


  public V1RayJobSpecRayClusterSpecHeadGroupSpecTemplateSpecVolumesInnerScaleIO system(String system) {
    
    this.system = system;
    return this;
  }

   /**
   * Get system
   * @return system
  **/
  @jakarta.annotation.Nonnull
  public String getSystem() {
    return system;
  }


  public void setSystem(String system) {
    this.system = system;
  }


  public V1RayJobSpecRayClusterSpecHeadGroupSpecTemplateSpecVolumesInnerScaleIO volumeName(String volumeName) {
    
    this.volumeName = volumeName;
    return this;
  }

   /**
   * Get volumeName
   * @return volumeName
  **/
  @jakarta.annotation.Nullable
  public String getVolumeName() {
    return volumeName;
  }


  public void setVolumeName(String volumeName) {
    this.volumeName = volumeName;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1RayJobSpecRayClusterSpecHeadGroupSpecTemplateSpecVolumesInnerScaleIO v1RayJobSpecRayClusterSpecHeadGroupSpecTemplateSpecVolumesInnerScaleIO = (V1RayJobSpecRayClusterSpecHeadGroupSpecTemplateSpecVolumesInnerScaleIO) o;
    return Objects.equals(this.fsType, v1RayJobSpecRayClusterSpecHeadGroupSpecTemplateSpecVolumesInnerScaleIO.fsType) &&
        Objects.equals(this.gateway, v1RayJobSpecRayClusterSpecHeadGroupSpecTemplateSpecVolumesInnerScaleIO.gateway) &&
        Objects.equals(this.protectionDomain, v1RayJobSpecRayClusterSpecHeadGroupSpecTemplateSpecVolumesInnerScaleIO.protectionDomain) &&
        Objects.equals(this.readOnly, v1RayJobSpecRayClusterSpecHeadGroupSpecTemplateSpecVolumesInnerScaleIO.readOnly) &&
        Objects.equals(this.secretRef, v1RayJobSpecRayClusterSpecHeadGroupSpecTemplateSpecVolumesInnerScaleIO.secretRef) &&
        Objects.equals(this.sslEnabled, v1RayJobSpecRayClusterSpecHeadGroupSpecTemplateSpecVolumesInnerScaleIO.sslEnabled) &&
        Objects.equals(this.storageMode, v1RayJobSpecRayClusterSpecHeadGroupSpecTemplateSpecVolumesInnerScaleIO.storageMode) &&
        Objects.equals(this.storagePool, v1RayJobSpecRayClusterSpecHeadGroupSpecTemplateSpecVolumesInnerScaleIO.storagePool) &&
        Objects.equals(this.system, v1RayJobSpecRayClusterSpecHeadGroupSpecTemplateSpecVolumesInnerScaleIO.system) &&
        Objects.equals(this.volumeName, v1RayJobSpecRayClusterSpecHeadGroupSpecTemplateSpecVolumesInnerScaleIO.volumeName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(fsType, gateway, protectionDomain, readOnly, secretRef, sslEnabled, storageMode, storagePool, system, volumeName);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1RayJobSpecRayClusterSpecHeadGroupSpecTemplateSpecVolumesInnerScaleIO {\n");
    sb.append("    fsType: ").append(toIndentedString(fsType)).append("\n");
    sb.append("    gateway: ").append(toIndentedString(gateway)).append("\n");
    sb.append("    protectionDomain: ").append(toIndentedString(protectionDomain)).append("\n");
    sb.append("    readOnly: ").append(toIndentedString(readOnly)).append("\n");
    sb.append("    secretRef: ").append(toIndentedString(secretRef)).append("\n");
    sb.append("    sslEnabled: ").append(toIndentedString(sslEnabled)).append("\n");
    sb.append("    storageMode: ").append(toIndentedString(storageMode)).append("\n");
    sb.append("    storagePool: ").append(toIndentedString(storagePool)).append("\n");
    sb.append("    system: ").append(toIndentedString(system)).append("\n");
    sb.append("    volumeName: ").append(toIndentedString(volumeName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("fsType");
    openapiFields.add("gateway");
    openapiFields.add("protectionDomain");
    openapiFields.add("readOnly");
    openapiFields.add("secretRef");
    openapiFields.add("sslEnabled");
    openapiFields.add("storageMode");
    openapiFields.add("storagePool");
    openapiFields.add("system");
    openapiFields.add("volumeName");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("gateway");
    openapiRequiredFields.add("secretRef");
    openapiRequiredFields.add("system");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to V1RayJobSpecRayClusterSpecHeadGroupSpecTemplateSpecVolumesInnerScaleIO
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!V1RayJobSpecRayClusterSpecHeadGroupSpecTemplateSpecVolumesInnerScaleIO.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in V1RayJobSpecRayClusterSpecHeadGroupSpecTemplateSpecVolumesInnerScaleIO is not found in the empty JSON string", V1RayJobSpecRayClusterSpecHeadGroupSpecTemplateSpecVolumesInnerScaleIO.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!V1RayJobSpecRayClusterSpecHeadGroupSpecTemplateSpecVolumesInnerScaleIO.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `V1RayJobSpecRayClusterSpecHeadGroupSpecTemplateSpecVolumesInnerScaleIO` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : V1RayJobSpecRayClusterSpecHeadGroupSpecTemplateSpecVolumesInnerScaleIO.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      if ((jsonObj.get("fsType") != null && !jsonObj.get("fsType").isJsonNull()) && !jsonObj.get("fsType").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `fsType` to be a primitive type in the JSON string but got `%s`", jsonObj.get("fsType").toString()));
      }
      if (!jsonObj.get("gateway").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `gateway` to be a primitive type in the JSON string but got `%s`", jsonObj.get("gateway").toString()));
      }
      if ((jsonObj.get("protectionDomain") != null && !jsonObj.get("protectionDomain").isJsonNull()) && !jsonObj.get("protectionDomain").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `protectionDomain` to be a primitive type in the JSON string but got `%s`", jsonObj.get("protectionDomain").toString()));
      }
      // validate the required field `secretRef`
      V1RayJobSpecRayClusterSpecHeadGroupSpecTemplateSpecImagePullSecretsInner.validateJsonObject(jsonObj.getAsJsonObject("secretRef"));
      if ((jsonObj.get("storageMode") != null && !jsonObj.get("storageMode").isJsonNull()) && !jsonObj.get("storageMode").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `storageMode` to be a primitive type in the JSON string but got `%s`", jsonObj.get("storageMode").toString()));
      }
      if ((jsonObj.get("storagePool") != null && !jsonObj.get("storagePool").isJsonNull()) && !jsonObj.get("storagePool").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `storagePool` to be a primitive type in the JSON string but got `%s`", jsonObj.get("storagePool").toString()));
      }
      if (!jsonObj.get("system").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `system` to be a primitive type in the JSON string but got `%s`", jsonObj.get("system").toString()));
      }
      if ((jsonObj.get("volumeName") != null && !jsonObj.get("volumeName").isJsonNull()) && !jsonObj.get("volumeName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `volumeName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("volumeName").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!V1RayJobSpecRayClusterSpecHeadGroupSpecTemplateSpecVolumesInnerScaleIO.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'V1RayJobSpecRayClusterSpecHeadGroupSpecTemplateSpecVolumesInnerScaleIO' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<V1RayJobSpecRayClusterSpecHeadGroupSpecTemplateSpecVolumesInnerScaleIO> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(V1RayJobSpecRayClusterSpecHeadGroupSpecTemplateSpecVolumesInnerScaleIO.class));

       return (TypeAdapter<T>) new TypeAdapter<V1RayJobSpecRayClusterSpecHeadGroupSpecTemplateSpecVolumesInnerScaleIO>() {
           @Override
           public void write(JsonWriter out, V1RayJobSpecRayClusterSpecHeadGroupSpecTemplateSpecVolumesInnerScaleIO value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public V1RayJobSpecRayClusterSpecHeadGroupSpecTemplateSpecVolumesInnerScaleIO read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of V1RayJobSpecRayClusterSpecHeadGroupSpecTemplateSpecVolumesInnerScaleIO given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of V1RayJobSpecRayClusterSpecHeadGroupSpecTemplateSpecVolumesInnerScaleIO
  * @throws IOException if the JSON string is invalid with respect to V1RayJobSpecRayClusterSpecHeadGroupSpecTemplateSpecVolumesInnerScaleIO
  */
  public static V1RayJobSpecRayClusterSpecHeadGroupSpecTemplateSpecVolumesInnerScaleIO fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, V1RayJobSpecRayClusterSpecHeadGroupSpecTemplateSpecVolumesInnerScaleIO.class);
  }

 /**
  * Convert an instance of V1RayJobSpecRayClusterSpecHeadGroupSpecTemplateSpecVolumesInnerScaleIO to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

