/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.25.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package net.statemesh.k8s.crd.rayjob.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import net.statemesh.k8s.crd.rayjob.models.V1RayJobSpecRayClusterSpecAutoscalerOptionsSecurityContextAppArmorProfile;
import net.statemesh.k8s.crd.rayjob.models.V1RayJobSpecRayClusterSpecAutoscalerOptionsSecurityContextCapabilities;
import net.statemesh.k8s.crd.rayjob.models.V1RayJobSpecRayClusterSpecAutoscalerOptionsSecurityContextSeLinuxOptions;
import net.statemesh.k8s.crd.rayjob.models.V1RayJobSpecRayClusterSpecAutoscalerOptionsSecurityContextWindowsOptions;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import io.kubernetes.client.openapi.JSON;

/**
 * V1RayJobSpecRayClusterSpecAutoscalerOptionsSecurityContext
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-09-11T07:03:01.189516Z[Etc/UTC]")
public class V1RayJobSpecRayClusterSpecAutoscalerOptionsSecurityContext {
  public static final String SERIALIZED_NAME_ALLOW_PRIVILEGE_ESCALATION = "allowPrivilegeEscalation";
  @SerializedName(SERIALIZED_NAME_ALLOW_PRIVILEGE_ESCALATION)
  private Boolean allowPrivilegeEscalation;

  public static final String SERIALIZED_NAME_APP_ARMOR_PROFILE = "appArmorProfile";
  @SerializedName(SERIALIZED_NAME_APP_ARMOR_PROFILE)
  private V1RayJobSpecRayClusterSpecAutoscalerOptionsSecurityContextAppArmorProfile appArmorProfile;

  public static final String SERIALIZED_NAME_CAPABILITIES = "capabilities";
  @SerializedName(SERIALIZED_NAME_CAPABILITIES)
  private V1RayJobSpecRayClusterSpecAutoscalerOptionsSecurityContextCapabilities capabilities;

  public static final String SERIALIZED_NAME_PRIVILEGED = "privileged";
  @SerializedName(SERIALIZED_NAME_PRIVILEGED)
  private Boolean privileged;

  public static final String SERIALIZED_NAME_PROC_MOUNT = "procMount";
  @SerializedName(SERIALIZED_NAME_PROC_MOUNT)
  private String procMount;

  public static final String SERIALIZED_NAME_READ_ONLY_ROOT_FILESYSTEM = "readOnlyRootFilesystem";
  @SerializedName(SERIALIZED_NAME_READ_ONLY_ROOT_FILESYSTEM)
  private Boolean readOnlyRootFilesystem;

  public static final String SERIALIZED_NAME_RUN_AS_GROUP = "runAsGroup";
  @SerializedName(SERIALIZED_NAME_RUN_AS_GROUP)
  private Long runAsGroup;

  public static final String SERIALIZED_NAME_RUN_AS_NON_ROOT = "runAsNonRoot";
  @SerializedName(SERIALIZED_NAME_RUN_AS_NON_ROOT)
  private Boolean runAsNonRoot;

  public static final String SERIALIZED_NAME_RUN_AS_USER = "runAsUser";
  @SerializedName(SERIALIZED_NAME_RUN_AS_USER)
  private Long runAsUser;

  public static final String SERIALIZED_NAME_SE_LINUX_OPTIONS = "seLinuxOptions";
  @SerializedName(SERIALIZED_NAME_SE_LINUX_OPTIONS)
  private V1RayJobSpecRayClusterSpecAutoscalerOptionsSecurityContextSeLinuxOptions seLinuxOptions;

  public static final String SERIALIZED_NAME_SECCOMP_PROFILE = "seccompProfile";
  @SerializedName(SERIALIZED_NAME_SECCOMP_PROFILE)
  private V1RayJobSpecRayClusterSpecAutoscalerOptionsSecurityContextAppArmorProfile seccompProfile;

  public static final String SERIALIZED_NAME_WINDOWS_OPTIONS = "windowsOptions";
  @SerializedName(SERIALIZED_NAME_WINDOWS_OPTIONS)
  private V1RayJobSpecRayClusterSpecAutoscalerOptionsSecurityContextWindowsOptions windowsOptions;

  public V1RayJobSpecRayClusterSpecAutoscalerOptionsSecurityContext() {
  }

  public V1RayJobSpecRayClusterSpecAutoscalerOptionsSecurityContext allowPrivilegeEscalation(Boolean allowPrivilegeEscalation) {
    
    this.allowPrivilegeEscalation = allowPrivilegeEscalation;
    return this;
  }

   /**
   * Get allowPrivilegeEscalation
   * @return allowPrivilegeEscalation
  **/
  @jakarta.annotation.Nullable
  public Boolean getAllowPrivilegeEscalation() {
    return allowPrivilegeEscalation;
  }


  public void setAllowPrivilegeEscalation(Boolean allowPrivilegeEscalation) {
    this.allowPrivilegeEscalation = allowPrivilegeEscalation;
  }


  public V1RayJobSpecRayClusterSpecAutoscalerOptionsSecurityContext appArmorProfile(V1RayJobSpecRayClusterSpecAutoscalerOptionsSecurityContextAppArmorProfile appArmorProfile) {
    
    this.appArmorProfile = appArmorProfile;
    return this;
  }

   /**
   * Get appArmorProfile
   * @return appArmorProfile
  **/
  @jakarta.annotation.Nullable
  public V1RayJobSpecRayClusterSpecAutoscalerOptionsSecurityContextAppArmorProfile getAppArmorProfile() {
    return appArmorProfile;
  }


  public void setAppArmorProfile(V1RayJobSpecRayClusterSpecAutoscalerOptionsSecurityContextAppArmorProfile appArmorProfile) {
    this.appArmorProfile = appArmorProfile;
  }


  public V1RayJobSpecRayClusterSpecAutoscalerOptionsSecurityContext capabilities(V1RayJobSpecRayClusterSpecAutoscalerOptionsSecurityContextCapabilities capabilities) {
    
    this.capabilities = capabilities;
    return this;
  }

   /**
   * Get capabilities
   * @return capabilities
  **/
  @jakarta.annotation.Nullable
  public V1RayJobSpecRayClusterSpecAutoscalerOptionsSecurityContextCapabilities getCapabilities() {
    return capabilities;
  }


  public void setCapabilities(V1RayJobSpecRayClusterSpecAutoscalerOptionsSecurityContextCapabilities capabilities) {
    this.capabilities = capabilities;
  }


  public V1RayJobSpecRayClusterSpecAutoscalerOptionsSecurityContext privileged(Boolean privileged) {
    
    this.privileged = privileged;
    return this;
  }

   /**
   * Get privileged
   * @return privileged
  **/
  @jakarta.annotation.Nullable
  public Boolean getPrivileged() {
    return privileged;
  }


  public void setPrivileged(Boolean privileged) {
    this.privileged = privileged;
  }


  public V1RayJobSpecRayClusterSpecAutoscalerOptionsSecurityContext procMount(String procMount) {
    
    this.procMount = procMount;
    return this;
  }

   /**
   * Get procMount
   * @return procMount
  **/
  @jakarta.annotation.Nullable
  public String getProcMount() {
    return procMount;
  }


  public void setProcMount(String procMount) {
    this.procMount = procMount;
  }


  public V1RayJobSpecRayClusterSpecAutoscalerOptionsSecurityContext readOnlyRootFilesystem(Boolean readOnlyRootFilesystem) {
    
    this.readOnlyRootFilesystem = readOnlyRootFilesystem;
    return this;
  }

   /**
   * Get readOnlyRootFilesystem
   * @return readOnlyRootFilesystem
  **/
  @jakarta.annotation.Nullable
  public Boolean getReadOnlyRootFilesystem() {
    return readOnlyRootFilesystem;
  }


  public void setReadOnlyRootFilesystem(Boolean readOnlyRootFilesystem) {
    this.readOnlyRootFilesystem = readOnlyRootFilesystem;
  }


  public V1RayJobSpecRayClusterSpecAutoscalerOptionsSecurityContext runAsGroup(Long runAsGroup) {
    
    this.runAsGroup = runAsGroup;
    return this;
  }

   /**
   * Get runAsGroup
   * @return runAsGroup
  **/
  @jakarta.annotation.Nullable
  public Long getRunAsGroup() {
    return runAsGroup;
  }


  public void setRunAsGroup(Long runAsGroup) {
    this.runAsGroup = runAsGroup;
  }


  public V1RayJobSpecRayClusterSpecAutoscalerOptionsSecurityContext runAsNonRoot(Boolean runAsNonRoot) {
    
    this.runAsNonRoot = runAsNonRoot;
    return this;
  }

   /**
   * Get runAsNonRoot
   * @return runAsNonRoot
  **/
  @jakarta.annotation.Nullable
  public Boolean getRunAsNonRoot() {
    return runAsNonRoot;
  }


  public void setRunAsNonRoot(Boolean runAsNonRoot) {
    this.runAsNonRoot = runAsNonRoot;
  }


  public V1RayJobSpecRayClusterSpecAutoscalerOptionsSecurityContext runAsUser(Long runAsUser) {
    
    this.runAsUser = runAsUser;
    return this;
  }

   /**
   * Get runAsUser
   * @return runAsUser
  **/
  @jakarta.annotation.Nullable
  public Long getRunAsUser() {
    return runAsUser;
  }


  public void setRunAsUser(Long runAsUser) {
    this.runAsUser = runAsUser;
  }


  public V1RayJobSpecRayClusterSpecAutoscalerOptionsSecurityContext seLinuxOptions(V1RayJobSpecRayClusterSpecAutoscalerOptionsSecurityContextSeLinuxOptions seLinuxOptions) {
    
    this.seLinuxOptions = seLinuxOptions;
    return this;
  }

   /**
   * Get seLinuxOptions
   * @return seLinuxOptions
  **/
  @jakarta.annotation.Nullable
  public V1RayJobSpecRayClusterSpecAutoscalerOptionsSecurityContextSeLinuxOptions getSeLinuxOptions() {
    return seLinuxOptions;
  }


  public void setSeLinuxOptions(V1RayJobSpecRayClusterSpecAutoscalerOptionsSecurityContextSeLinuxOptions seLinuxOptions) {
    this.seLinuxOptions = seLinuxOptions;
  }


  public V1RayJobSpecRayClusterSpecAutoscalerOptionsSecurityContext seccompProfile(V1RayJobSpecRayClusterSpecAutoscalerOptionsSecurityContextAppArmorProfile seccompProfile) {
    
    this.seccompProfile = seccompProfile;
    return this;
  }

   /**
   * Get seccompProfile
   * @return seccompProfile
  **/
  @jakarta.annotation.Nullable
  public V1RayJobSpecRayClusterSpecAutoscalerOptionsSecurityContextAppArmorProfile getSeccompProfile() {
    return seccompProfile;
  }


  public void setSeccompProfile(V1RayJobSpecRayClusterSpecAutoscalerOptionsSecurityContextAppArmorProfile seccompProfile) {
    this.seccompProfile = seccompProfile;
  }


  public V1RayJobSpecRayClusterSpecAutoscalerOptionsSecurityContext windowsOptions(V1RayJobSpecRayClusterSpecAutoscalerOptionsSecurityContextWindowsOptions windowsOptions) {
    
    this.windowsOptions = windowsOptions;
    return this;
  }

   /**
   * Get windowsOptions
   * @return windowsOptions
  **/
  @jakarta.annotation.Nullable
  public V1RayJobSpecRayClusterSpecAutoscalerOptionsSecurityContextWindowsOptions getWindowsOptions() {
    return windowsOptions;
  }


  public void setWindowsOptions(V1RayJobSpecRayClusterSpecAutoscalerOptionsSecurityContextWindowsOptions windowsOptions) {
    this.windowsOptions = windowsOptions;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1RayJobSpecRayClusterSpecAutoscalerOptionsSecurityContext v1RayJobSpecRayClusterSpecAutoscalerOptionsSecurityContext = (V1RayJobSpecRayClusterSpecAutoscalerOptionsSecurityContext) o;
    return Objects.equals(this.allowPrivilegeEscalation, v1RayJobSpecRayClusterSpecAutoscalerOptionsSecurityContext.allowPrivilegeEscalation) &&
        Objects.equals(this.appArmorProfile, v1RayJobSpecRayClusterSpecAutoscalerOptionsSecurityContext.appArmorProfile) &&
        Objects.equals(this.capabilities, v1RayJobSpecRayClusterSpecAutoscalerOptionsSecurityContext.capabilities) &&
        Objects.equals(this.privileged, v1RayJobSpecRayClusterSpecAutoscalerOptionsSecurityContext.privileged) &&
        Objects.equals(this.procMount, v1RayJobSpecRayClusterSpecAutoscalerOptionsSecurityContext.procMount) &&
        Objects.equals(this.readOnlyRootFilesystem, v1RayJobSpecRayClusterSpecAutoscalerOptionsSecurityContext.readOnlyRootFilesystem) &&
        Objects.equals(this.runAsGroup, v1RayJobSpecRayClusterSpecAutoscalerOptionsSecurityContext.runAsGroup) &&
        Objects.equals(this.runAsNonRoot, v1RayJobSpecRayClusterSpecAutoscalerOptionsSecurityContext.runAsNonRoot) &&
        Objects.equals(this.runAsUser, v1RayJobSpecRayClusterSpecAutoscalerOptionsSecurityContext.runAsUser) &&
        Objects.equals(this.seLinuxOptions, v1RayJobSpecRayClusterSpecAutoscalerOptionsSecurityContext.seLinuxOptions) &&
        Objects.equals(this.seccompProfile, v1RayJobSpecRayClusterSpecAutoscalerOptionsSecurityContext.seccompProfile) &&
        Objects.equals(this.windowsOptions, v1RayJobSpecRayClusterSpecAutoscalerOptionsSecurityContext.windowsOptions);
  }

  @Override
  public int hashCode() {
    return Objects.hash(allowPrivilegeEscalation, appArmorProfile, capabilities, privileged, procMount, readOnlyRootFilesystem, runAsGroup, runAsNonRoot, runAsUser, seLinuxOptions, seccompProfile, windowsOptions);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1RayJobSpecRayClusterSpecAutoscalerOptionsSecurityContext {\n");
    sb.append("    allowPrivilegeEscalation: ").append(toIndentedString(allowPrivilegeEscalation)).append("\n");
    sb.append("    appArmorProfile: ").append(toIndentedString(appArmorProfile)).append("\n");
    sb.append("    capabilities: ").append(toIndentedString(capabilities)).append("\n");
    sb.append("    privileged: ").append(toIndentedString(privileged)).append("\n");
    sb.append("    procMount: ").append(toIndentedString(procMount)).append("\n");
    sb.append("    readOnlyRootFilesystem: ").append(toIndentedString(readOnlyRootFilesystem)).append("\n");
    sb.append("    runAsGroup: ").append(toIndentedString(runAsGroup)).append("\n");
    sb.append("    runAsNonRoot: ").append(toIndentedString(runAsNonRoot)).append("\n");
    sb.append("    runAsUser: ").append(toIndentedString(runAsUser)).append("\n");
    sb.append("    seLinuxOptions: ").append(toIndentedString(seLinuxOptions)).append("\n");
    sb.append("    seccompProfile: ").append(toIndentedString(seccompProfile)).append("\n");
    sb.append("    windowsOptions: ").append(toIndentedString(windowsOptions)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("allowPrivilegeEscalation");
    openapiFields.add("appArmorProfile");
    openapiFields.add("capabilities");
    openapiFields.add("privileged");
    openapiFields.add("procMount");
    openapiFields.add("readOnlyRootFilesystem");
    openapiFields.add("runAsGroup");
    openapiFields.add("runAsNonRoot");
    openapiFields.add("runAsUser");
    openapiFields.add("seLinuxOptions");
    openapiFields.add("seccompProfile");
    openapiFields.add("windowsOptions");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to V1RayJobSpecRayClusterSpecAutoscalerOptionsSecurityContext
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!V1RayJobSpecRayClusterSpecAutoscalerOptionsSecurityContext.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in V1RayJobSpecRayClusterSpecAutoscalerOptionsSecurityContext is not found in the empty JSON string", V1RayJobSpecRayClusterSpecAutoscalerOptionsSecurityContext.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!V1RayJobSpecRayClusterSpecAutoscalerOptionsSecurityContext.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `V1RayJobSpecRayClusterSpecAutoscalerOptionsSecurityContext` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }
      // validate the optional field `appArmorProfile`
      if (jsonObj.get("appArmorProfile") != null && !jsonObj.get("appArmorProfile").isJsonNull()) {
        V1RayJobSpecRayClusterSpecAutoscalerOptionsSecurityContextAppArmorProfile.validateJsonObject(jsonObj.getAsJsonObject("appArmorProfile"));
      }
      // validate the optional field `capabilities`
      if (jsonObj.get("capabilities") != null && !jsonObj.get("capabilities").isJsonNull()) {
        V1RayJobSpecRayClusterSpecAutoscalerOptionsSecurityContextCapabilities.validateJsonObject(jsonObj.getAsJsonObject("capabilities"));
      }
      if ((jsonObj.get("procMount") != null && !jsonObj.get("procMount").isJsonNull()) && !jsonObj.get("procMount").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `procMount` to be a primitive type in the JSON string but got `%s`", jsonObj.get("procMount").toString()));
      }
      // validate the optional field `seLinuxOptions`
      if (jsonObj.get("seLinuxOptions") != null && !jsonObj.get("seLinuxOptions").isJsonNull()) {
        V1RayJobSpecRayClusterSpecAutoscalerOptionsSecurityContextSeLinuxOptions.validateJsonObject(jsonObj.getAsJsonObject("seLinuxOptions"));
      }
      // validate the optional field `seccompProfile`
      if (jsonObj.get("seccompProfile") != null && !jsonObj.get("seccompProfile").isJsonNull()) {
        V1RayJobSpecRayClusterSpecAutoscalerOptionsSecurityContextAppArmorProfile.validateJsonObject(jsonObj.getAsJsonObject("seccompProfile"));
      }
      // validate the optional field `windowsOptions`
      if (jsonObj.get("windowsOptions") != null && !jsonObj.get("windowsOptions").isJsonNull()) {
        V1RayJobSpecRayClusterSpecAutoscalerOptionsSecurityContextWindowsOptions.validateJsonObject(jsonObj.getAsJsonObject("windowsOptions"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!V1RayJobSpecRayClusterSpecAutoscalerOptionsSecurityContext.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'V1RayJobSpecRayClusterSpecAutoscalerOptionsSecurityContext' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<V1RayJobSpecRayClusterSpecAutoscalerOptionsSecurityContext> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(V1RayJobSpecRayClusterSpecAutoscalerOptionsSecurityContext.class));

       return (TypeAdapter<T>) new TypeAdapter<V1RayJobSpecRayClusterSpecAutoscalerOptionsSecurityContext>() {
           @Override
           public void write(JsonWriter out, V1RayJobSpecRayClusterSpecAutoscalerOptionsSecurityContext value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public V1RayJobSpecRayClusterSpecAutoscalerOptionsSecurityContext read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of V1RayJobSpecRayClusterSpecAutoscalerOptionsSecurityContext given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of V1RayJobSpecRayClusterSpecAutoscalerOptionsSecurityContext
  * @throws IOException if the JSON string is invalid with respect to V1RayJobSpecRayClusterSpecAutoscalerOptionsSecurityContext
  */
  public static V1RayJobSpecRayClusterSpecAutoscalerOptionsSecurityContext fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, V1RayJobSpecRayClusterSpecAutoscalerOptionsSecurityContext.class);
  }

 /**
  * Convert an instance of V1RayJobSpecRayClusterSpecAutoscalerOptionsSecurityContext to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

