export enum TaskRunType {
  QUANTIZATION = "QUANTIZATION",
  EVALUATION = "EVALUATION",
  IMPORT_HF_MODEL = "IMPORT_HF_MODEL",
  IMPORT_HF_DATASET = "IMPORT_HF_DATASET",
  TRAIN = "TRAIN",
  FINE_TUNE = "FINE_TUNE"
}
