export enum TaskRunType {
  QUANTIZATION = "QUANTIZATION",
  EVALUATION = "EVALUATION",
  IMPORT_HF_MODEL = "IMPORT_HF_MODEL",
  IMPORT_HF_DATASET = "IMPORT_HF_DATASET",
  CHUNKING = "CHUNKING",
  QUESTION_GENERATION = "QUESTION_GENERATION",
  ANSWER_GENERATION = "ANSWER_GENERATION"
}
